### ISSUE TITLE
rabbitmq process consume too much memory

### ISSUE THREAD

**Issue by visibletrap** [docker-library/rabbitmq#1]
After pull and run, without touching anything, the beam process consumes 600MB. Is this an expected memory requirement?

**Comment by tianon** [comment]
Just tested and I get something similar:
```
VmSize:	  694920 kB
```

Also, this is in the logs, which appears relevant: (my machine has 32G of RAM total, so this number makes perfect sense)
```
=INFO REPORT==== 6-Jan-2015::21:06:54 ===
Memory limit set to 12753MB of 31884MB total.
```

It seems to be a common thing though: http://stackoverflow.com/a/6512252

**Comment by visibletrap** [comment]
I created a wheezy box on DO. Tried following commands in Dockerfile manually. It only creates a beam process which consumes only about 30MB of RAM. Not really sure the differences and how to debug this issue.
