### ISSUE TITLE
Can't access RabbitMQ management: connection refused 

### ISSUE THREAD

**Issue by Palleas** [docker-library/rabbitmq#10]
Hi,

I'm trying to use the rabbitmq image using the provided command:

````
docker run -d -e RABBITMQ_NODENAME=my-rabbit --name some-rabbit -p 8080:15672 rabbitmq:3-management
````

Once I try to go to http://localhost:8080, the page won't load. I can `curl`  http://localhost:15672 when I ssh to the container and the `docker port` command shows that ports are properly forwarded:

````
docker port 8cd41aa41e8ff5993f9ed8200d379b6c2d9eba3a3b7df218d3b196fd359f2066
15672/tcp -> 0.0.0.0:8080
````

Am I doing something wrong?

**Comment by vovimayhem** [comment]
Just a quick check: Is that port inadvertedly used by another service? Port 8080 is commonly used by webservers such as Nginx or Apache

Have you tried a different port?

**Comment by Palleas** [comment]
Sorry I'm dumb, that's because I was working on my mac via boot2docker, so it's not actually localhost:8080 but `boot2docker ip`:8080.

My bad!
