### ISSUE TITLE
Container exiting when running in on a RPi Zero

### ISSUE THREAD

**Issue by CarlosTorrecillas** [docker-library/rabbitmq#104]
Not sure if this is the right place to stick a question (I followed the link from https://hub.docker.com/r/sysrun/rpi-rabbitmq/) but I was trying to get the image running on a RPi Zero using the following yml:

rabbitmq-data:
  container_name: rabbitmq-data
  image: sander85/rpi-busybox:latest
  command: echo created
  volumes:
    - /data/mnesia

rabbitmq:
  container_name: rabbitmq
  image: sysrun/rpi-rabbitmq:latest
  ports:
    - "15672:15672"
    - "5672:5672"
  volumes_from:
    - rabbitmq-data

Both containers seem to start however the exit immediately. I get the following output from `docker ps -a`:

fc2505e2f7bc        sysrun/rpi-rabbitmq:latest    "/docker-entrypoint.s"   About an hour ago   Exited (139) 30 seconds ago                        rabbitmq
6d6a37f917db        sander85/rpi-busybox:latest   "echo created"           18 hours ago        Exited (0) 35 seconds ago                          rabbitmq-data

Which is not very useful as I can't really diagnose what's going on.

Any help would be much appreciated.

Thanks!

**Comment by yosifkit** [comment]
We are not affiliated with the `sysrun/rpi-rabbitmq` image.  The source is probably in one of @sysrun's repos and issues should be reported there.

On a side note, there might be something in `docker logs rabbitmq`.
