### ISSUE TITLE
Generate a load_definitions Block if a definitions.json is present

### ISSUE THREAD

**Issue by VolkerK** [docker-library/rabbitmq#107]
Hello,
it would be nice, if it is possible to specify definitions.json (as a Volume), and that the entrypoint writes a load_definitions block int rabbitmq.config if specified.
`
{rabbitmq_management, [
{listener, [...]},
{load_definitions, "/etc/rabbitmq/definitions.json"} ]},
`

**Comment by VolkerK** [comment]
Any suggestions what to do as a workaround ?
At the moment I'm trying to use sed to modify the rabbitmq.config file and add the load_definitions Block. But I'm stuck in the sed escaping hell at the moment.

**Comment by tianon** [comment]
Sorry for the massive delay!  This was officially implemented over in https://github.com/docker-library/rabbitmq/pull/112 and exists in the 3.7 images as well. :+1:
