### ISSUE TITLE
Couldnot find rabbitmqadmin

### ISSUE THREAD

**Issue by venkateswaris** [docker-library/rabbitmq#108]
Hi,

I am trying to create queue using rabbitmqadmin.

But rabbitmqadmin is not found in the image. Am i missing anything ?

**Comment by venkateswaris** [comment]
Hi,

I have downloaded rabbitmqadmin cli.

Please close this issue

**Comment by michaelklishin** [comment]
@venkateswaris hint: you can close issues you've opened.
