### ISSUE TITLE
rabbitmqadmin command not found in the management version

### ISSUE THREAD

**Issue by stolus** [docker-library/rabbitmq#109]
no rabbitmqadmin installed in the management version.
It should be installed as default, right?

**Comment by michaelklishin** [comment]
Enabling the plugin doesn't put `rabbitmqadmin` into `PATH`. You need to `curl` it down from the server. This is a duplicate of https://github.com/docker-library/rabbitmq/issues/108.

**Comment by stolus** [comment]
I just thought commands like`rabbitmqctl` are in the `PATH`, why can't we put `rabbitmqadmin` into `PATH` when the plugin installed. I mean in the install script.

**Comment by michaelklishin** [comment]
`rabbitmqctl` and `rabbitmq-plugins` do not come from plugins.
