### ISSUE TITLE
 $1: unbound variable -error -docker 

### ISSUE THREAD

**Issue by rajkumar49** [docker-library/rabbitmq#111]
Hi , 
i am combining RabbitMQ and one custom Web App in single docker image. 
so i am planning to run the docker-entrypoint.sh which will run two other  .sh files.
i am getting below error when docker-entrypoint.sh calls the rabbitmq-start.sh : 
(i am using official rabbitmq's docker-entrypoint.sh content in the rabbitmq-start.sh)
 
root@ubuntu-docker-xxxx-2:~/platform/rabbitmq-with-webapp# docker logs test-app
/usr/local/bin/rabbitmq-start.sh: line 5: **$1: unbound variable**

**rabbitmq-start.sh content :**

#!/bin/bash
set -eu

(allow the container to be started with `--user`)
if [[ "$1" == rabbitmq* ]] && [ "$(id -u)" = '0' ]; then
        if [ "$1" = 'rabbitmq-server' ]; then
                chown -R rabbitmq /var/lib/rabbitmq
        fi
        exec gosu rabbitmq "$BASH_SOURCE" "$@"
fi
( backwards compatibility for old environment variables)
: "${RABBITMQ_SSL_CERTFILE:=${RABBITMQ_SSL_CERT_FILE:-}}"
: "${RABBITMQ_SSL_KEYFILE:=${RABBITMQ_SSL_KEY_FILE:-}}"
: "${RABBITMQ_SSL_CACERTFILE:=${RABBITMQ_SSL_CA_FILE:-}}"
....

**Comment by yosifkit** [comment]
You need to call the entrypoint script from our image (your `rabbitmq-start.sh`) with the correct arguement, namely `rabbitmq-server`.  This is why there is `ENTRYPOINT` and `CMD` in the Dockerfile.

```bash
# I assume you are doing something like this

# initialize stuff

rabbitmq-start.sh rabbitmq-server &
exec run-webapp-script.sh
```

As a side note, I would not recommend running two processes in a container with a simple shell script.  In my example above, if rabbitmq died there would be no simple way to restart it without killing the whole container and on the flip side, if my webapp dies the rabbit server would just be killed.  I would recommend configuring the web service to connect to `rabbitmq` hostname, rather than `localhost` and then use docker-compose to spin it all up.  If you are really set on multiple services in one container, then something like `supervisord` should do what you need.

**Comment by rajkumar49** [comment]
thanks

**Comment by soulraven** [comment]
I have the same problem, when i try to start the server like this:

> docker run -it progeek/rabbitmq:3.6.5
> ./docker-entrypoint.sh: line 5: $1: unbound variable

how normally the server is started?
I have flow the exemple from here: https://github.com/harbur/docker-rabbitmq-cluster and the same problem, missing argument from the entrypoint

**Comment by yosifkit** [comment]
@soulraven
`progeek/rabbitmq` is not maintained by us, so I am not sure how it works.  If your image is calling `docker-entrypoint.sh`, then it has to supply an argument to it: `docker-entrypoint.sh rambbitmq-server`.

**Comment by soulraven** [comment]
progeek/rabbitmq is the same only i have change from jessie to xenial. The rest is all the same no change.
So i still don't understand why this argument is used like this, how is used in real word.
Because is not working even with compost or simple docker run.
Even this repository is not working, and throw the same error

**Comment by tianon** [comment]
@soulraven I can't reproduce the failure -- can you supply more information about how you're running it?
```console
$ docker pull rabbitmq
Using default tag: latest
latest: Pulling from library/rabbitmq

43c265008fae: Already exists 
0146d97f81e3: Pull complete 
8ac5e342a5e7: Pull complete 
a6263dd284bd: Pull complete 
9cb455a5fd9b: Pull complete 
6c9ce1b88386: Pull complete 
dc332e8e2850: Pull complete 
df2420500769: Pull complete 
8b285cd01a4a: Pull complete 
9f074d067133: Pull complete 
0cccb79c30c5: Pull complete 
fe7502a32c46: Pull complete 
e452f983c3a6: Pull complete 
ae197cc7bd38: Pull complete 
37d9266d2c32: Pull complete 
Digest: sha256:da14264ee63c5b05799869baeb24c3547a8b57fc1d368185c132973f59ad07c3
Status: Downloaded newer image for rabbitmq:latest
$ docker run -it --rm rabbitmq

              RabbitMQ 3.6.5. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########
              Starting broker...

=INFO REPORT==== 8-Nov-2016::17:27:27 ===
Starting RabbitMQ 3.6.5 on Erlang 19.0.7
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 8-Nov-2016::17:27:27 ===
node           : rabbit@66ca2779a2b8
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : rZG1OUEnGhVHG8U3kaqW/g==
log            : tty
sasl log       : tty
database dir   : /var/lib/rabbitmq/mnesia/rabbit@66ca2779a2b8

=INFO REPORT==== 8-Nov-2016::17:27:28 ===
Memory limit set to 12859MB of 32148MB total.

=INFO REPORT==== 8-Nov-2016::17:27:28 ===
Disk free limit set to 50MB

=INFO REPORT==== 8-Nov-2016::17:27:28 ===
Limiting to approx 1048476 file handles (943626 sockets)

=INFO REPORT==== 8-Nov-2016::17:27:28 ===
FHC read buffering:  OFF
FHC write buffering: ON

=INFO REPORT==== 8-Nov-2016::17:27:29 ===
Database directory at /var/lib/rabbitmq/mnesia/rabbit@66ca2779a2b8 is empty. Initialising from scratch...

=INFO REPORT==== 8-Nov-2016::17:27:29 ===
    application: mnesia
    exited: stopped
    type: temporary

=INFO REPORT==== 8-Nov-2016::17:27:29 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 8-Nov-2016::17:27:29 ===
Adding vhost '/'

=INFO REPORT==== 8-Nov-2016::17:27:30 ===
Creating user 'guest'

=INFO REPORT==== 8-Nov-2016::17:27:30 ===
Setting user tags for user 'guest' to [administrator]

=INFO REPORT==== 8-Nov-2016::17:27:30 ===
Setting permissions for 'guest' in '/' to '.*', '.*', '.*'

=INFO REPORT==== 8-Nov-2016::17:27:30 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 8-Nov-2016::17:27:30 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=WARNING REPORT==== 8-Nov-2016::17:27:30 ===
msg_store_persistent: rebuilding indices from scratch

=INFO REPORT==== 8-Nov-2016::17:27:30 ===
started TCP Listener on [::]:5672
 completed with 0 plugins.

=INFO REPORT==== 8-Nov-2016::17:27:30 ===
Server startup complete; 0 plugins started.

```
