### ISSUE TITLE
Setting default user credentials when extending from image

### ISSUE THREAD

**Issue by rhyslbw** [docker-library/rabbitmq#113]
I'm having trouble setting the default user after extending from this image for the purpose of running my own init script. I expect to just be able to set the ENVs when running a container from the following image, with the variables used in the parent's runtime. I've verified my custom ENVs are set, however the default user is still 'guest'.
``` Dockerfile
FROM rabbitmq:3.6.5-management
ADD init.sh /init.sh
EXPOSE 15672
# Define default command
CMD ["/init.sh"]
```
Am I missing something?

**Comment by yosifkit** [comment]
Setting your script as `CMD` means that the image will start with `docker-entrypoint.sh /init.sh`, so anything in your script will happen after the entrypoint script finishes, since it ends in `exec "$@"`.

**Comment by derickbailey** [comment]
i'm not sure i understand the comment @yosifkit 

setting the default username and password w/ the command line options is handled inside of the `docker-entrypoint.sh` file, though

`docker run ... -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password`

how does using the `CMD` of a dockerfile affect that, if docker-entrypoint is still run?

**Comment by yosifkit** [comment]
The config file is not generated from your environment variables unless the entrypoint script gets [`rabbitmq-server` as its argument](https://github.com/docker-library/rabbitmq/blob/ca2f23e34d2077ec3885700a644a1c4163923a0b/docker-entrypoint.sh#L208).  With your script being `CMD` then the only argument the entyrypoint script gets is `/init.sh` and so it does not generate a config file.

**Comment by rhyslbw** [comment]
Ah thanks for pointing this out @yosifkit. Do you see any problem instead overriding `ENTRYPOINT` with a slightly different init script, then running _docker-entrypoint.sh_ after the sleeping subshell passing `rabbitmq-server` as the first param?  I'm using `exec` to ensure it's pid 1 inside the container 

``` Dockerfile
FROM rabbitmq:3.6.5-management
ADD init.sh /init.sh
RUN chmod +x /init.sh
EXPOSE 15672
ENTRYPOINT ["/init.sh"]
```

``` shell
#!/bin/sh
( sleep 15 ; \
# Create users
rabbitmqctl add_user my-user-1 $RABBITMQ_USER_PASSWORD_1 2>/dev/null ; \
rabbitmqctl set_permissions -p / my-user-1  ".*" ".*" ".*" ; \

exec docker-entrypoint.sh rabbitmq-server $@
```

**Comment by yosifkit** [comment]
That should work.  You may need/want to add `gosu rabbitmq` to drop to the `rabbitmq` user for each of your `rabbitmqctl` commands.  Also, if you have ssl config, you might need the same variables that get exported at the [end of docker-entrypoint.sh](https://github.com/docker-library/rabbitmq/blob/ca2f23e34d2077ec3885700a644a1c4163923a0b/docker-entrypoint.sh#L275-L277).

On a side note, I'm always hesitant to use sleepy bash jobs to hack around container service start, but I don't really have great alternatives.  Start a second container that is just a client to add users? Run a script that starts the container and then does a `docker exec` to add users?

**Comment by rhyslbw** [comment]
> On a side note, I'm always hesitant to use sleepy bash jobs to hack around container service start

I agree. We're really undermining the integrity here. A separate management service feels like the best approach and one that is in harmony with the Docker way. Considering this is an orchestration task I'm going to push the responsibility up to docker-compose.

I did come across some useful information in the docs on [multiple compose files] under the section 'Administrative tasks'(https://docs.docker.com/compose/extends/#/multiple-compose-files). In this case I will likely just run a service in the same stack but good to know there are options to isolate that if needed.

> Another common use case is running adhoc or administrative tasks against one or more services in a Compose app. This example demonstrates running a database backup.
