### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by jonapich** [docker-library/rabbitmq#116]
As mentioned in #76, docker users get painted in the corner when they use environment variables to configure aspects of the configuration file since the rabbitmq.config file will get overriden by the script because of [the haveConfig flag.](https://github.com/docker-library/rabbitmq/blob/master/docker-entrypoint.sh#L68)

At the base, the script should probably at least provide a generic and dumb way to inject raw definitions to be appended to the rabbitmq.config file, kinda like what the Chef Cookbook does. This way, everyone will be able to leverage some sort of workaround around the features they need. Unfortunately my sh skills are close to none and I can't possibly contribute this feature in a solid way.

Alternatively, implementing distributed config files (/etc/rabbitmq.config.d/) could solve this problem nicely. Another approach would be to allow for flat-json to be introduced in the environment variables; for instance, providing something like `RABBITMQ_CONFIG_RAW.rabbitmq.reverse_dns_lookup=true`.

In my particular use-case, I am required to implement the LDAP auth backend. For now, I am thinking of forking and borrow the pattern introduced in #112 to add an LDAP section as well. Is this kind of implementation acceptable for an eventual PR?

**Comment by yosifkit** [comment]
> Given docker-library/docs#1011, and that 3.7 introduced the new (trivial to write/append to) ini/sysctl-style configuration format (https://www.rabbitmq.com/configure.html#config-file-formats), I'm going to close this.
>
> In Kubernetes, it should be pretty trivial to create a config object which gets inserted at `/etc/rabbitmq/rabbitmq.conf` with the desired settings included. :+1:
>
> (Or to create a derivative image `FROM` this one which adds a simple `ENTRYPOINT` that appends the contents of an environment variable to the above-noted file.)
>
> \- https://github.com/docker-library/rabbitmq/issues/186#issuecomment-382878415
