### ISSUE TITLE
proposal: create vhost from env_var

### ISSUE THREAD

**Issue by dpetzel** [docker-library/rabbitmq#12]
Taking a page from https://registry.hub.docker.com/u/library/mysql/, it would be nice if this image could create an alternate vhost from env vars. This would make working with this image via docker-compose or Vagrant just a little bit simpler as it would allow folks to not need to create their own image on top of this one and/or have some provisioning step to create their vhost

* `RABBITMQ_VHOST` - An alternate VHOST to create. The var should be optional, but when set this VHOST would be created
* `RABBITMQ_VHOST_USER` - If set, would create a user with admin rights to that vhost
* `RABBITMQ_VHOST_PASSWORD` - Set the password for the supplied VHOST user

**Comment by yosifkit** [comment]
That sounds perfectly reasonable :+1:.  Want to take a crack at it?  This is just like the sql databases and creating a database, user, and password ([more info](https://www.rabbitmq.com/access-control.html)).

@tianon any opinions here?

**Comment by dpetzel** [comment]
If its something that's likely to be accepted, I wouldn't mind taking a crack at it.

**Comment by tianon** [comment]
I'm definitely interested :+1:

**Comment by vovimayhem** [comment]
Cool :+1:

**Comment by dpetzel** [comment]
So I finally got around to taking a crack at this and was interested in getting some feedback. Would the expectation be that this vhost and creds would *replace* the defaults ("/" and "guest"), or would this be in addition to? I'm leaning toward it being in addition to, however that comes with some complications. In order to add a new vhost and user Rabbit has to be running. Since it runs in the foreground this makes post startup stuff tricky. The only idea I had was to background the initial run, create the stuff, kill the initial run, restart in foreground. That sounds really gross though and was hoping maybe someone had a better idea.

**Comment by dpetzel** [comment]
FWIW, going the replacement route is super easy. I'm just not sure if that what most folks would want.

**Comment by yosifkit** [comment]
Since this is [access control](https://www.rabbitmq.com/access-control.html), replacement route sounds less hacky while following the same semantics as the postgres image where the only user is the one specified with a known default.

**Comment by moimael** [comment]
I also would prefer to replace default guest user ! There is another rqbbitmq image doing so by creating rabbit config file from env var in entry point script .

**Comment by tianon** [comment]
Fixed by #28, additional discussion in #29.
