### ISSUE TITLE
Release earlier versions of RabbitMQ

### ISSUE THREAD

**Issue by mavarazy** [docker-library/rabbitmq#126]
I'm working on a project, that is using RabbitMQ 3.1.2 in development and I want to use Docker easiness in managing my development environment.

Ideally, the project should switch to latest RabbitMQ, but this is not possible in foreseeable feature, and I still want to take advantages.

I would create my own Docker image, but I'm not planning to support it.
Can you release earlier versions of RabbitMQ?

**Comment by michaelklishin** [comment]
@mavarazy has been out of 3.1.x any kind of support in any way by Team RabbitMQ or Pivotal for over 2 years. Sorry but asking Docker image maintainers to support is too much to ask. You are on your own.

**Comment by yosifkit** [comment]
Agreed, thanks @michaelklishin.  You *should* be able to use our Dockerfile as a starting place for creating you own image.  Good luck!
