### ISSUE TITLE
SSL/TLS and rabbitmqctl problem connecting to node

### ISSUE THREAD

**Issue by lzalewsk** [docker-library/rabbitmq#130]
Hi,
My goul is to setup 2 node claster with SSL/TLS using docker.
I have started from one node configuration and I wander is it correct behavior
My example container initialization:
```
docker run -d \
--name rabbit-ssl-test \
--hostname my-rabbit \
-p 5671:5671 -p 15671:15671 \
-e RABBITMQ_ERLANG_COOKIE='ZHVwYWR1cGE=' \
-e RABBITMQ_NODENAME=rabbit@my-rabbit \
-e RABBITMQ_SSL_CERT_FILE=/cert_rabbitmq/cert.pem \
-e RABBITMQ_SSL_KEY_FILE=/cert_rabbitmq/key.pem \
-e RABBITMQ_SSL_CA_FILE=/cert_rabbitmq/cacert.pem \
-e RABBITMQ_DEFAULT_USER=user \
-e RABBITMQ_DEFAULT_PASS=password \
-v /opt/localvolume/ssl:/cert_rabbitmq \
rabbitmq:3-management
```
Then I wanted put 
```
rabbitmqctl stop_app
rabbitmqctl join_cluster rabbit@maasdockvm2
rabbitmqctl start_app
```
but simple status check give me:

```
root@my-rabbit:/# rabbitmqctl status
Status of node 'rabbit@my-rabbit' ...
Error: unable to connect to node 'rabbit@my-rabbit': nodedown

DIAGNOSTICS
===========

attempted to contact: ['rabbit@my-rabbit']

rabbit@my-rabbit:
  * connected to epmd (port 4369) on my-rabbit
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed

  * TCP connection to remote host has timed out. Is the Erlang distribution using TLS?


current node details:
- node name: 'rabbitmq-cli-35@my-rabbit'
- home dir: /var/lib/rabbitmq
- cookie hash: M3SYfC4HB3C3yAdt+eKepw==
```

Any suggestions?

**Comment by tianon** [comment]
How are you running `rabbitmqctl`?  Via `docker exec`, or a second container?

**Comment by lzalewsk** [comment]
Within the container.
After `docker exec -it rabbit-ssl-test bash`

**Comment by tianon** [comment]
Ah, it's probably because your `docker exec` is missing `ERL_SSL_PATH`, `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS`, and/or `RABBITMQ_CTL_ERL_ARGS` (https://github.com/docker-library/rabbitmq/blob/c766dd4dad64dd1c5550febff7e19ab763b7c5a4/docker-entrypoint.sh#L271-L278).

Can you try again with `docker-entrypoint.sh rabbitmqctl ...` or even `docker exec -it rabbit-ssl-test docker-entrypoint.sh bash` followed by simply `rabbitmqctl ...`?

**Comment by lzalewsk** [comment]
Works,
Now it's clear.
Thank tianon.
