### ISSUE TITLE
Complete documentation of supported environment variables

### ISSUE THREAD

**Issue by ash9002** [docker-library/rabbitmq#138]
Is there a full list of supported environment variables for the official RabbitMQ Docker image anywhere?

I've looked at https://github.com/docker-library/docs/blob/master/rabbitmq/README.md and https://hub.docker.com/_/rabbitmq/ but neither seem to provide any such documentation or point to a link which does - unless I've missed something.

**Comment by tianon** [comment]
Ouch, good point -- RabbitMQ itself supports several, but we add a bunch more in `docker-entrypoint.sh`: https://github.com/docker-library/rabbitmq/blob/bded33b6598e8e2b5a92b5c2a1bbebd255edf24a/debian/docker-entrypoint.sh (which really do need to be documented)

**Comment by zoidbergwill** [comment]
Of what I can see at a glance by printing the config keys with:

```
for configKey in "${allConfigKeys[@]}"; do
  echo "$configKey" | tr "[:lower:]" "[:upper:]" | sed -e "s/^/RABBITMQ_/g"
done
```

We have

```
RABBITMQ_MANAGEMENT_SSL_CACERTFILE
RABBITMQ_MANAGEMENT_SSL_CERTFILE
RABBITMQ_MANAGEMENT_SSL_DEPTH
RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT
RABBITMQ_MANAGEMENT_SSL_KEYFILE
RABBITMQ_MANAGEMENT_SSL_VERIFY
RABBITMQ_DEFAULT_PASS
RABBITMQ_DEFAULT_USER
RABBITMQ_DEFAULT_VHOST
RABBITMQ_HIPE_COMPILE
RABBITMQ_VM_MEMORY_HIGH_WATERMARK
RABBITMQ_SSL_CACERTFILE
RABBITMQ_SSL_CERTFILE
RABBITMQ_SSL_DEPTH
RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT
RABBITMQ_SSL_KEYFILE
RABBITMQ_SSL_VERIFY
```

**Comment by zoidbergwill** [comment]
Some documented images have Markdown tables which make for nice summaries of configurable options.

**Comment by zoidbergwill** [comment]
And then we could link to https://www.rabbitmq.com/configure.html#define-environment-variables as well.

**Comment by tianon** [comment]
Here's an updated list (https://github.com/docker-library/rabbitmq/pull/197#issuecomment-350081071 -- where we're discussing maybe removing some/all of these for 3.7+):

> - `RABBITMQ_DEFAULT_PASS`
> - `RABBITMQ_DEFAULT_USER`
> - `RABBITMQ_DEFAULT_VHOST`
> - `RABBITMQ_ERLANG_COOKIE`
> - `RABBITMQ_HIPE_COMPILE`
> - `RABBITMQ_MANAGEMENT_SSL_CACERTFILE`
> - `RABBITMQ_MANAGEMENT_SSL_CERTFILE`
> - `RABBITMQ_MANAGEMENT_SSL_DEPTH`
> - `RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT`
> - `RABBITMQ_MANAGEMENT_SSL_KEYFILE`
> - `RABBITMQ_MANAGEMENT_SSL_VERIFY`
> - `RABBITMQ_SSL_CACERTFILE`
> - `RABBITMQ_SSL_CERTFILE`
> - `RABBITMQ_SSL_DEPTH`
> - `RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT`
> - `RABBITMQ_SSL_KEYFILE`
> - `RABBITMQ_SSL_VERIFY`
> - `RABBITMQ_VM_MEMORY_HIGH_WATERMARK`
