### ISSUE TITLE
3.5.0 broken — exited immediately

### ISSUE THREAD

**Issue by develar** [docker-library/rabbitmq#14]
1) docker run rabbitmq:3.5.0 

Server not started, container exited immediately.

2) docker run rabbitmq:3.4.4

Server started, works as expected.

**Comment by alex-sherwin** [comment]
Apparently the binary changed location or something similar?  You can use 3.5.0 by specifying the full path to the `rabbitmq-server` binary like this:

`docker run -it -d -e RABBITMQ_NODENAME=my-rabbit --name=rabbitmq rabbitmq3.5-management /usr/lib/rabbitmq/lib/rabbitmq_server-3.5.0/sbin/rabbitmq-server`

**Comment by aldobongio** [comment]
Please now rebuild the image: the current "rabbitmq" image on the official Docker Hub Registry has the following timestamp "2015-03-20T07:58:18.749473722Z" and therefore it is still broken
