### ISSUE TITLE
set_permissions and set_user_tags on Container Load

### ISSUE THREAD

**Issue by marchofreason** [docker-library/rabbitmq#140]
Hi all,

I'm struggling to figure out what's the best way to set permissions and user tags on runtime with the rabbitmq container. 
There are evidently not environmental variables for this and it seems that most people are using a bash script to do this on build 

Something like:

```
FROM rabbitmq:3-management

# Add script to create default users / vhosts
ADD init.sh /init.sh

# Set correct executable permissions
RUN chmod +x /init.sh

# Define default command
CMD ["/init.sh"]
```

This just ends up overriding the default docker-entrypoint.sh and causes all sorts of issues. Is there a more robust way of doing this?

**Comment by blissdev** [comment]
@marchofreason Did you figure out a more robust way?
