### ISSUE TITLE
Segmentation fault in rabbitmq:alpine

### ISSUE THREAD

**Issue by sega-yarkin** [docker-library/rabbitmq#142]
When I try to limit CPU cores for a container with `rabbitmq:alpine`, the container stops with segmentation fault:

```sh
$ docker container run -it --rm --cpus=1 --cpuset-cpus="0" rabbitmq:alpine
Segmentation fault (core dumped)
```

```sh
$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)
```

**Comment by yosifkit** [comment]
Hmm, I can reproduce on docker `1.13.1` with the newest image but have no idea why it fails. 😕 The Debian based image works fine.

Not really a solution, but why limit it to a specific cpu core when you are already limiting it to one core worth of activity with `cpus=1`?

**Comment by yosifkit** [comment]
I can also reproduce with the Alpine package for `rabbitmq-server` in [edge testing](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/rabbitmq-server).

Removing `--cpus` does not change the outcome; it fails when a value to `--cpuset-cpus` does not give it all cores available (on a system with one physical CPU, I don't have a machine with multiple physical CPUs).  So `docker container run -it --rm --cpuset-cpus=0-7 rabbitmq:alpine` works on my machine because that is all the cores of the system, ie not limited at all.

**Comment by sega-yarkin** [comment]
@yosifkit  I want to pin containers to specific cores to have a full isolation and get full utilization of CPU caches. It looks like the problem in compatibility Erlang and Alpine Linux, because Debian and CentOS work well with these parameters.

**Comment by renich** [comment]
Same here:

~~~
# docker container run -it --rm --cpus=1 --cpuset-cpus="0" rabbitmq:alpine
Unable to find image 'rabbitmq:alpine' locally
alpine: Pulling from library/rabbitmq
627beaf3eaaf: Already exists 
079ada2a602c: Already exists 
c8b76ba05073: Already exists 
3ca62166aad9: Already exists 
7135a346decf: Already exists 
dbf7c356704c: Already exists 
f77d8db7a4fb: Already exists 
3c9fd3558f62: Already exists 
851eb24a3922: Already exists 
Digest: sha256:f0331cc7846647de67409248a4736776e03cc9d0a2e49d8f1471d9df776c6600
Status: Downloaded newer image for rabbitmq:alpine
Segmentation fault (core dumped)

# docker verison
docker: 'verison' is not a docker command.
See 'docker --help'
root@turlo-mx-renich:~/docker/rabbitmq# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:40:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:40:33 2017
 OS/Arch:      linux/amd64
 Experimental: false

# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
~~~
