### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by WaltHP** [docker-library/rabbitmq#153]
It would be nice to have official ARM architecture support.

I got it working on the raspberry pi 3 with the following changes to the Dockerfile

https://gist.github.com/bd7d209f0dd007f461627cc8dc31fd63

**Comment by michaelklishin** [comment]
So you switched to the default apt repo to obtain Erlang. That makes sense. Would a separate Dockerfile for ARM suffice?

**Comment by tianon** [comment]
Looking at the http://packages.erlang-solutions.com/debian repo, they appear to have packages built for `armhf` -- I wonder if they're ARMv6 or ARMv7.

**Comment by tianon** [comment]
http://packages.erlang-solutions.com/debian/pool/esl-erlang_19.2-1~raspbian~jessie_armhf.deb is definitely going to be ARMv6 :smile:

**Comment by yosifkit** [comment]
With https://github.com/docker-library/rabbitmq/pull/167, we currently build the rabbitmq imagesfor the following architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x.
