### ISSUE TITLE
Cluster don't work!

### ISSUE THREAD

**Issue by leshin** [docker-library/rabbitmq#154]
Compose:
```docker
rabbit1:
  image: rabbitmq:3.6.9-management-alpine
  hostname: rabbit1
  ports:
    - "5672:5672"
    - "8000:15672"
  environment:
    - RABBITMQ_ERLANG_COOKIE=mycookie
    - RABBITMQ_DEFAULT_USER=myuser
    - RABBITMQ_DEFAULT_PASS=mypass

rabbit2:
  image: rabbitmq:3.6.9-management-alpine
  hostname: rabbit2
  links:
    - rabbit1
  environment: 
    - RABBITMQ_ERLANG_COOKIE=mycookie
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
    - RAM_NODE=true
  ports:
    - "5673:5672"
    - "8001:15672"

rabbit3:
  image: rabbitmq:3.6.9-management-alpine
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment: 
    - RABBITMQ_ERLANG_COOKIE=mycookie
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
  ports:
    - "5674:5672"
```

**Comment by michaelklishin** [comment]
Can you please be more specific than "it does not work"? If you expect others to spend their time helping you, please help them help you by providing at least

 * A description of your expectations
 * A list of steps taken to verify them
 * Server logs

**Comment by Viszeral** [comment]
The reason that compose file "does not work" is because the containers don't have two way name resolution with that linking structure.  Here's a compose file that works "out of the box" with the clustering features of the container.

Compose:
```version: '2'

networks:
  rabbitnet:
    driver: bridge

services:
  rabbit1:
    image: rabbitmq:3.6.9-management-alpine
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "8000:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=mycookie
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypass
    networks:
      - rabbitnet

  rabbit2:
    image: rabbitmq:3.6.9-management-alpine
    hostname: rabbit2
    environment:
      - RABBITMQ_ERLANG_COOKIE=mycookie
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
      - RAM_NODE=true
    ports:
      - "5673:5672"
      - "8001:15672"
    networks:
      - rabbitnet

  rabbit3:
    image: rabbitmq:3.6.9-management-alpine
    hostname: rabbit3
    environment:
      - RABBITMQ_ERLANG_COOKIE=mycookie
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
    ports:
      - "5674:5672"
      - "8002:15672"
    networks:
      - rabbitnet```


Note that if you're using Swarm you'll want to change the network driver to `overlay`.

**Comment by leshin** [comment]
@michaelklishin It's only discover one node.

**Comment by Gsantomaggio** [comment]
Use a network definition is a common practise to resolve the hostnames, [here is an example](https://github.com/Gsantomaggio/rabbitmqexample/blob/master/cluster_docker_compose/cluster_conf/docker-compose.yml)

The hostname resolutions is required by the RabbitMQ to create the cluster, see here for detail:
https://www.rabbitmq.com/clustering.html

So I don't think this is a bug.

**NOTE:**
These parameters:
```
 - CLUSTERED=true
 - CLUSTER_WITH=rabbit1
```
are valid for harbur image: https://github.com/harbur/docker-rabbitmq-cluster not for this image

**Comment by Gsantomaggio** [comment]
I'd close this issue WDYT ?
@yosifkit @michaelklishin

**Comment by michaelklishin** [comment]
@Gsantomaggio looks like this has been answered, so I concur.
