### ISSUE TITLE
Version 3.6.10 not published?

### ISSUE THREAD

**Issue by Meabed** [docker-library/rabbitmq#157]
Version 3.6.10 not published?
https://hub.docker.com/_/rabbitmq/

**Comment by Meabed** [comment]
hello ?

**Comment by michaelklishin** [comment]
@Meabed it's a long weekend in some areas of the world and you filed this on a Saturday or so. Please be patient.

**Comment by Meabed** [comment]
:) i understand, just wondering its been 3 days now hehe :)

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/2993 :+1:

(Sorry for the delay -- we were indeed out for the US holiday.)
