### ISSUE TITLE
Please alter Docker Hub image description

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#158]
@yosifkit @tianon apologies if what I'm about to ask can be changed with a PR, GitHub search is failing me.

Docker Hub's page [for this image](https://hub.docker.com/_/rabbitmq/) describes RabbitMQ as
"a highly reliable enterprise messaging system based on the emerging AMQP standard."

On behalf of team RabbitMQ, can it be changed to

"an open source multi-protocol messaging broker."

We feel this description is more to the point and does not use blanket marketing statements.

**Comment by michaelklishin** [comment]
Thanks to @Gsantomaggio I figured where the docs are. Here's a PR: https://github.com/docker-library/docs/pull/917.

**Comment by tianon** [comment]
https://github.com/docker-library/docs/pull/917 is now merged!  Thanks :heart: :heart:
