### ISSUE TITLE
RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: unbound variable

### ISSUE THREAD

**Issue by mikenowak** [docker-library/rabbitmq#160]
It appears that this is caused by #159 

++ erl -eval 'io:format("~p", [code:lib_dir(ssl, ebin)]),halt().' -noshell
+ export 'ERL_SSL_PATH="/usr/lib/erlang/lib/ssl-8.1.1/ebin"'
+ ERL_SSL_PATH='"/usr/lib/erlang/lib/ssl-8.1.1/ebin"'
+ sslErlArgs='-pa "/usr/lib/erlang/lib/ssl-8.1.1/ebin" -proto_dist inet_tls -ssl_dist_opt server_certfile /tmp/combined.pem -ssl_dist_opt server_secure_renegotiate true client_secure_renegotiate true'
/docker-entrypoint.sh: line 401: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: unbound variable

**Comment by michaelklishin** [comment]
@mikenowak would you mind providing a bit more details about how this can be reproduced?

**Comment by mikenowak** [comment]
@michaelklishin hi, and sorry about that.

Basically I am suspecting that the problem is with this line:

`export RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="$RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS $sslErlArgs"`

that in my case gets evaluated as:

`export RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="$RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS -pa "/usr/lib/erlang/lib/ssl-8.1.1/ebin" -proto_dist inet_tls -ssl_dist_opt server_certfile /tmp/combined.pem -ssl_dist_opt server_secure_renegotiate true client_secure_renegotiate true"`

Mind the double quotes twice over there.

In case you need it, here is how I start the container:

`docker run -d --restart always --name rabbitmq --hostname rabbitmq -p 5671:5671 -p 15671:15671 -e RABBITMQ_SSL_CERT_FILE="/etc/ssl/certs/server.crt" -e RABBITMQ_SSL_KEY_FILE="/etc/ssl/certs/server.key" -e RABBITMQ_SSL_CA_FILE="/etc/ssl/certs/CASA-CA.pem" -e RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT="false" -v /etc/ssl/certs:/etc/ssl/certs:ro -v rabbitmq_var-lib-rabbitmq:/var/lib/rabbitmq rabbitmq:latest`

Let me know if you need anything else.

**Comment by tianon** [comment]
Doh, excellent catch -- I'll submit a fix ASAP.

**Comment by michaelklishin** [comment]
@mikenowak thank you.
