### ISSUE TITLE
ps command for rabbitmqctl wait

### ISSUE THREAD

**Issue by alterationx10** [docker-library/rabbitmq#162]
I believe the default ps that comes with alpine is a BusyBox command. `rabbitmqctl wait` seems to use ps, but doesn't properly wait with it. I get something like:

>  Waiting for rabbit@54e9f3ce2ca9
> pid is 6
> Error: process_not_running

Adding in `RUN apk --no-cache add procps` in my Dockerfile seems to fix the issue. Perhaps it would be good to add this into the main image at`rabbitmq/3.6/alpine/Dockerfile`?

**Comment by yosifkit** [comment]
That sounds reasonable to me. :+1:

**Comment by alterationx10** [comment]
I put in a pull request for it :smiley:

**Comment by alterationx10** [comment]
Looks like pull request got merged :-)
