### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [docker-library/rabbitmq#175]
I want to build this image on arm64 architecture but I don't find arm64 package in this file http://www.rabbitmq.com/debian/dists/testing/InRelease , So I want to know this image whether or not support arm64 architecture.

**Comment by yosifkit** [comment]
It looks like there are arm64 packages now.  I'm not sure when they were added.  We had specifically removed arm64 from our list.
https://github.com/docker-library/rabbitmq/blob/7d76799247764423a69438f72961ef0581788e07/generate-stackbrew-library.sh#L97-L101

But now it is the Release file!  So I am going to run a quick build test on an arm64 box and then hopefully we'll have a new arch to add.
```
 f1510f1402394eee74cdb37bc51ba964 665 main/binary-arm64/Packages
 1f81bea1fd6fc6fbe71cb016193adb88 454 main/binary-arm64/Packages.gz
 de9347dadb4ca991e60fc6c4fd9de08c 178 main/binary-arm64/Release
```

**Comment by yosifkit** [comment]
Ok, worked! PR incoming!

**Comment by longquan7** [comment]
@yosifkit OK
