### ISSUE TITLE
Version 3.6.11 not published to dockerhub

### ISSUE THREAD

**Issue by Meabed** [docker-library/rabbitmq#176]
Version 3.6.11 not published to dockerhub ?
https://hub.docker.com/_/rabbitmq/

**Comment by yosifkit** [comment]
> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/rabbitmq" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/rabbitmq), especially [PRs with the "library/rabbitmq" label on that repo](https://github.com/docker-library/official-images/labels/library%2Frabbitmq). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

https://github.com/docker-library/official-images/pull/3336 was just merged, so the images are in process of building. It should be up shortly.
