### ISSUE TITLE
Can't add environment variable to running rabbitmq container

### ISSUE THREAD

**Issue by w7089** [docker-library/rabbitmq#178]
After running RabbitMQ container _coo_ from the image.

Trying:

`docker exec c00 --env HOSTNAME=5`

Gives error

> rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:262: starting container process caused "exec: \"--v\": executable file not found in $PATH"

Trying to set any environment variable fails.
What's wrong?
Thanks in advance.

**Comment by Gsantomaggio** [comment]
This is not a RabbitMQ image problem.

Please read posts as:

https://stackoverflow.com/questions/41349007/set-environment-variable-in-running-docker-contianer

your command is trying to execute `--env HOSTNAME=5` that is not recognized.

**Comment by w7089** [comment]
Sorry, thanks
