### ISSUE TITLE
Upstreaming fixes to RabbitMQ

### ISSUE THREAD

**Issue by dumbbell** [docker-library/rabbitmq#18]
Hi!

I'm working on RabbitMQ to fix the issues you encounter with RabbitMQ in a Docker image and I would like to discuss how I can help you (the corresponding issue on our side is rabbitmq/rabbitmq-server#113). I am very new to Docker so I apologize for any mistakes or non-sense :)

By looking at the `Dockerfile`, I see at least two problems you work around:

1. Docker expects the contained application to write log messages to stdout. In rabbitmq/rabbitmq-server@68d628cf2891b17e6cb225e6a6782b7ca94fd158 (not merged yet), I propose to use the environment variables `RABBITMQ_LOGS=-` and `RABBITMQ_SASL_LOGS=-` to send everything to stdout. Is this ok with you?
2. Apparently, rabbitmq/rabbitmq-server@ec851de0e9a9d70620aacef5ad59592fbea75c81 broke the Docker image and you needed to use gosu and call the real `rabbitmq-server` script directly. Ironically, I made this change because a Docker user reported a problem with the lack of exec to start the server. I admit I didn't tested the fix in Docker by lack of knowledge/time and trusted him.

Is there anything else to ease the integration of RabbitMQ in Docker?

**Comment by tianon** [comment]
For the first issue, that patch looks awesome; so much love :heart:.  I'd so love to stop `sed`ding the startup script in the hacky way that we do.

For the second issue, I'm not sure there's going to be a good solution upstream -- `sudo` and `su` both behave poorly with respect to ttys, signal handling/passing, and staying resident in the process tree, which is why we use the simplified `gosu` which _only_ does the `setuid`/`setgid` portion of the functionality of these other tools.  I'd love to switch to using `USER` directly instead, but we can't do anything with permissions before starting the server if we do that, so that's a no-go.

**Comment by tianon** [comment]
If you've got any advice on #6, help or thoughts there (and anywhere/everywhere else) would be appreciated also. :+1:

**Comment by dumbbell** [comment]
Yeah, gosu seems perfect here. I was confident su(1) didn't fork a process but I was wrong... I'm going to remove that `exec` before `su ...` anyway, it's useless.

I will take a look at #6 in a week; I will be away for a few days.

Thanks for getting back to me so quickly!

**Comment by yosifkit** [comment]
Thanks for caring about your docker users :heart_eyes_cat:.

**Comment by tianon** [comment]
Yeah absolutely; we love it when upstream actually gets involved. :+1: :heart:

**Comment by dumbbell** [comment]
No problem, that's my pleasure! When you have issues with RabbitMQ, please don't hesitate to report them either on our mailing-list or on GitHub.

**Comment by dumbbell** [comment]
Hi guys!

I merged the two branches I had related to Docker (log to stdout, no need to "exec" before "su"). Do you see anything else we should fix?

FYI, we plan to release RabbitMQ 3.5.2 next week.

**Comment by yosifkit** [comment]
Thanks!  I don't know of anything else, but I am not actively using it.  Maybe one of our users like @vovimayhem would know something else that should be fixed?

**Comment by tianon** [comment]
If this lets us get SASL logs to stdout too, that's going to be a massive
improvement by itself.  Doing so without the hacky "sed" we're doing now is
even more sugar on top! :heart:

(When we tried pushing SASL to stdout too previously, everything crashed
and burned.)

**Comment by vovimayhem** [comment]
@yosifkit Not that I'm aware of... I stopped trying to persist the mnesia files in a mounted volume. I'm happy now. The TSL/SSL issue I found was fixed a couple of releases ago.

:heart:

**Comment by dumbbell** [comment]
Great, thank you all for your feedback!
