### ISSUE TITLE
/var/lib/rabbitmq/.erlang.cookie is different from the one given in RABBITMQ_ERLANG_COOKIE env variable

### ISSUE THREAD

**Issue by w7089** [docker-library/rabbitmq#180]
Hi, i'm trying to configure cluster using docker swarm. 
So specified in _yaml_ for each of the service running rabbitmq replica

```
      environment:
        - RABBITMQ_ERLANG_COOKIE=LQKLAGNROLGHUYELNBVY

```
Entering each of the 3 running containers and running _env_ gives:

```
...
RABBITMQ_ERLANG_COOKIE=LQKLAGNROLGHUYELNBVY
...
```

Though cat _/var/lib/rabbitmq/.erlang.cookie_ gives different value for each container.
So, can't configure cluster and getting error:

>  * Authentication failed (rejected by the remote node), please check the Erlang cookie

while running _rabbitmqctl join_cluster ..._ command.
How to overcome this?

Followed:

> Erlang Cookie
> 
> See the RabbitMQ "Clustering Guide" for more information about cookies and why they're necessary.
> 
> For setting a consistent cookie (especially useful for clustering but also for remote/cross-container administration via rabbitmqctl), use RABBITMQ_ERLANG_COOKIE:
> 
> $ docker run -d --hostname my-rabbit --name some-rabbit -e RABBITMQ_ERLANG_COOKIE='secret cookie here' rabbitmq:3

From the image documentation and expected it to work.

**Comment by bwheatley** [comment]
What was the issue you had @w7089?
