### ISSUE TITLE
Add tag with autocluster plugin

### ISSUE THREAD

**Issue by Fank** [docker-library/rabbitmq#183]
Currently only a tag with the management plugin exists.   
There should be a tag that also contains the [autocluster plugin](https://github.com/rabbitmq/rabbitmq-autocluster) currently it only supports ubuntu base not alpine (tested 0.8.0).

**Comment by Gsantomaggio** [comment]
@Fank please read this https://github.com/docker-library/rabbitmq/pull/121
We already spoke about it

**Comment by michaelklishin** [comment]
@Fank there is at least one separate image that includes [rabbitmq-autocluster](https://github.com/rabbitmq/rabbitmq-autocluster). I really doubt this project should mess with that plugin for a few reasons:

 * It supports N backends, some of which have enough configurable settings to look scary
 * Starting with 3.7.0, that plugin will be partially in RabbitMQ core, partially in separate backend plugins such as [rabbitmq-peer-discovery-consul](https://github.com/rabbitmq/rabbitmq-peer-discovery-consul)
 * A separate image can build on top of this one.

**Comment by Fank** [comment]
Thanks havn't found it.

**Comment by Fank** [comment]
Yea but if 3.7 gets released this should be enabled by default, i saw that multiple person are in need of this one.

**Comment by michaelklishin** [comment]
@Fank please spend sometime figuring out what will be [available in 3.7.0](http://next.rabbitmq.com/cluster-formation.html) around cluster formation. It is not a single "feature" and I really don't think it should be advertised or implemented as such in this image. It can be N features or N new images.

**Comment by michaelklishin** [comment]
@Gsantomaggio @tianon FWIW maybe it's the place where this image's plans w.r.t. cluster formation features in 3.7.0 can be discussed.

**Comment by tianon** [comment]
@michaelklishin yeah, that sounds sane!

Just to get things started, I used the following diff to get something built so I could start playing around:
```diff
diff --git a/3.6/debian/Dockerfile b/3.6/debian/Dockerfile
index 7a8cfc9..734b63a 100644
--- a/3.6/debian/Dockerfile
+++ b/3.6/debian/Dockerfile
@@ -63,10 +63,10 @@ RUN set -ex; \
        gpg --export "$key" > /etc/apt/trusted.gpg.d/rabbitmq.gpg; \
        rm -rf "$GNUPGHOME"; \
        apt-key list
-RUN echo 'deb http://www.rabbitmq.com/debian testing main' > /etc/apt/sources.list.d/rabbitmq.list
+RUN echo 'deb http://dl.bintray.com/rabbitmq/debian-dev stretch rabbitmq-server-v3.7.x' > /etc/apt/sources.list.d/rabbitmq.list
 
-ENV RABBITMQ_VERSION 3.6.11
-ENV RABBITMQ_DEBIAN_VERSION 3.6.11-1
+ENV RABBITMQ_VERSION 3.7.0-alpha.380
+ENV RABBITMQ_DEBIAN_VERSION 3.7.0~alpha.380-1
 
 RUN apt-get update && apt-get install -y --no-install-recommends \
                rabbitmq-server=$RABBITMQ_DEBIAN_VERSION \
```

One of the first issues I ran into is that `rabbitmq-plugins list ...` now requires the server to be online (unlike `...-plugins enable` and `disable`, which can optionally be performed offline, and how `list` used to be).  There must be some new way to check whether the management plugin is enabled?

Other than that issue, everything appears to start up correctly. :smile:

**Comment by michaelklishin** [comment]
@tianon yes, `rabbitmq-plugins` in 3.7.0 performs a lot more validations. That particular one can be dropped, I guess, or `--offline` should be supported by `list`. I filed https://github.com/rabbitmq/rabbitmq-cli/issues/219.

It is safe to enable `rabbitmq_management` with `--offline` even if it's already enabled. Plugin activation should be idempotent. Would this work for this image?

**Comment by michaelklishin** [comment]
@tianon https://github.com/rabbitmq/rabbitmq-cli/pull/220, will be in a new 3.7.0 milestone we hope to publish in a couple of days.

**Comment by tianon** [comment]
Very nice! :metal:

It's used in the entrypoint script to detect whether or not management is enabled so that we can generate appropriate configuration for it conditionally.  In the `Dockerfile`, we already use `--offline`: :smile:

https://github.com/docker-library/rabbitmq/blob/42d8debb805a0721ee7e666502fcf15bb7c3280a/3.6/debian/management/Dockerfile#L3
