### ISSUE TITLE
[Request] Add support for cluster_partition_handling through ENV var

### ISSUE THREAD

**Issue by boeboe** [docker-library/rabbitmq#186]
FYI,

I have added support to configure cluster_partition_handling strategy through the use of an ENV variable. Very handy in container orchestration platforms like Kubernetes.

Pull request: https://github.com/docker-library/rabbitmq/pull/185

Kindly,
Bart

**Comment by foxylion** [comment]
I second this, we have the same requirements. Did the same modifications. Would be handesome if is already included.

**Comment by tianon** [comment]
See also the related docker-library/docs#1011.

**Comment by tianon** [comment]
Given docker-library/docs#1011, and that 3.7 introduced the new (trivial to write/append to) ini/sysctl-style configuration format (https://www.rabbitmq.com/configure.html#config-file-formats), I'm going to close this.

In Kubernetes, it should be pretty trivial to create a config object which gets inserted at `/etc/rabbitmq/rabbitmq.conf` with the desired settings included. :+1:

(Or to create a derivative image `FROM` this one which adds a simple `ENTRYPOINT` that appends the contents of an environment variable to the above-noted file.)

**Comment by sergey-safarov** [comment]
Same result you can mounting `/etc/rabbitmq/advanced.config` file into container of standard image
Example of `advanced.config`
```
[
 {rabbit,
  [%%
   %% cluster_formation.peer_discovery_backend = rabbit_peer_discovery_dns
   %% cluster_formation.dns.hostname = rmq.discovery
   {cluster_formation,
    [
     {peer_discovery_backend, rabbit_peer_discovery_dns},
     {peer_discovery_dns,
      [
       {hostname, "rmq.discovery"}
      ]
     }
    ]
   },

   %% Setting cluster behaviour after split brain
   {cluster_partition_handling, autoheal}
  ]
 }
].
```
