### ISSUE TITLE
rabbitmq:3-management docker image is borked

### ISSUE THREAD

**Issue by ealter** [docker-library/rabbitmq#188]
It was working earlier today.

```
$ docker pull rabbitmq:3-management 
3-management: Pulling from library/rabbitmq
no matching manifest for linux/amd64 in the manifest list entries
```

I tried this on both Mac OSX as well as Ubuntu Trusty.

**Comment by tianon** [comment]
Still some kinks to iron out from https://github.com/docker-library/official-images/issues/2289 -- got `amd64` builds running now, so this will automatically update once those finish (that image is hilariously `ppc64le`-only right now).

**Comment by tianon** [comment]
Should be fixed now. :+1:

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:
