### ISSUE TITLE
Rabbitmq3 management exited directly

### ISSUE THREAD

**Issue by Freyskeyd** [docker-library/rabbitmq#19]
Hey,

i'm running:
```
docker run -d -e 'RABBITMQ_NODENAME=my-rabbit' --name rabbitmq -p 8080:15672 rabbitmq:3-management
```

but container exit (error 1): without sending any log information.

**Comment by tianon** [comment]
Can you try again with the latest version (`docker pull rabbitmq:3-management`), and perhaps with `-it` as well?
