### ISSUE TITLE
rabbitmq:management image (version 3.6.12) won't import valid broker definitions exported from a 3.6.6 image

### ISSUE THREAD

**Issue by dcominottim** [docker-library/rabbitmq#190]
Running the command

`docker run -d --security-opt label:disable --hostname rabbitmq-dev --name rabbitmq-dev -p 5672:5672 -p 15672:15672 rabbitmq:management`

logging in to the web console and trying to import broker definitions that were exported from a 3.6.6 image won't work -- RabbitMQ says [almost immediately] that the import was successful but queues, exchanges, etc. don't actually show up.

As a workaround, I pulled the rabbitmq:3.6.6-management image instead and the import does work.

**Comment by michaelklishin** [comment]
@dcominottim it has nothing to do with this image. See server log for clues and make sure you always import definitions using a user is an administrator and has permissions to every vhost there is.

If you still can figure it out with the suggestions above, start a rabbitmq-users and provide the file used for definitions as well as the exact steps to reproduce.

**Comment by michaelklishin** [comment]
Also make sure that you are importing definitions for *all* vhosts and not just one (or use [definition loading on startup from a local file](http://www.rabbitmq.com/management.html)).

**Comment by dcominottim** [comment]
Here are the exact steps to reproduce:

1. In a terminal, run the command

`docker run -d --security-opt label:disable --hostname rabbitmq-dev --name rabbitmq-dev -p 5672:5672 -p 15672:15672 rabbitmq:management`

2. Access `http://localhost:15672` and log in with `guest:guest`

3. On the "Import / export definitions" section, select the attached JSON file (extract it first), click on "Upload broker definitions," and click on "OK" on the modal dialog

4. RabbitMQ says the import was successful, but no queues, exchanges, etc. have actually been imported

On the other hand, if the `rabbitmq:3.6.6-management` image is specified on step 1, everything is imported perfectly.

Please let me know if you need anything else.
[rabbit_definitions.zip](https://github.com/docker-library/rabbitmq/files/1310529/rabbit_definitions.zip)

**Comment by yosifkit** [comment]
If the import is supposed to end with 322 exchanges and 302 queues, then it worked here.  I did not disable SELinux, since I don't run it.

```console
$ docker run -it --rm --hostname rabbitmq-dev --name rabbitmq-dev rabbitmq:3.6.12-management
... (just the logs from import)
=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Creating user 'myuser1'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting user tags for user 'myuser1' to [administrator]

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Creating user 'myuser2'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting user tags for user 'myuser2' to [administrator]

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting user tags for user 'guest' to [administrator]

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Creating user 'myuser3'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting user tags for user 'myuser3' to [administrator]

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Creating user 'myuser4'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting user tags for user 'myuser4' to [administrator]

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Adding vhost 'qa'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Adding vhost 'preprod'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Adding vhost 'dev'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Adding vhost 'integracao'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Adding vhost 'hotfix'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting permissions for 'guest' in 'hotfix' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting permissions for 'myuser2' in 'dev' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting permissions for 'myuser1' in 'integracao' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting permissions for 'guest' in 'dev' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting permissions for 'myuser4' in 'dev' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting permissions for 'myuser3' in 'preprod' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting permissions for 'myuser3' in 'qa' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:44 ===
Setting permissions for 'myuser1' in 'dev' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser4' in '/' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser2' in 'preprod' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser3' in 'dev' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser4' in 'preprod' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser2' in 'qa' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser1' in 'hotfix' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser1' in '/' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser2' in 'hotfix' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser3' in '/' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'guest' in 'preprod' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'guest' in 'qa' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser4' in 'hotfix' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'guest' in 'integracao' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser1' in 'qa' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser2' in '/' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser4' in 'qa' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser3' in 'hotfix' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'myuser1' in 'preprod' to '.*', '.*', '.*'

=INFO REPORT==== 18-Sep-2017::22:54:45 ===
Setting permissions for 'guest' in '/' to '.*', '.*', '.*'
```

![image](https://user-images.githubusercontent.com/896423/30568697-7daced72-9c8b-11e7-9029-a30e498e690e.png)

**Comment by dcominottim** [comment]
Your result seems OK -- that is what I am expecting. There is something strange here. Running the same command that you ran, there is no extra log output whatsoever after I run the import and see the success message on the browser. The last log output I see is

```
=INFO REPORT==== 19-Sep-2017::00:15:06 ===
Server startup complete; 6 plugins started.
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_web_dispatch
 * amqp_client
 * cowboy
 * cowlib
```

Any ideas? I am running Fedora 26 and Docker 1.13.1 (the default from Fedora's repos).

**Comment by dcominottim** [comment]
I have tested the command on Debian 9 with Docker 17.06.2-ce and everything works as expected. I suppose there is some issue with the Docker version that is shipped in Fedora 26 or something similar.

**Comment by michaelklishin** [comment]
@dcominottim according to the provided steps and the log, the import process was never started. I suspect it's a UI code issue of some kind, so see browser's JS console and recent HTTP requests.

**Comment by dcominottim** [comment]
@michaelklishin You are right -- it works in Chromium 60 but not in Firefox 55. I have not identified any obvious problem in Firefox's console, but I have created two HAR archives (one for Chromium and one for Firefox). 

[HAR.zip](https://github.com/docker-library/rabbitmq/files/1314255/HAR.zip)

**Comment by michaelklishin** [comment]
@tianon I think we have enough evidence that this is not an issue with the image by any stretch.

@dcominottim ironically [this HAR analyzer](https://toolbox.googleapps.com/apps/har_analyzer/) fails to load the Firefox version :) Since you have two options that work around this, I suggest that we leave it here. If it becomes a common enough issue, we will investigate what's going on in the management UI code (unless that entire form gets replaced with a new UI by then).

**Comment by yosifkit** [comment]
I'm going to close the issue since it is not a problem with the image.
