### ISSUE TITLE
[Request]SSL Config Enhancement - versions and ciphers environmental variables

### ISSUE THREAD

**Issue by dozor** [docker-library/rabbitmq#192]
Please add the ability to pass environmental variables to set the SSL options for "versions" and "ciphers".

Being able to set things such as TLSv1.2 and eliminate 3DES ciphers is important in highly scrutinized security environments.

**Comment by michaelklishin** [comment]
See https://github.com/docker-library/docs/pull/1011 for a way to set any configuration setting you want via `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS `.

**Comment by tianon** [comment]
Indeed, and in 3.7, this should be even easier to configure via the newer configuration file format (see https://github.com/docker-library/rabbitmq/pull/197 for where that discussion is happening). :+1:
