### ISSUE TITLE
Please switch to Package Cloud/Bintray/GitHub for provisioning

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#194]
Team RabbitMQ has plans to [turn rabbitmq.com/releases and rabbitmq.com Debian repo into read-only archives](https://groups.google.com/forum/#!topic/rabbitmq-users/9ASVq55wXnA) in a few months and fully switch to Bintray/Package Cloud/GitHub for artifact distribution and repositories.

It would be great if this image could switch to e.g. Package Cloud before that. Nothing is going to break for currently released versions but new ones likely won't be available.

I'm happy to look into a PR if @tianon and @yosifkit share their opinion on which source(s) they prefer and what would be the best migration path.

**Comment by michaelklishin** [comment]
Oh, I don't mind others doing the actual work ;) Why are GitHub tags difficult to generate programmatically, though? Up to 3.6.x they have been pretty consistent. 3.7.0 might use a different version but if anything, it is more straightforward since we dropped the `rabbitmq_` prefix and use dots instead of underscores.

**Comment by tianon** [comment]
Right, I didn't mean difficult in the sense of impossible, but difficult in that the logic for doing so is slightly more than "put version number in URL and gogogo", and we'll have to scrape those pages anyhow during `./update.sh` (to get the exact Debian version number, for example), so we might as well just embed that directly in the `Dockerfile` at `./update.sh` time to keep the `Dockerfile` simpler and more straightforward (and with my current in-progress `update.sh` changes, it'll automatically detect which of the two formats is being used, so we can seamlessly update to 3.7's newer/simpler format). :+1:

**Comment by michaelklishin** [comment]
Replacing the entire URL is fine and what we do in the Chef cookbook. Debian package revision number is a separate value still but it is almost always `1`.

**Comment by tianon** [comment]
@michaelklishin ok, cool :smile: :heart:

I figure the Debian revision will pretty much _always_ be `-1`, but the goal is to try to isolate us from any unexpected future turbulence as much as we can. :innocent:
