### ISSUE TITLE
No matching manifest for windows/amd64 in the manifest list entries.

### ISSUE THREAD

**Issue by webstep-or** [docker-library/rabbitmq#198]
I'm trying to set up rabbitmq on Windows Server 2016.

docker run -d --hostname my-rabbit --name some-rabbit rabbitmq:3

I get this
No matching manifest for windows/amd64 in the manifest list entries.

**Comment by yosifkit** [comment]
There is not even a windows image available. Duplicate of https://github.com/docker-library/rabbitmq/issues/168.

**Comment by martineza79** [comment]
Try switching to Linux containers: 
![switchtolinuxcontainers](https://user-images.githubusercontent.com/20962711/34421459-590a0224-ebdd-11e7-9615-43d50011044f.PNG)

**Comment by panoskarajohn** [comment]
What if you want to run with aspnet core for windows and rabbitmq?

**Comment by tianon** [comment]
@panoskarajohn then you'll either need to run RabbitMQ on another host (or VM) or you'll need to create your own Windows-based image of RabbitMQ (and there are likely some clues for doing so over in https://github.com/docker-library/rabbitmq/issues/168)

**Comment by abhibt** [comment]
Faced same problem, after I selected "Switch to Linux Containers" it worked for me.
