### ISSUE TITLE
Allow to set User/pass via env var

### ISSUE THREAD

**Issue by moimael** [docker-library/rabbitmq#20]
Hi,

First thanks for this docker image, really made my day !

Right now i'm forced to create a volume containing rabbitmq.config to change default rabbitmq user/pass (which cannot stay guest/guest in any production environment).

So i was wondering if this image could natively integrate the possibility of setting them via docker env var ? I saw some third party rabbit images doing so.

What do you think ?

**Comment by yosifkit** [comment]
There was some discussion in https://github.com/docker-library/rabbitmq/issues/12, but I never saw a PR for it :disappointed:.

**Comment by moimael** [comment]
There are 2 PR for this, any ETA ? :)
