### ISSUE TITLE
Unable to start rabbitmq-server as root

### ISSUE THREAD

**Issue by mfojtak** [docker-library/rabbitmq#200]
rabbitmq-server is always started as rabbitmq user.
There should a possibility to run it as root.
If we need to map /var/lib/rabbitmq to persistent volume in Kubernetes the folder is not accessible by rabbitmq user and container crashes.

Also, why there are two exec commands in docker-entrypoint? What is the point?

This line in docker-entrypoint looks fishy:
```
exec gosu rabbitmq "$BASH_SOURCE" "$@"
```

It basically says - everytime you try to start docker-entrypoint as root, the rabbitmq-server will be started as hardcoded user - rabbitmq. It is kind of illogical.

**Comment by tianon** [comment]
We strive with all the official images to run as non-root as much as possible, usually only using root just long enough to fix permissions on any directories that matter (especially volumes like `/var/lib/rabbitmq`), and then step down -- see https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user for more details about that recommendation.

The lines in question are the following:

https://github.com/docker-library/rabbitmq/blob/ed9a656804f0f14a6b6b99fc7d71ba1a043854f5/3.6/debian/docker-entrypoint.sh#L26-L32

As you can see, before we step down from root, we set the appropriate permissions on `/var/lib/rabbitmq` such that `rabbitmq-server` can use it properly once we're no longer root, so it sounds like some part of that isn't working in your deployment for some reason, and it'd be good if we could figure out a simple way to reproduce the issue (preferably without a full k8s setup :wink:), so we can work on a fix!

**Comment by thenewguy** [comment]
@tianon I've hit this issue where the ssl key file is passed in from the host as read only by root.  So later in the script when it is attempted to cat the key file, it doesn't have permissions
