### ISSUE TITLE
pidfile change

### ISSUE THREAD

**Issue by timchenxiaoyu** [docker-library/rabbitmq#209]
I run rabbitmq -v -v /data/rabbitmq-data/:/var/lib/rabbitmq to mount data.  if I rm docker container and recreate another ,but pid change and data loss ,how to solve this?

![wechatimg5](https://user-images.githubusercontent.com/9782796/33112810-0b0d8f64-cf90-11e7-9934-87186a498e35.jpeg)

**Comment by yosifkit** [comment]
You need to set a hostname.

> One of the important things to note about RabbitMQ is that it stores data based on what it calls the "Node Name", which defaults to the hostname. What this means for usage in Docker is that we should specify `-h`/`--hostname` explicitly for each daemon so that we don't get a random hostname and can keep track of our data:
>
> \- [Docker Hub docs](https://github.com/docker-library/docs/tree/288848ced007206bbf589098e8498a20c53dd6f3/rabbitmq#running-the-daemon)

**Comment by timchenxiaoyu** [comment]
ths,you are right
