### ISSUE TITLE
Request for improvement: adding tzdata package to alpine containers

### ISSUE THREAD

**Issue by alexxkn** [docker-library/rabbitmq#211]
Hello.

I would like you to add a "tzdata" package to the alpine containers, in order to correctly display the time in the logs. Then the timezone can be passed through the environment variable TZ="<value>".

**Comment by qedrakmar** [comment]
From https://github.com/docker-library/docs/tree/master/rabbitmq:

To minimize image size, it's uncommon for additional related tools (such as git or bash) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [alpine image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).
