### ISSUE TITLE
3.7 not published to docker

### ISSUE THREAD

**Issue by Meabed** [docker-library/rabbitmq#216]
Hey guys 
the image it not published to docker hub yet.

Thanks :)

**Comment by tianon** [comment]
Indeed, the update is in https://github.com/docker-library/official-images/pull/3795, and our build servers are a little bit overwhelmed right now (due to https://github.com/docker-library/official-images/pull/3791), but it should go up soon. :+1:

**Comment by tianon** [comment]
This is up now.
