### ISSUE TITLE
Unable to pull rabbitmq:3-management

### ISSUE THREAD

**Issue by deepakinseattle** [docker-library/rabbitmq#217]
We first noticed this in our CI environment about an hour ago (2:00 PM PST). I'm not sure what could be causing this. Possibly related to 301c52ad6d75075aa8b42b0977e4f54866c0af96 ?

```
$ docker pull rabbitmq:3-management
3-management: Pulling from library/rabbitmq
no supported platform found in manifest list
```

```
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.24 (downgraded from 1.23)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.6
 API version:  1.24 (minimum version )
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by BrainMonkey** [comment]
Also getting error with new image on Ubuntu System

```management: Pulling from library/rabbitmq
no matching manifest for linux/amd64 in the manifest list entries```

**Comment by tianon** [comment]
Yeah, the `amd64` builds had a hiccup the first time around.  I've restarted them, and the fixed builds should be up shortly.

**Comment by yosifkit** [comment]
Similar issues: https://github.com/docker-library/hello-world/issues/39, https://github.com/docker-library/official-images/pull/3622#issuecomment-340039696, https://github.com/docker-library/wordpress/issues/239, https://github.com/docker-library/ruby/issues/159, https://github.com/docker-library/rabbitmq/issues/188, https://github.com/docker-library/ghost/issues/106, https://github.com/docker-library/redis/issues/115.

**Comment by cjkupers** [comment]
Haha... I was rolling out AWX in a lab and much googling lead me to this very issue report.

can't pull rabbitmq container on ubuntu 16.04
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by yosifkit** [comment]
It is fixed now for both `rabbitmq:3` and `rabbitmq:3-management`.
```console
$ manifest-tool inspect rabbitmq:3-management
Name:   rabbitmq:3-management (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:dbccb9bca4121313a90c893642a6e8fc25873dbf68ec9d56751a23035eb648ab
 * Contains 3 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:24a08b8eae15d86155112a65382d020c1d42d4b24a5011a44a12a8508559e288
1  Mfst Length: 3033
1     Platform:
1           -      OS: linux
1           - OS Vers: 
1           - OS Feat: []
1           -    Arch: amd64
1           - Variant: 
1           - Feature: 
...
```

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:
