### ISSUE TITLE
3.7-management no longer includes rabbitmqadmin

### ISSUE THREAD

**Issue by johanneswuerbach** [docker-library/rabbitmq#219]
While the 3.6-management images included rabbitmqadmin, the 3.7-management images don't seem to include it any longer.

Potentially the script to extract the admin cli needs to also be ported to 3.7.

3.6:
https://github.com/docker-library/rabbitmq/blob/301c52ad6d75075aa8b42b0977e4f54866c0af96/3.6/alpine/management/Dockerfile#L7

3.7:
https://github.com/docker-library/rabbitmq/blob/301c52ad6d75075aa8b42b0977e4f54866c0af96/3.7/alpine/management/Dockerfile

**Comment by tianon** [comment]
Doh, thanks for the heads up -- I'll go do a re-meld of 3.6 to 3.7 since we might have lost other things in the conversion (since the 3.7 PR was open for a while, and obviously missed a few things :sweat_smile:).

**Comment by johanneswuerbach** [comment]
Thanks @tianon 🙇
