### ISSUE TITLE
Failed to start with memory limit and high watermark set

### ISSUE THREAD

**Issue by mirasrael** [docker-library/rabbitmq#220]
Fails with this error:
```
/usr/local/bin/docker-entrypoint.sh: line 285: :#: command not found
```
I checked this file and it contains (note colon at line start):
```
:# TODO: ...
```
It looks like miss type from vim :)

https://github.com/docker-library/rabbitmq/blob/301c52ad6d75075aa8b42b0977e4f54866c0af96/3.7/docker-entrypoint.sh#L285

**Comment by Tomateauketchup** [comment]
Yes i have exactly the same problem :-p

**Comment by tianon** [comment]
Duplicate of #215
