### ISSUE TITLE
Please consider supporting ServiceFabric

### ISSUE THREAD

**Issue by grahamehorner** [docker-library/rabbitmq#228]
Please consider supporting the running of RabbitMQ docker images with in/under a Microsoft Azure Service Fabric Cluster allowing ServiceFabric to orchestrate/scale RabbitMQ

**Comment by tianon** [comment]
Can you be more specific about what aspects of the image need to change, or what features would need to be added, in order for this to be "supported" ?

Generally, the official images tend to stay fairly vanilla, explicitly attempting to stay inline with upstream's official deployment recommendations.
