### ISSUE TITLE
Cannot pull rabbitmq:3.7.1-management-alpine

### ISSUE THREAD

**Issue by decaz** [docker-library/rabbitmq#230]
```
$ docker pull rabbitmq:3.7.1-management-alpine
Error response from daemon: manifest for rabbitmq:3.7.1-management-alpine not found
```

**Comment by tianon** [comment]
It's currently building: https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/rabbitmq/4/console

See also docker-library/rabbitmq#188, docker-library/ruby#159, c0b/docker-erlang-otp#75, docker-library/official-images#3472, https://github.com/docker-library/wordpress/issues/239, https://github.com/piwik/docker-piwik/issues/70, https://github.com/nodejs/docker-node/issues/571, https://github.com/docker-library/official-images/issues/3653, https://github.com/docker-library/official-images/pull/3622#issuecomment-339838650, https://github.com/docker-library/redis/issues/115, https://github.com/docker-library/rabbitmq/issues/217, https://github.com/docker-library/python/issues/252.

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:

**Comment by decaz** [comment]
@tianon the same issue with rabbitmq:3.7.**2**-management-alpine =/

**Comment by tianon** [comment]
See https://github.com/docker-library/rabbitmq#readme, especially:

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/rabbitmq" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/rabbitmq), especially [PRs with the "library/rabbitmq" label on that repo](https://github.com/docker-library/official-images/labels/library%2Frabbitmq). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

The version bump to 3.7.2 in _this_ repo only happened 3 hours ago (https://github.com/docker-library/rabbitmq/commit/31a69457c8adbe0d7fe7e33afeaa95e4faf2b73e), while all the image maintainers were asleep.  Additionally, it's now the weekend, and not just that, but in the US at least, a holiday weekend.

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/3841
