### ISSUE TITLE
Enable management plugin by default

### ISSUE THREAD

**Issue by jleskovar** [docker-library/rabbitmq#24]
Is there a reason why management isn't enabled by default? I'd submit a PR, but should be fairly simple to implement (see [dockerfile](https://dockerfile.github.io/#/rabbitmq)'s version).

**Comment by michaelklishin** [comment]
It's a reasonable thing to do as long as the image only ever runs one node.

**Comment by yosifkit** [comment]
There is a separate tag for that: [`rabbitmq:management`](https://github.com/docker-library/rabbitmq/blob/5bdfc8547e813bbe2e0ef725738252792780d744/management/Dockerfile).
