### ISSUE TITLE
3.7.4 tags not published

### ISSUE THREAD

**Issue by jharting** [docker-library/rabbitmq#240]
Looks like 3.7.4 release was merged last week https://github.com/docker-library/rabbitmq/commit/1a37166704d2ca7c386980387e81615985d5db47 but I cannot see 3.7.4 tags at https://hub.docker.com/r/library/rabbitmq/tags/ (only RCs)

**Comment by flyudvik** [comment]
Same for latest and 3 and 3.7 tags. Some of the production servers are not able to update with deployment configuration.

**Comment by flyudvik** [comment]
It turns out that Travis job building Docker image is failing on Gosu installation step.

**Comment by ottumm** [comment]
Would this cause the following error?

```
$ docker pull rabbitmq:3
3: Pulling from library/rabbitmq
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by flyudvik** [comment]
@ottumm yes, it ~~would~~ does

**Comment by tianon** [comment]
This was actually waiting for https://github.com/docker-library/official-images/pull/4113 to be merged, so the builds are currently in-queue (https://doi-janky.infosiftr.net/job/multiarch/view/images/view/rabbitmq/).

See also https://github.com/docker-library/rabbitmq/issues/241 and https://github.com/docker-library/official-images/issues/3835.
