### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by ThePixelDeveloper** [docker-library/rabbitmq#241]
When pulling down on macOS.

```
Pulling rabbitmq (rabbitmq:management-alpine)...
management-alpine: Pulling from library/rabbitmq
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by eacmen** [comment]
I went to file this issue as well. Seems like the docker image that was pushed about half an hour ago does not include amd64 support.  Confirmed this is also broken when trying to pull on amd64 Linux machine.

**Comment by rbrent** [comment]
Same

**Comment by fortman** [comment]
I opened https://github.com/docker-library/rabbitmq/issues/241  I'll go ahead and clone mine since it was opened a few minutes after this one

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/3835 (builds are in-queue, should be available sometime today).

**Comment by fortman** [comment]
I know this is closed, but an update for my fellow rabbitmq users, it seems to be working now
:>docker pull rabbitmq
Using default tag: latest
latest: Pulling from library/rabbitmq
8176e34d5d92: Pull complete
....
