### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by fortman** [docker-library/rabbitmq#242]
This seems to be back https://github.com/docker-library/rabbitmq/issues/188

:>docker pull rabbitmq
Using default tag: latest
latest: Pulling from library/rabbitmq
no matching manifest for linux/amd64 in the manifest list entries

**Comment by flyudvik** [comment]
see #240 and #241

**Comment by fortman** [comment]
Dup ticket
