### ISSUE TITLE
RabbitMQ Management's Queues, Exchanges are empty

### ISSUE THREAD

**Issue by a1exus** [docker-library/rabbitmq#243]
I'm using `RabbitMQ 3.7.4 Erlang 20.2.4`:

```
# docker pull rabbitmq:latest
latest: Pulling from library/rabbitmq
Digest: sha256:90d77d4a710bb84378f4e929e67caf2d6d9e6f5485011cb1664537241bcdc0dd
Status: Image is up to date for rabbitmq:latest
# 
# docker pull rabbitmq:management
management: Pulling from library/rabbitmq
Digest: sha256:51477e783858941c8035f62c288c14fc282c3d7c543163edf08d87c53c71c8bf
Status: Image is up to date for rabbitmq:management
# 
```

while connecting to RabbitMQ Management, I do see my node, however if I click on `Queues`, `Exchanges` and etc, it shows empty... 

Rabbitmq works fine, it's just management that I have issue with...

Any help is appreciate it...

**Comment by tianon** [comment]
I can't seem to reproduce; I've run the `rabbitmq:management` image, logged into the web UI, created a queue, and it persisted just fine (even after logging out and back in).

I see you're pulling both `rabbitmq:latest` _and_ `rabbitmq:management` -- are you running two containers?  The `rabbitmq:management` is the standard RabbitMQ install with the management plugin enabled -- it does not connect to an existing RabbitMQ instance, but rather manages the local one (so you should simply run `rabbitmq:management` and use it for both your RabbitMQ needs and for accessing the management web UI).
