### ISSUE TITLE
Getting No Route To Host Exception during connection recovery

### ISSUE THREAD

**Issue by Akhilesh-Soni** [docker-library/rabbitmq#247]
I am facing one issue with rabbitmq, that it terminate the connection with below exception

>  {"log":"Caught an exception during connection recovery!\n","stream":"stderr","time":"2018-03-22T00:00:00.632851865Z"}
{"log":"java.net.NoRouteToHostException: No route to host\n","stream":"stderr","time":"2018-03-22T00:00:00.633374123Z"}
{"log":"\u0009at java.net.PlainSocketImpl.socketConnect(Native Method)\n","stream":"stderr","time":"2018-03-22T00:00:00.633666158Z"}
{"log":"\u0009at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)\n","stream":"stderr","time":"2018-03-22T00:00:00.633935828Z"}
{"log":"\u0009at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n","stream":"stderr","time":"2018-03-22T00:00:00.634170787Z"}
{"log":"\u0009at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n","stream":"stderr","time":"2018-03-22T00:00:00.63440824Z"}
{"log":"\u0009at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n","stream":"stderr","time":"2018-03-22T00:00:00.634625637Z"}
{"log":"\u0009at java.net.Socket.connect(Socket.java:589)\n","stream":"stderr","time":"2018-03-22T00:00:00.635038038Z"}
{"log":"\u0009at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:32)\n","stream":"stderr","time":"2018-03-22T00:00:00.635172903Z"}
{"log":"\u0009at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:34)\n","stream":"stderr","time":"2018-03-22T00:00:00.635369445Z"}
{"log":"\u0009at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConnection(AutorecoveringConnection.java:435)\n","stream":"stderr","time":"2018-03-22T00:00:00.635639932Z"}
{"log":"\u0009at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:407)\n","stream":"stderr","time":"2018-03-22T00:00:00.63584649Z"}
{"log":"\u0009at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)\n","stream":"stderr","time":"2018-03-22T00:00:00.636051142Z"}
{"log":"\u0009at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.shutdownCompleted(AutorecoveringConnection.java:352)\n","stream":"stderr","time":"2018-03-22T00:00:00.636233667Z"}
{"log":"\u0009at com.rabbitmq.client.impl.ShutdownNotifierComponent.notifyListeners(ShutdownNotifierComponent.java:75)\n","stream":"stderr","time":"2018-03-22T00:00:00.636899252Z"}
{"log":"\u0009at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:576)\n","stream":"stderr","time":"2018-03-22T00:00:00.637183801Z"}

The Configuration is as follows:-

1. Rabbitmq docker on aws ec2-instance1 on t2_small server.

2. Services which are facing this issue are running on aws ec2-instance2 on t2-small server.

3. Set following configuration for rabbitmq

what I found suspicious is that the services which are running on ec2-instance1 are able to recover the connection, but the service which are running on ec2-instace2 are not able to connect and throwing above exception.

Please let me know how can I resolve it.

Thanks.

**Comment by wglambert** [comment]
Noting the issue made over at stackoverflow, specifically the comments: https://stackoverflow.com/questions/49570360/getting-rabbitmq-heartbeat-exception#comment86991187_49572239

It seems to be either environmental or a behavior/issue with rabbitmq itself; lacking anything denoting an error in the image or something we could change in the way it's built, I'm going to close the issue.
