### ISSUE TITLE
Port is not changed in config.

### ISSUE THREAD

**Issue by Andrey-mp** [docker-library/rabbitmq#251]
To redefine port the 'RABBITMQ_NODE_PORT' can be set.
Cluster is created successfully with additional options:
RABBITMQ_NODE_PORT=5673
RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit cluster_nodes {['contrail@nodem14','contrail@nodem7','contrail@nodem6'],disc}

but /etc/rabbitmq/rabbitmq.config has default port 5672

I've checked this in 3.6.10 and in 3.7.4

**Comment by yosifkit** [comment]
The default in the config file comes from the entrypoint:

https://github.com/docker-library/rabbitmq/blob/9a847d7134a5b9a75b7cb7d391c6d5273acfcc0d/3.7/debian/docker-entrypoint.sh#L334-L339

Is there a reason that you need to change the port?  Each container runs in their own network namespace, so there won't be port conflicts there and you can map each rabbitmq container to a different port on the host/cluster.

It does look like the environment variable does override the value in the config:

```console
$ docker run -it --rm -e RABBITMQ_NODE_PORT=6666 rabbitmq
...
2018-04-20 20:35:12.260 [info] <0.447.0> started TCP Listener on [::]:6666
2018-04-20 20:35:12.300 [info] <0.183.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@5c5422fbecbe
2018-04-20 20:35:12.354 [info] <0.183.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@5c5422fbecbe
2018-04-20 20:35:12.355 [info] <0.33.0> Application rabbit started on node rabbit@5c5422fbecbe
2018-04-20 20:35:12.570 [info] <0.5.0> Server startup complete; 0 plugins started.
 completed with 0 plugins.
```

(side note to future readers, the `RABBITMQ_NODE_PORT` comes from variables supported by rabbitmq server directly: https://www.rabbitmq.com/configure.html#define-environment-variables; it is not something that is specific to the Docker image)

**Comment by Andrey-mp** [comment]
right now we run rabbitmq container in host network where one more rabbitmq container can be (or not) run on default port. then we change default port by RABBITMQ_NODE_PORT variable.
It works well, listens on non-default port, can be cluster-ized. 
And only rabbitmq.config with default port confuses me...

Is it possible to write RABBITMQ_NODE_PORT into config file?

**Comment by heitorPB** [comment]
Same problem here. Trying to setup rabbitmq in a machine that already have an AMPQ service. The idea is to migrate to RabbitMQ.

The workaround was to copy the content of `/etc/rabbitmq/` to a local folder and mount it as Docker volume.
