### ISSUE TITLE
Unable to access management console from host

### ISSUE THREAD

**Issue by kalkrishnan** [docker-library/rabbitmq#256]
This is not working for me. I ran the below command on docker for windows to run the container:

docker run -d -p 5672:5672 -p 15672:15672 --hostname rabbit-server1 --name rabbit1 rabbitmq:3-management

docker logs rabbit1 show me that the server has started with the management plugin.

I even exposed the port in virtualbox:

image
![image](https://user-images.githubusercontent.com/6913583/39775422-aae79f0c-52b2-11e8-8004-cfa4107096da.png)

But when I try to access localhost:15672 or 172.17.0.2:15672(The Ip of the container), the url just times out and nothing happens.

**Comment by kalkrishnan** [comment]
solved this by doing the port mapping to the docker machine ip and not the container ip

**Comment by tianon** [comment]
Nice, glad you got it figured out! :+1:
