### ISSUE TITLE
Image not working on LCOW

### ISSUE THREAD

**Issue by Kralizek** [docker-library/rabbitmq#257]
Hi,

I've been trying to use `rabbitmq:management` on Docker for Windows 18.03.1-ce using the new `--platform linux` flag on the Windows containers.

`docker run -P --platform linux rabbitmq:management`

[Here you can see all the information I could gather about my configuration](https://gist.github.com/Kralizek/b11ccc354868eac8acd5e20822e4d013) (including logs and error message on console)

I've tried to mount a volume pointing to `/var/lib/rabbitmq/mnesia` as suggested in #171 but the default volume is still mounted.

`docker create --name rabbitmq -P --platform linux -v /var/lib/rabbitmq/mnesia rabbitmq:management`

![u297v71m](https://user-images.githubusercontent.com/2458439/39803405-3c6985c6-5371-11e8-86b9-527386a5b284.jpg)

Let me know if you need more information.

**Comment by yosifkit** [comment]
Sounds like https://github.com/moby/moby/issues/35665.  Rabbitmq requires very specific permissions on the cookie file and it is in the default `VOLUME` from the Dockerfile: `/var/lib/rabbitmq`.

Cross referencing LCOW super issue https://github.com/moby/moby/issues/33850.

**Comment by cassidmj** [comment]
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers#known-app-issues

This is a known issue for a few apps that require volume mapping.

**Comment by Kralizek** [comment]
@cassidmj oops I didn't see this article.

Are there plans to eventually support those applications as well?

**Comment by tianon** [comment]
I think Microsoft plans to eventually, but only they can speak to that unfortunately.  The issue on the Moby repo linked above is the place to follow along for all that work (we're not directly involved in that).

Closing since this is a known LCOW issue (not something we can fix in the image).
