### ISSUE TITLE
ERROR: no matching manifest for linux/arm in the manifest list entries

### ISSUE THREAD

**Issue by matiasdecarli** [docker-library/rabbitmq#258]
I'm getting this after today's release when trying to run on `arm`

```
Pulling rabbit (rabbitmq:3-management)...
3-management: Pulling from library/rabbitmq
ERROR: no matching manifest for linux/arm in the manifest list entries
``` 

`latest` is crashing, but version `3.6-management` is working OK

Any reason for excluding ARM on the manifest or is just a bug?

Let me know if I can help. Thanks in advance

**Comment by yosifkit** [comment]
"no matching manifest" is https://github.com/docker-library/official-images/issues/3835.

As for "crashing", Is that rabbitmq crashing?  You would have to be a bit more detailed on how you are running it and where.
