### ISSUE TITLE
Suppress INFO logs

### ISSUE THREAD

**Issue by soichih** [docker-library/rabbitmq#26]
This container is filling up my disk with verbose (INFO) logs on stdout.

Like..

```
=INFO REPORT==== 6-Jun-2015::02:56:07 ===
closing AMQP connection <0.17897.53> (172.17.42.1:43623 -> 172.17.0.62:5672)
```

Is there a way to suppress this? I think it should be suppressed by default also.

**Comment by michaelklishin** [comment]
See [log levels](http://www.rabbitmq.com/configure.html). I'd discourage image maintainers from disabling info logs by default. They are very helpful when diagnosing various connectivity issues.

**Comment by soichih** [comment]
Yes, info log can be helpful, but rabbitmq already displays ERROR when connection fails, so even without INFO log (which is really mostly noise in my opinion..) user can do basic troubleshooting of connectivity issues. INFO log unnecessarily consumes disk space under normal operations - even with no issues. So I still think INFO log should be disabled by default.

Anyway, I've updated my rabbitmq.config with following.

```
[
    {rabbit, [
        {loopback_users, []
        },

        %% Log levels (currently just used for connection logging).
        %% One of 'debug', 'info', 'warning', 'error' or 'none', in decreasing
        %% order of verbosity. Defaults to 'info'.
        {log_levels, [{connection, warning}, {channel, warning}]}
    ]}
].
```

Now I am only seeing warning and above.

**Comment by tianon** [comment]
We try to stay as close to whatever upstream's defaults are -- the thought behind that is that if upstream thinks people should have `INFO` by default, then who are we to disagree? :smile:

**Comment by soichih** [comment]
OK. I understand. Thank you for your responses.

This is more of an issue because the docker doesn't support automatic log rotation of container stdout, but fortunately, they seem to be working on this for upcoming releases. Once that's in place.. it shouldn't be an issue.
