### ISSUE TITLE
Please add easy instruction how to add initial users to container

### ISSUE THREAD

**Issue by metamaker** [docker-library/rabbitmq#263]
It is extremely hard as of now to add initial user for container. I had to stick with https://stackoverflow.com/a/42251266/2678487, but this is very big chunk of work that costed me 3 hours of time to run properly (worst thing was to generate hash - https://stackoverflow.com/questions/41306350/how-to-generate-password-hash-for-rabbitmq-management-http-api, people, you really need to ship utility that can generate hash for user, how long can it last?).

I couldn't make anything useful with standard RabbitMQ docker container, but `management` version of container worked out fine in the end.

**Comment by wglambert** [comment]
Why are the environment variables insufficient for this https://github.com/docker-library/docs/tree/master/rabbitmq

The default initial user with admin privileges is guest, which can be changed through the environment variable. The images are built in such a way that they are kept as close to upstream as possible such that others can modify them to their liking, so adding in a custom utility would go against this.

Adding additional users is documented in https://www.rabbitmq.com/rabbitmqctl.8.html#User_Management

For example:
```console
rabbitmqctl add_user test test
rabbitmqctl set_user_tags test administrator
```

**Comment by metamaker** [comment]
I didn't see this documentation entry, thanks for reference!

However, passing credentials on command line is insecure. See e.g. MySQL warning about passing password on CLI, same practice applies to any Unix-like system:

https://dev.mysql.com/doc/mysql-security-excerpt/5.7/en/password-security-user.html

Probably, I could pass env variables through docker-compose.yml or script, so this is possibility.

guest user can't be used to access container remotely, so this user must be replaced in any case. Specifying admin user via env is good, but by using `definitions.json` and `rabbitmq.config` I can configure everything (install additional users and set their permissions, define queues and exchanges, etc.) in a more flexible and transparent way than calling plain console commands. There is no mention of this way to configure RabbitMQ in Docker image docs, which I would suggest to add.

**Comment by tianon** [comment]
It's not currently documented, but you can append `_FILE` to any of those environment variable names to reference a file that the value should be pulled from instead -- this allows for the use of Docker Secrets instead (https://docs.docker.com/engine/swarm/secrets/), which keeps the data encrypted while in flight.

**Comment by michaelklishin** [comment]
[Definitions import](http://www.rabbitmq.com/management.html#load-definitions) is by far the most automation-friendly option there is.

**Comment by wglambert** [comment]
Closing since issue is resolved
