### ISSUE TITLE
Info on using RabbitMQ plugins missing

### ISSUE THREAD

**Issue by luigiberrettini** [docker-library/rabbitmq#264]
I am looking for a way to create a container specifying the list of plugins I want to enable (`rabbitmq-plugins enable --offline`) and I could not find any example on the [Docker store.](https://store.docker.com/images/rabbitmq)

I need to use the following plugins and I would prefer not creating a new image based on yours:
 - rabbitmq_federation
 - rabbitmq_federation_management
 - rabbitmq_management_visualiser
 - rabbitmq_mqtt
 - rabbitmq_stomp

**Comment by luigiberrettini** [comment]
As per comment [145#291476039](https://github.com/docker-library/rabbitmq/issues/145#issuecomment-291476039) plugins can be enabled editing the `enabled_plugins` file

This could be done in the entrypoint passing the list of plugins as a parameter: this is aligned with the goal of containers as reusable components.

**Comment by lincoln310** [comment]
what is the port of enabled stomp?

**Comment by wglambert** [comment]
https://www.rabbitmq.com/stomp.html

Looks like 12345 is default? We don't change anything for it.
