### ISSUE TITLE
RABBITMQ_DEFAULT_VHOST_FILE doesn't work

### ISSUE THREAD

**Issue by SushilShrestha** [docker-library/rabbitmq#267]
I am using the docker secret for storing `RABBITMQ_DEFAULT_USER`, `RABBITMQ_DEFAULT_PASS`, and `RABBITMQ_DEFAULT_VHOST` and trying to pass those secrets throught the `RABBITMQ_DEFAULT_USER_FILE`, `RABBITMQ_DEFAULT_PASS_FILE`, and `RABBITMQ_DEFAULT_VHOST_FILE` env variables. 

`RABBITMQ_DEFAULT_USER_FILE` and `RABBITMQ_DEFAULT_PASS_FILE` seems to works but `RABBITMQ_DEFAULT_VHOST_FILE` is not working.

**Comment by wglambert** [comment]
There isn't a variable for `RABBITMQ_DEFAULT_VHOST_FILE` only `RABBITMQ_DEFAULT_VHOST`

https://github.com/docker-library/rabbitmq/blob/master/3.7/docker-entrypoint.sh#L62-L67

**Comment by tianon** [comment]
There are some options which have `_FILE` variants, but `DEFAULT_USER` and `DEFAULT_PASS` are the only ones (https://github.com/docker-library/rabbitmq/blob/92c53e854fb21899d0bc91d75ad5779bfaf45312/3.7/docker-entrypoint.sh#L44-L48).
