### ISSUE TITLE
Set user permission problem

### ISSUE THREAD

**Issue by majidgolshadi** [docker-library/rabbitmq#27]
Hi
I try to use your rabbitmq image and start it with
```shell
docker run -d -e RABBITMQ_NODENAME=my-rabbit --name rabbitmq-station --hostname rabbitmq-station -p 15672:15672 -p 5672:5672 rabbitmq:3.5.1-management
```
I can see management page at port 15672. When i try to set permission for an user i got `Not Found` message!!
In browser Network log i got `404 Object Not Found` to response of set user permission.
What's wrong in running rabbitmq container?

**Comment by yosifkit** [comment]
Using that exact run I am unable to reproduce.

**Comment by majidgolshadi** [comment]
The problem was that the web client was't compatible with latest API, so I fixed my problem by directly calling commands in the terminal.
