### ISSUE TITLE
gpg --keyserver error

### ISSUE THREAD

**Issue by Jongchana-P** [docker-library/rabbitmq#272]
OS : MacOS 10.13.3
Docker : 18.06.0-ce

I used master branch to create docker container when I executed "build" command I got an error when run "gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \" But I found the solution to replace by 

> for server in $(shuf -e ha.pool.sks-keyservers.net \
>                             hkp://p80.pool.sks-keyservers.net:80 \
>                             keyserver.ubuntu.com \
>                             hkp://keyserver.ubuntu.com:80 \
>                             pgp.mit.edu) ; do \
>         gpg --keyserver "$server" --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && break || : ; \
>     done && \
>     gpg --batch --verify /tmp/gosu.asc /usr/bin/gosu && \

And "build" command is a success.

Is it a correct solution?

**Comment by wglambert** [comment]
We get GPG related issues quite frequently, see https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035

What we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749

**Comment by Jongchana-P** [comment]
Thank you @wglambert for your information.
