### ISSUE TITLE
Document how to set management plugin path_prefix

### ISSUE THREAD

**Issue by thenewguy** [docker-library/rabbitmq#275]
Please document how to set path_prefix for the management plugin with this image

**Comment by tianon** [comment]
It's not one of the limited set of configuration options we support directly setting from an environment variable, so the supported method of setting this configuration option is to mount or build+copy a configuration file into the image with your desired configuration set.  You could also use `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS`, but the syntax for using that is fairly arcane, so I'd really recommend simply using a file instead (and we should probably update the "Additional Configuration" section of the documentation to say so).
