### ISSUE TITLE
Overriding `channel_max` is not working

### ISSUE THREAD

**Issue by rajiff** [docker-library/rabbitmq#278]
It is not very clear from the Dockerfile documentation on the docker hub, how can we override certain core server settings, such as `channel_max`

Tried overriding with a custom supplied rabbitmq.conf but it does not allow that
Tried setting env variable RABBITMQ_CHANNEL_MAX but that too not working

please check if this is a issue with the documentation or really there is nothing to override this

**Comment by wglambert** [comment]
You'd want to use `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` for any environment variables that the `entrypoint.sh` doesn't explicitly interpret
https://github.com/docker-library/docs/tree/master/rabbitmq#additional-configuration


Passing `-e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbit channel_max [{4007}]"` to docker will update the rabbitmq environment variables in the container
```console
$ docker run -dit --rm --name rabbitmq rabbitmq
1e79d1fe8765d3878a779fd457ea3c59bc42d336b83cb3521ae1566c5b093627
$ docker exec -it rabbitmq bash
root@1e79d1fe8765:/# rabbitmqctl environment | grep channel
           {rabbit_log_channel_lager_event,
      {channel_max,2047},
      {channel_operation_timeout,15000},
          [rabbit_reader,rabbit_channel,gen_server2,rabbit_exchange,
          [rabbit_log_lager_event,rabbit_log_channel_lager_event,
root@1e79d1fe8765:/# exit
exit
$ docker run -dit --rm --name rabbitmq1 -d -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbit channel_max [{4007}]" rabbitmq5a1bcbe1d9d4ca433e93e36d720a90a7e7a86aa9ee212ff49b082907a320d055
$ docker exec -it rabbitmq1 bash
root@5a1bcbe1d9d4:/# rabbitmqctl environment | grep channel
           {rabbit_log_channel_lager_event,                                                                                                                   
      {channel_max,[{4007}]},                                                                                                                                 
      {channel_operation_timeout,15000},                                                                                                                      
          [rabbit_reader,rabbit_channel,gen_server2,rabbit_exchange,                                                                                          
          [rabbit_log_lager_event,rabbit_log_channel_lager_event,                                                                                             
root@5a1bcbe1d9d4:/#

**Comment by tianon** [comment]
You should also be able to accomplish this with a configuration file (which is especially simple with the newer sysctl-style configuration file):

```console
$ cat rabbitmq.conf
channel_max = 4007

$ docker pull rabbitmq:3.7
3.7: Pulling from library/rabbitmq
Digest: sha256:a8094b952b9fe778f4e70efaca98494e167088ef3272944a28b89caf6e098790
Status: Image is up to date for rabbitmq:3.7

$ docker run -dit --name test -v "$PWD/rabbitmq.conf":/etc/rabbitmq/rabbitmq.conf rabbitmq:3.7
a11bcf69bc47106f7e0100ca418cf2ab60a526e31600e3f73b76af97c4417195

$ docker logs --tail 2 test
2018-09-19 20:37:30.568 [info] <0.5.0> Server startup complete; 0 plugins started.
 completed with 0 plugins.

$ docker exec -it test bash
root@a11bcf69bc47:/# rabbitmqctl environment | grep channel
           {rabbit_log_channel_lager_event,
      {channel_max,4007},
      {channel_operation_timeout,15000},
          [rabbit_reader,rabbit_channel,gen_server2,rabbit_exchange,
          [rabbit_log_lager_event,rabbit_log_channel_lager_event,
```

**Comment by rajiff** [comment]
> You'd want to use `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` for any environment variables that the `entrypoint.sh` doesn't explicitly interpret
> https://github.com/docker-library/docs/tree/master/rabbitmq#additional-configuration
> 
> Passing `-e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbit channel_max 4007"` to docker will update the rabbitmq environment variables in the container
> 
> ```
> $ docker run -dit --rm --name rabbitmq rabbitmq
> 1e79d1fe8765d3878a779fd457ea3c59bc42d336b83cb3521ae1566c5b093627
> $ docker exec -it rabbitmq bash
> root@1e79d1fe8765:/# rabbitmqctl environment | grep channel
>            {rabbit_log_channel_lager_event,
>       {channel_max,2047},
>       {channel_operation_timeout,15000},
>           [rabbit_reader,rabbit_channel,gen_server2,rabbit_exchange,
>           [rabbit_log_lager_event,rabbit_log_channel_lager_event,
> root@1e79d1fe8765:/# exit
> exit
> $ docker run -dit --rm --name rabbitmq1 -d -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbit channel_max 4007" rabbitmq
> 5a1bcbe1d9d4ca433e93e36d720a90a7e7a86aa9ee212ff49b082907a320d055
> $ docker exec -it rabbitmq1 bash
> root@5a1bcbe1d9d4:/# rabbitmqctl environment | grep channel
>            {rabbit_log_channel_lager_event,
>       {channel_max,4007},
>       {channel_operation_timeout,15000},
>           [rabbit_reader,rabbit_channel,gen_server2,rabbit_exchange,
>           [rabbit_log_lager_event,rabbit_log_channel_lager_event,                                                                                            
> root@5a1bcbe1d9d4:/#
> ```

I will try this today and will post back if this worked

**Comment by rajiff** [comment]
> You should also be able to accomplish this with a configuration file (which is especially simple with the newer sysctl-style configuration file):
> 
> ```
> $ cat rabbitmq.conf
> channel_max = 4007
> 
> $ docker pull rabbitmq:3.7
> 3.7: Pulling from library/rabbitmq
> Digest: sha256:a8094b952b9fe778f4e70efaca98494e167088ef3272944a28b89caf6e098790
> Status: Image is up to date for rabbitmq:3.7
> 
> $ docker run -dit --name test -v "$PWD/rabbitmq.conf":/etc/rabbitmq/rabbitmq.conf rabbitmq:3.7
> a11bcf69bc47106f7e0100ca418cf2ab60a526e31600e3f73b76af97c4417195
> 
> $ docker logs --tail 2 test
> 2018-09-19 20:37:30.568 [info] <0.5.0> Server startup complete; 0 plugins started.
>  completed with 0 plugins.
> 
> $ docker exec -it test bash
> root@a11bcf69bc47:/# rabbitmqctl environment | grep channel
>            {rabbit_log_channel_lager_event,
>       {channel_max,4007},
>       {channel_operation_timeout,15000},
>           [rabbit_reader,rabbit_channel,gen_server2,rabbit_exchange,
>           [rabbit_log_lager_event,rabbit_log_channel_lager_event,
> ```

Thanks for responding 

We tried this, issue was RabbitMQ not booted at all with error `Device not ready, reading /etc/.../rabbitmq.conf`

**Comment by tianon** [comment]
Sounds like an issue with your filesystem and/or mount.  Instead of doing a bind-mount (`-v ...:/etc/rabbitmq/rabbitmq.conf`), I'd recommend you bake the `.conf` file directly into a new image to overcome whatever odd issue you're seeing:

```dockerfile
FROM rabbitmq:3.7
COPY rabbitmq.conf /etc/rabbitmq/
```

**Comment by tianon** [comment]
(Closing, since this appears to be resolved.  Just as a note, I've filed https://github.com/docker-library/docs/pull/1314 to adjust our recommendation to recommend folks use the file before they try the crazy environment variable whose syntax is really difficult to get right.)
