### ISSUE TITLE
Have a more flexible initialisiation

### ISSUE THREAD

**Issue by anentropic** [docker-library/rabbitmq#29]
I wanted to have several users, vhosts and permissions set up on my dockerised RabbitMQ...  the fix which closed #12  doesn't really solve it as you only get the one 'default' user and vhost available to be set via RabbitMQ config (why config file is so limited I don't understand...)

I struggled with this for a while due to various problems - for a well designed container you basically want to have `exec rabbitmq-server` as the final action in your entrypoint script... however adding vhosts has to be done via `rabbitmqctl` cli, which needs a server running. Sort of Catch 22.

I tried to start server, add vhosts and stop server again as a `RUN` action in the Dockerfile (as per this answer on SO http://stackoverflow.com/a/26553393/202168) but that didn't seem to work. (If you start the server again in a subsequent `RUN` command and `list_vhosts` they're not there any more)

Eventually solved with help of this blog post: http://mpas.github.io/post/2015/06/docker-rabbitmq-default-users/  ...though I had to modify by prefixing all the `rabbitmqctl` commands and the final `rabbitmq-server` command with `gosu rabbitmq`

Since it was quite hard to find a working solution, for I guess a common problem, I'm suggesting the recipe above (if best approach) should either be documented or better: perhaps a clean hook for injecting `rabbitmqctl` actions as part of the setup/startup should be provided in this image?

If I've misunderstood or am solving the wrong problem in the wrong way please put me right

**Comment by tianon** [comment]
Ahh, thanks for the report.  This actually boils down to problems with
managing that pesky ".erlang.cookie" file -- I'll be making a pull request
in a minute that should make this simpler for both "docker exec" and for
linking (or even direct remote usage, if you're crazy enough to have
rabbitmq directly listen to the public internet or private network).

**Comment by anentropic** [comment]
I think #30 fixes a slightly different problem from mine I think...

I want to execute a series of `rabbitmqctl` commands, effectively as part of the _image_ ...so that when you start the _container_ the vhosts already exist.

So far I didn't find a way to do that, but I did find a way to execute them when starting the container, which is good enough for me.
