### ISSUE TITLE
Reoping #150 - RABBITMQ_DEFAULT_USER/PASS environment variables not taken into account

### ISSUE THREAD

**Issue by TheFonz2017** [docker-library/rabbitmq#290]
Please have a look at #150. 
This has been closed, but there are comments afterwards that explain why this is still not properly solved.

Thanks!

**Comment by wglambert** [comment]
From your comment "The /etc/rabbitmq/rabbit.conf is not created"; is there anything in the logs like an error related to the config file by the entrypoint script: https://github.com/docker-library/rabbitmq/blob/3740043813fc8a0f0b58451c94e181f441b37dc5/3.7/debian/docker-entrypoint.sh#L208

Can you get a concise reproducer, as by default there doesn't seem to be an issue with the environment variables or generating the config file https://github.com/docker-library/rabbitmq/issues/150#issuecomment-297179099

**Comment by tianon** [comment]
Closing given https://github.com/docker-library/rabbitmq/issues/150#issuecomment-442221687 -- this is exactly the expected behavior.
