### ISSUE TITLE
Docker entrypoint doesn't allow RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.0

### ISSUE THREAD

**Issue by bfink13** [docker-library/rabbitmq#294]
I noticed that https://github.com/docker-library/rabbitmq/blob/master/3.7/docker-entrypoint.sh#L324 restricts RABBITMQ_VM_MEMORY_HIGH_WATERMARK to `0.0 < RABBITMQ_VM_MEMORY_HIGH_WATERMARK <= 1.0`. I am not sure of any reason to disallow 0.0 and I verified that Rabbit accepts a value of 0.0 on startup.

Seems like RABBITMQ_VM_MEMORY_HIGH_WATERMARK should be inclusive on both ends - `0.0 <= RABBITMQ_VM_MEMORY_HIGH_WATERMARK <= 1.0`.

Does anyone see a reason to disallow this?

**Comment by tianon** [comment]
Looking at https://www.rabbitmq.com/memory.html, this seems reasonable to me:

> ### Disabling All Publishing
>
> A value of `0` makes the memory alarm go off immediately and thus eventually blocks all publishing connections (this may be useful if you wish to disable publishing globally); use `rabbitmqctl set_vm_memory_high_watermark 0`.

**Comment by tianon** [comment]
Yep, seems fine:

```
2018-12-04 21:33:20.254 [info] <0.192.0> Memory high watermark set to 0 MiB (0 bytes) of 64300 MiB (67424264192 bytes) total
2018-12-04 21:33:20.255 [info] <0.192.0> vm_memory_high_watermark set. Memory used:98217984 allowed:0
2018-12-04 21:33:20.255 [warning] <0.190.0> memory resource limit alarm set on node rabbit@63e2dc61db9f.
```

**Comment by bfink13** [comment]
Cool - I'll get a PR submitted in the next couple days.

**Comment by michaelklishin** [comment]
A value of `0.0000000000001` should be as good even if something prevents you from setting it to 0 ;)

**Comment by gerhard** [comment]
@bfink13 how's it coming along?

**Comment by gerhard** [comment]
@bfink13 how's the PR coming along?

**Comment by bfink13** [comment]
Sorry I've been so slow on this. I'll get it done this week.

**Comment by gerhard** [comment]
No worries, just checking 👍
