### ISSUE TITLE
Define max-length policy

### ISSUE THREAD

**Issue by okolimar** [docker-library/rabbitmq#296]
Currently I don't see a simple way to define custom policies without having to define custom definitions file in custom config file. Is there another way I am missing please?

**Comment by wglambert** [comment]
Setting parameters/policies can be done through the `rabbitmqctl` or the management plugin for which we have a tag for
https://www.rabbitmq.com/parameters.html
https://www.rabbitmq.com/parameters.html#how-policies-work

If a setting needs to be set from the config file then you'll either want to mount a custom config or pass the arguments as environment variables with `-e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` https://github.com/docker-library/docs/tree/master/rabbitmq#additional-configuration

**Comment by okolimar** [comment]
I ended up running a command to set the policy after container startup in CI. Thanks for your response.
