### ISSUE TITLE
Version 3.7.11

### ISSUE THREAD

**Issue by decaz** [docker-library/rabbitmq#308]
There is still version `3.7.11-rc.2` at the Docker Hub but `3.7.11` version has been released already.

**Comment by tianon** [comment]
See https://github.com/docker-library/rabbitmq/commit/4320a3fdbf9f189ee29dc03abf3df82180459f12, https://github.com/docker-library/rabbitmq#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet, and thus https://github.com/docker-library/official-images/pull/5387.
