### ISSUE TITLE
Can't connect using rabbitmqctl

### ISSUE THREAD

**Issue by tdudgeon** [docker-library/rabbitmq#31]
Using this image its not obvious how to connect and manage using rabbitmqctl.
I did this:
1 Ran container using 
`docker run -it --rm -h rabbitmq1 --name rabbitmq1 -p 5672:5672 rabbitmq:3`

2 Connected to container using  
`docker exec -it rabbitmq1 /bin/bash`

3 Tried to use one of the management functions:
`rabbitmqctl list_users`
and got:
```Error: unable to connect to node rabbit@rabbitmq1: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@rabbitmq1]

rabbit@rabbitmq1:
  * connected to epmd (port 4369) on rabbitmq1
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed
  * suggestion: hostname mismatch?
  * suggestion: is the cookie set correctly?
  * suggestion: is the Erlang distribution using TLS?

current node details:
- node name: 'rabbitmq-cli-142@rabbitmq1'
- home dir: /root
- cookie hash: DF2OcnpF+mD/X4V5vhs8Iw==```

4 But in the server log I in fact see:
```=ERROR REPORT==== 2-Jul-2015::16:18:06 ===
** Connection attempt from disallowed node 'rabbitmq-cli-142@rabbitmq1' **```

So it either looks like something is misconfigured, or I'm doing something wrong.
Would be good to clarify this in the docs.

**Comment by yosifkit** [comment]
https://github.com/docker-library/rabbitmq/pull/30 should fix this.

**Comment by tianon** [comment]
Indeed it did! :+1:

**Comment by tdudgeon** [comment]
Still struggling with this. According to the docs this should work

`docker run -d --hostname my-rabbit --name some-rabbit -e RABBITMQ_ERLANG_COOKIE='secret cookie here' rabbitmq:3`

then
`docker run -it --rm --link some-rabbit:my-rabbit -e RABBITMQ_ERLANG_COOKIE='secret cookie here' rabbitmq:3 bash`

and then in that container:
`rabbitmqctl -n rabbit@my-rabbit list_users`

But that fails for me:

Error: unable to connect to node 'rabbit@my-rabbit': nodedown

DIAGNOSTICS

attempted to contact: ['rabbit@my-rabbit']

rabbit@my-rabbit:
  * connected to epmd (port 4369) on my-rabbit
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed
  * suggestion: hostname mismatch?
  * suggestion: is the cookie set correctly?
  * suggestion: is the Erlang distribution using TLS?

current node details:
- node name: 'rabbitmq-cli-169@d853db02abf6'
- home dir: /root
- cookie hash: JzH3+tD8sRBzqWQ7C9Nvmw==

(note that the cookie hash is different form the one the server reports)

**Comment by yosifkit** [comment]
I was just testing to duplicate this and had the same problem... until I did a `docker pull` :smiley:

**Comment by tdudgeon** [comment]
OK, so I had done a `docker pull` but clearly something was cached somewhere.
After some deep cleansing its now working OK.
Thanks!
