### ISSUE TITLE
Memory leak on 3.7.11-management-alpine?

### ISSUE THREAD

**Issue by ManofWax** [docker-library/rabbitmq#312]
Hello, I was running `rabbitmq-3.7.8-management-alpine` yesterday I've updated to `rabbitmq-3.7.11-managment-alpine` and memory usage growth until the watermark as shown in prometheus:
![image](https://user-images.githubusercontent.com/188858/52332531-2f621d00-29fb-11e9-937a-fc09a56db8a8.png)

The drop of memory usage was due to my manual restart.
I've checked number of connections, queues, messages and they are the same across the three versions, I've also left the configuration untouched.
I'm running this configuration in more than 100 servers and in all of them the beheviour is the same.

Did something changed between 3.7.8 and 3.7.10/11 that I need to adjust my configuration for or is it some bug?

**Comment by wglambert** [comment]
You could try asking over at https://github.com/rabbitmq/rabbitmq-server/issues since these repos are for issues with the Docker image and not with the software itself, as we aren't maintainers of RabbitMQ

**Comment by tianon** [comment]
@gerhard @michaelklishin any idea whether there's something about how we start RabbitMQ / build Erlang / install the management plugin that might cause something like this, or is the suggestion to file an appropriate issue further up the chain the best we can offer from this perspective?

**Comment by gerhard** [comment]
I am not aware of any changes in 3.7.11 that could be causing this, but I am intrigued.

The first page to read is https://www.rabbitmq.com/memory-use.html. Sharing a memory breakdown using `rabbitmqctl` is essential in making progress with this.

If you are already using Prometheus, I am assuming that you have Grafana nearby, which would make it easy to set up [BEAM Memory Allocators Dashboard](https://github.com/deadtrickster/beam-dashboards). While this is not necessary, it provides a deeper insight into Erlang VM's memory management and helps narrow-down memory-related issues quicker. This Grafana dashboard requires [prometheus_rabbitmq_exporter](https://github.com/deadtrickster/prometheus_rabbitmq_exporter), as described in https://www.rabbitmq.com/prometheus.html.

Lastly, the [rabbitmq-users mailling list](https://groups.google.com/forum/?hl=en#!forum/rabbitmq-users) is full of insightful memory-related threads.

Hope this helps, Gerhard.

**Comment by michaelklishin** [comment]
@wgerlach team RabbitMQ does not use GitHub issues for questions and any questions asked there will be redirected to the mailing list.

[Memory breakdown](https://www.rabbitmq.com/memory-use.html) and `rabbitmq-top` should be the OP's starting points. We'd ask for both first thing on rabbitmq-users. Don't guess, collect data instead.

**Comment by michaelklishin** [comment]
There weren't any relevant changes in RabbitMQ since 3.7.8: [3.7.9](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.9), [3.7.10](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.10), [3.7.11](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.11), so there's a decent chance the biggest contributor can be the Erlang version upgrade that happened in this image since September.

@gerhard's memory allocator dashboard suggestion is therefore a very good idea.

**Comment by gerhard** [comment]
@ManofWax did you make progress with this?

**Comment by ManofWax** [comment]
Thanks everyone for the help, I haven't got time to investigate further but tt seems disabling ldap plugin solved the issue. As soon as I've time I will test again rabbitmq  `3.7.9` and `3.7.11` with ldap plugin enabled  and I'll report back in case the problem persisted providing date from memory allocator dashboard.

I think this issue can be closed for now
