### ISSUE TITLE
Version 3.7.9 is missing

### ISSUE THREAD

**Issue by mattbennett** [docker-library/rabbitmq#315]
No variety of 3.7.9 is present on https://hub.docker.com/_/rabbitmq

I see https://github.com/docker-library/rabbitmq/issues/295 is closed but it looks like only 3.7.10 onwards was subsequently uploaded.

**Comment by gerhard** [comment]
@mattbennett are you missing something specific from v3.7.9 that one of the newer versions don't have?

**Comment by mattbennett** [comment]
@gerhard I don't particularly need 3.7.9, but I have a downstream image that builds on top of this one. A missing tag here cascades into a missing tag in my repo too. Not a big deal but I thought you might like to know :)

**Comment by gerhard** [comment]
👍 got it, I don't like missing versions either.

[As the build process is fully automated and defaults to latest](https://doi-janky.infosiftr.net/job/update.sh/job/rabbitmq/), we would need to force build a 3.7.9 to back-fill the missing image tags. How do we do this @tianon @yosifkit ?

**Comment by yosifkit** [comment]
> As the build process is fully automated and defaults to latest, we would need to force build a 3.7.9 to back-fill the missing image tags. How do we do this @tianon @yosifkit ?

:thinking: I think we just need a commit here of the `3.7.9` image, and then make a PR from that commit to official-images and after that merges and builds make a revert PR to official-images. Probably also do a revert here, unless the bot beats us.
