### ISSUE TITLE
Introducing images based on opensuse?

### ISSUE THREAD

**Issue by Itxaka** [docker-library/rabbitmq#319]
Hi!

Was wondering if there would be any issues on creating opensuse based images for rabbit.

Im willing to work on this but before starting I wanted to know if they would be accepted to live alongside the ubuntu/alpine as to not make the effort of creating them to be rejected afterwards :)

Thanks!

**Comment by michaelklishin** [comment]
@Itxaka the question with every new image type is primarily "who is going to maintain it going forward". Doing the work once is not too time consuming. Doing it over the course of a few years can be much more of a commitment.

I definitely like how much better things are on OpenSUSE now compared to, say, 12 months ago so I 👍  this but the question remains: who is going to maintain this new image? I have a feeling most maintainers and users are long time Debian users.

**Comment by Itxaka** [comment]
That is indeed true @michaelklishin usually the front work of creating something its the easiest work, maintaining it afterwards is where the pain comes from ;)

This would be part of creating all of the openstack needed images based of opensuse, so it will be consumed by SUSE customers deploying openstack in kubernetes clusters, meaning that it will have an userbase *and* we (SUSE) should be the ones maintaining it.

Knowing that this is possible, let me move this internally to see if there is an internal commitment to this for years to come.

Thanks for the quick response! :+1:

**Comment by tianon** [comment]
I think https://github.com/docker-library/official-images/issues/5371 is also relevant here.

**Comment by michaelklishin** [comment]
@tianon is there a policy that would prevent this image or one of its variants on being based on a community OS image such as `opensuse/tumbleweed`?

**Comment by tianon** [comment]
Right, for it to be part of the https://hub.docker.com/_/rabbitmq image, it has to be `FROM` some other image in the program (https://github.com/docker-library/official-images#repeatability).

**Comment by Itxaka** [comment]
> I think [docker-library/official-images#5371](https://github.com/docker-library/official-images/issues/5371) is also relevant here.

Im not sure how that would affect this, if I send a PR for an opensuse rabbitmq image it will be based of the official one `opensuse/leap:15` for example, so there should be no issue there :)

**Comment by michaelklishin** [comment]
If the plan is for SUSE folks to maintain their own image based on this one how can we possibly object? :)

**Comment by yosifkit** [comment]
> If the plan is for SUSE folks to maintain their own image based on this one how can we possibly object? :)

I have no objection to them having their own image; that is in the spirit of open source. :smiley_cat:

Given docker-library/official-images#5371 and "_No official images can be derived from, or depend on, non-official images_"\*, I would not be comfortable adding an opensuse variant of rabbitmq in the Official-Images.  It would be better to live under the opensuse org, like `https://hub.docker.com/r/opensuse/rabbitmq`.

\* to be clear, "official" in this context means part of [Docker's Official Image program](https://docs.docker.com/docker-hub/official_images/), not to be confused with "Docker images provided by the software creators"

-----

Similar issue on https://github.com/docker-library/python/issues/61#issuecomment-282450114, especially this part with a swap of python for rabbitmq: "_For most users, just having "[rabbitmq]" at a specific version fulfills all their requirements. They don't need to care about the underlying distribution it is running within_."

**Comment by michaelklishin** [comment]
Sounds like we have a consensus and the constraints are well understood and articulated. @Itxaka is there anything that prevents us from considering this resolved and OpenSUSE folks from starting their own image based on this one?

**Comment by Itxaka** [comment]
@michaelklishin yep, that is great and everything understood!

Thank you all for your time and effort, I will close this!
