### ISSUE TITLE
rabbitmq management ui occer errors

### ISSUE THREAD

**Issue by zhousujian** [docker-library/rabbitmq#321]
I use the latest version in docker hub(3.7.12)，and I depeloyed it, enable plugins : rabbitmq_management,rabbitmq_mqtt,rabbitmq_web_mqtt，then check the management ui,find some ui errors.
ReferenceError: paginate_ui is not defined ReferenceError: paginate_ui is not defined at Array.process (eval at compile (http://x.x.x.x:15672/js/ejs-1.0.min.js:1:6654), :3:48) at EJS.render (http://x.x.x.x:15672/js/ejs-1.0.min.js:1:1885) at format (http://x.x.x.x:15672/js/main.js:1065:21) at http://x.x.x.x:15672/js/main.js:439:24 at with_reqs (http://x.x.x.x:15672/js/main.js:1047:9) at http://x.x.x.x:15672/js/main.js:1043:17 at XMLHttpRequest.req.onreadystatechange (http://x.x.x.x:15672/js/main.js:1123:17)

**Comment by michaelklishin** [comment]
Clear your browser's cache.

**Comment by wglambert** [comment]
Where are the errors at specifically, I'm not able to see any when trying to reproduce

```Dockerfile
FROM rabbitmq:3.7.12-management
RUN rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_federation_management
```
```console
$ docker run -dit --rm -p 8000:15672 --name rabbit rabbit:test
83209af5cb80b1ce98c28c325cd147ae1c50a2a2cc3bd67af13a7023c1d76a20

$ docker logs rabbit | tail -n 12
2019-02-26 17:27:47.141 [info] <0.574.0> rabbit_web_mqtt: listening for HTTP connections on undefined:15675
2019-02-26 17:27:47.166 [info] <0.601.0> Management plugin: HTTP (non-TLS) listener started on port 15672
2019-02-26 17:27:47.166 [info] <0.707.0> Statistics database started.
 completed with 7 plugins.
2019-02-26 17:27:47.327 [info] <0.8.0> Server startup complete; 7 plugins started.
 * rabbitmq_federation_management
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_federation
 * rabbitmq_web_mqtt
 * rabbitmq_management_agent
 * rabbitmq_mqtt

$ docker exec -it rabbit bash
root@83209af5cb80:/# rabbitmq-plugins list
Listing plugins with pattern ".*" ...
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on rabbit@83209af5cb80
 |/
[  ] rabbitmq_amqp1_0                  3.7.12
[  ] rabbitmq_auth_backend_cache       3.7.12
[  ] rabbitmq_auth_backend_http        3.7.12
[  ] rabbitmq_auth_backend_ldap        3.7.12
[  ] rabbitmq_auth_mechanism_ssl       3.7.12
[  ] rabbitmq_consistent_hash_exchange 3.7.12
[  ] rabbitmq_event_exchange           3.7.12
[e*] rabbitmq_federation               3.7.12
[E*] rabbitmq_federation_management    3.7.12
[  ] rabbitmq_jms_topic_exchange       3.7.12
[E*] rabbitmq_management               3.7.12
[e*] rabbitmq_management_agent         3.7.12
[E*] rabbitmq_mqtt                     3.7.12
[  ] rabbitmq_peer_discovery_aws       3.7.12
[  ] rabbitmq_peer_discovery_common    3.7.12
[  ] rabbitmq_peer_discovery_consul    3.7.12
[  ] rabbitmq_peer_discovery_etcd      3.7.12
[  ] rabbitmq_peer_discovery_k8s       3.7.12
[  ] rabbitmq_random_exchange          3.7.12
[  ] rabbitmq_recent_history_exchange  3.7.12
[  ] rabbitmq_sharding                 3.7.12
[  ] rabbitmq_shovel                   3.7.12
[  ] rabbitmq_shovel_management        3.7.12
[  ] rabbitmq_stomp                    3.7.12
[  ] rabbitmq_top                      3.7.12
[  ] rabbitmq_tracing                  3.7.12
[  ] rabbitmq_trust_store              3.7.12
[e*] rabbitmq_web_dispatch             3.7.12
[E*] rabbitmq_web_mqtt                 3.7.12
[  ] rabbitmq_web_mqtt_examples        3.7.12
[  ] rabbitmq_web_stomp                3.7.12
[  ] rabbitmq_web_stomp_examples       3.7.12
```

![rabbit_ui](https://user-images.githubusercontent.com/26428991/53433600-89765280-39a9-11e9-8071-31edb1a71ec2.png)

**Comment by michaelklishin** [comment]
@wgerlach this issue is mailing list material. UI app code changes between upgrades can require clearing browser cache. This is [mentioned in the Upgrades guide](https://www.rabbitmq.com/upgrade.html) and has nothing to do with this image.

**Comment by MArK1done** [comment]
Clearing the cache worked for me. Thanks @michaelklishin 

> @wgerlach this issue is mailing list material. UI app code changes between upgrades can require clearing browser cache. This is [mentioned in the Upgrades guide](https://www.rabbitmq.com/upgrade.html) and has nothing to do with this image.

**Comment by KeithTt** [comment]
> [Clear your browser's cache](https://www.rabbitmq.com/upgrade.html).

worked for me, thanx a lot.
