### ISSUE TITLE
healthchecks

### ISSUE THREAD

**Issue by MobyDikkens** [docker-library/rabbitmq#326]
# hi, i have a question about the rabbit healthchecks
## little intro
lets imagine that we want to deploy a service that depends on rabbit using docker-compose, i guess it will look like
```version: "3.3"
services:
  rabbitmq:
    image: rabbitmq
    expose:
      - 5672
      - 15672
  service:
    image: service
    depends_on:
      - rabbitmq
```

but you can face with the problem when the service has been successfully started and trying to connect to the rabbit that has not ready yet, it will cause an error, so that u need to add an additional custom healthchecks like

```version: "3.3"
services:
  rabbitmq:
    image: rabbitmq
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      timeout: 5s
      retries: 1
  service:
    image: service
    depends_on:
      service:
        condition: service_healthy
```

question is, is it possible to move the healthcheck logic into rabbit dockerfile, to avoid scripts like the one above?

**Comment by wglambert** [comment]
Explicit health checks are not added to official images for a number of reasons https://github.com/docker-library/faq#healthcheck

**Comment by MobyDikkens** [comment]
thnx
