### ISSUE TITLE
arm32v7 Build failing

### ISSUE THREAD

**Issue by jordiebiemold** [docker-library/rabbitmq#327]
I am attempting to run the `3.7.13-management-alpine` image on a Raspberry Pi 3 model B but the following error is produced:
```
docker run --rm rabbitmq:3.7.13-management-alpine
Unable to find image 'rabbitmq:3.7.13-management-alpine' locally
3.7.13-management-alpine: Pulling from library/rabbitmq
docker: no matching manifest for unknown in the manifest list entries.
See 'docker run --help'.
```
After checking i saw the arm32v7 build is failing (https://doi-janky.infosiftr.net/job/multiarch/job/arm32v7/job/rabbitmq/).

Can this be fixed or will i have to resort to something else?

I have tried the `arm64v8/rabbitmq:3.7.13-management-alpine` image but that gives the same result.

**Comment by tianon** [comment]
Thanks for the prod!  I've filed https://github.com/docker-library/rabbitmq/pull/328 which should hopefully fix the build failure.
