### ISSUE TITLE
ppc64el pull-problem

### ISSUE THREAD

**Issue by Tockra** [docker-library/rabbitmq#329]
Hello,

when I try to pull rabbitmq I get following error:
`
user@pc:~$ docker pull rabbitmq
Using default tag: latest 
latest: Pulling from library/rabbitmq
no matching manifest for unknown in the manifest list entries
`

I can pull other repositorys without problem.

T

**Comment by tianon** [comment]
It looks like the Ubuntu-based variants are failing to build on ppc64le for some reason. :disappointed:

https://doi-janky.infosiftr.net/job/multiarch/job/ppc64le/job/rabbitmq/

```
gosu: error while loading shared libraries: R_PPC64_ADDR16_HA reloc at 0x00000b69c5feaf58 for symbol `' out of range
```

Kind of a hairy one, and Google's not really helping much so I've reached out to someone at IBM to see if maybe they have some better ideas about what's happening there.

In the meantime, you should be able to use the Alpine variants on ppc64le, assuming `musl` is acceptable for how you want to use RabbitMQ.

**Comment by tianon** [comment]
Filed an issue with Ubuntu: https://bugs.launchpad.net/ubuntu/+source/gosu/+bug/1822632

**Comment by tianon** [comment]
This is fixed now! :tada:
