### ISSUE TITLE
How to configure as part of docker file

### ISSUE THREAD

**Issue by tdudgeon** [docker-library/rabbitmq#33]
I'm struggling with how to use this image and to configure some parts of the broker configuration as part of the Dockerfile. e.g I want to add a user and a virtual host so that I have a self contained image to use for integration testing.
I was thinking it would look something like this:

FROM rabbitmq:3-management
RUN /usr/sbin/rabbitmq-server &&\
  rabbitmqctl add_vhost test &&\
  rabbitmqctl add_user tester secret &&\
  rabbitmqctl set_permissions -p /test tester ".*" ".*" ".*"

The problem part seem to be starting the server so that rabbitmqctl can connect. 
The rabbitmq-server command seem to block, and nothing else ever happens, so this is clearly not the way to go about this.

Any suggestions?

**Comment by yosifkit** [comment]
The only way is to background the `rabbitmq-server` process, then run the rest, and then kill the backgrounded process (all in the same RUN).  There may be issues of the server not coming up fast enough and the `ctl` parts would fail.  This really is just a hack waiting to break.

The alternative is to just use the currently undocumented `RABBITMQ_DEFAULT_VHOST`, `RABBITMQ_DEFAULT_USER`, and `RABBITMQ_DEFAULT_PASSWORD` to `-e` in the `docker run`.  You can even set those with `ENV` in your Dockerfile.
