### ISSUE TITLE
Some RST (Reset) packets shows container IP as Source instead of Host IP (Sometimes NATing does not seems to work)

### ISSUE THREAD

**Issue by NiharPattanaik** [docker-library/rabbitmq#335]
We have a 2 node setup where RabbitMQ container present on each node communicates with each other over Federation link. When we have captured outgoing traffic on a source host using tcpdump, noticed for some RST packet the source IP is coming as container IP instead of Host IP. Seems like NATing is not working sometimes which is supposed to masquerade the container IP for outgoing traffic.

[root@npattana-62 ~]# docker version
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54266
 Built:             Wed Mar 27 18:34:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:04:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false

  have attached tcpdump screenshot where the last packet shows the issue.
<img width="1440" alt="Screen Shot 2019-04-25 at 12 01 57 PM" src="https://user-images.githubusercontent.com/25510438/57390399-e24c3d80-71d9-11e9-9857-21d271dc06a9.png">

**Comment by wglambert** [comment]
Cool find, looks like this is a known issue with Docker 
https://github.com/moby/moby/issues/18630

**Comment by tianon** [comment]
Closing since there doesn't appear to be anything we can do in the image to work around this -- it's likely going to have to be a fix higher up in the stack in either Docker or the kernel? :disappointed:
