### ISSUE TITLE
Erlang 22 series support

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#336]
This is not an issue but rather a heads-up and a place to discuss how we want to support Erlang 22.x which is now GA.

This image currently provides a single (latest) version of Erlang. If we want to continue this way, should we wait for a few 22.0.x patch releases? Should we consider supporting two major versions?

@gerhard

**Comment by gerhard** [comment]
> This image currently provides a single (latest) version of Erlang

As it currently stands, [Erlang/OTP versions are already pinned](https://github.com/docker-library/rabbitmq/blob/master/update.sh#L12-L15) and follow the official [Which Erlang - Max supported version](https://www.rabbitmq.com/which-erlang.html). This feels right from all perspectives.

> Should we wait for a few 22.0.x patch releases?

Yes. Out of experience, it's always best to wait out at least 2 patches for a new major release before upgrading, especially production.

> Should we consider supporting two major versions?

I don't see sufficient benefits in supporting multiple major versions. A single Erlang/OTP version feels adequate.

The plan for Erlang/OTP 22 is to start battle-testing it as early as next week. Most of this will be via [rabbitmq-prometheus](https://github.com/rabbitmq/rabbitmq-prometheus/tree/master/docker). The new metrics are insightful in more than one way, I am confident that we have everything we need to make the right decisions. FWIW, the [Dockerfile](https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/Dockerfile) is already based on the official Ubuntu one, it's an easy way of sharing relevant learnings.

Any thoughts @tianon & @yosifkit ?

**Comment by tianon** [comment]
Sounds reasonable!  We'll look forward to the results of your testing. :+1:

**Comment by gerhard** [comment]
This week was busier than usual, will continue with this next week. 🌆

**Comment by tianon** [comment]
Given the notes about HiPE in that thread, should we also remove our HiPE support from the image?

https://github.com/docker-library/rabbitmq/blob/dbbe820acaac916a975ccca45ea1a3662fd4ac59/Dockerfile-ubuntu.template#L119
https://github.com/docker-library/rabbitmq/blob/dbbe820acaac916a975ccca45ea1a3662fd4ac59/Dockerfile-alpine.template#L114
https://github.com/docker-library/rabbitmq/blob/dbbe820acaac916a975ccca45ea1a3662fd4ac59/docker-entrypoint.sh#L58

**Comment by gerhard** [comment]
Yes, definitely. This is from [OTP 22 release notes](http://erlang.org/download/otp_src_22.0.readme):

> In OTP 22, HiPE (the native code compiler) is not fully functional. The reasons for this are:

Search for **OTP-15596** in the above notes to see the rest.

Also, in the [OTP HiPE docs](http://erlang.org/doc/man/HiPE_app.html) there is this:

> HiPE and execution of HiPE compiled code only have limited support by the OTP team at Ericsson. The OTP team only does limited maintenance of HiPE and does not actively develop HiPE. HiPE is mainly supported by the HiPE team at Uppsala University.

**Comment by gerhard** [comment]
Nice!

Btw, [ERL-959](https://bugs.erlang.org/browse/ERL-959) turned out to not be a bug, it was just a matter of learning something new.

**Comment by avihil1** [comment]
> Yes, definitely.
> 
> This is from [OTP 22 release notes](http://erlang.org/download/otp_src_22.0.readme):
> 



Does it mean that RabbitMQ will be slower now, without HiPE compiling ?

**Comment by gerhard** [comment]
In the scenarios that HiPE was making RabbitMQ faster, then yes, RabbitMQ will be slower without HiPE.

In real-world scenarios, disks, network contention or lower-frequency CPUs (e.g. AMD Epyc) will have a higher impact on RabbitMQ than HiPE did. Client configuration (e.g. publisher confirms, multi confirm, etc.) will also have a significant impact on RabbitMQ's perceived speed.

It would be interesting to know what impact (if any) disabling HiPE in **your production** has (everyone's production is different). Care to share the performance that you are expecting out of RabbitMQ @avihil1?

Erlang Jit expected to ship in OTP 24 (summer 2021) - https://github.com/erlang/otp/pull/2745 - is the HiPE replacement that I am looking forward to 😉

You may find https://www.rabbitmq.com/blog/2020/06/04/how-to-run-benchmarks/ & https://github.com/rabbitmq/workloads useful. There are some good recent posts on our blog on this topic: https://www.rabbitmq.com/blog/category/performance-2/

**Comment by avihil1** [comment]
Thanks !

**Comment by gerhard** [comment]
My recommendation would be to **not** upgrade until you are satisfied with the benchmark results. Don't benchmark production. Setup an identical environment and simulate the traffic that production is expected to handle. It doesn't get any easier than this: https://github.com/rabbitmq/tgir/blob/S01E07/s01/e07/k8s/rabbitmq/default-metrics.yml. For extra context: https://github.com/rabbitmq/tgir/tree/S01E07/s01/e07

Everything that I mentioned above is from years of experience with under-performing production RabbitMQ deployments. I have more specifics in this RabbitMQ Summit 2018 talk: [Real-world RabbitMQ deployments](https://www.youtube.com/watch?v=etT_VMkYrdI).

**Comment by avihil1** [comment]
Thanks! very helpful
