### ISSUE TITLE
pause_minority mode is invalid after network partition recovery

### ISSUE THREAD

**Issue by gujun4990** [docker-library/rabbitmq#337]
Hello,
    I found a problem that pause_minority mode is invalid after network partition recovery. The below steps can reproduce the problem.
1. I have three RabbitMQ nodes to construct a cluster and configure pause_minority to prevent network partition.
2. Suppose the three RabbitMQ nodes are rabbit1, rabbit2 and rabbit3. I set iptable rules into rabbit2 node. The iptable rules are the below:
iptables -A INPUT -p tcp --dport 25672 -j DROP
iptables -A OUTPUT -p tcp --dport 25672 -j DROP
3. As I configure livenessprobe for every RabbitMQ node, the rabbit2 container will restart automatically.
4. After the rabbit2 container restart, I set the below iptable rules to recovery network.
iptables -D INPUT 1
iptables -D OUTPUT 1
5. When I run "rabbitmqctl cluster_status" for every RabbitMQ node, I found that RabbitMQ cluster status has not been restored. The result are the below.
**rabbit1 cluster status:**
bash-4.4# rabbitmqctl cluster_status
Cluster status of node rabbit@rabbit1
[{nodes,[{disc,[rabbit@rabbit1,rabbit@rabbit2,rabbit@rabbit3]}]},
 {running_nodes,[rabbit@rabbit3,rabbit@rabbit1]},
 {cluster_name,<<"rabbit@rabbit1">>},
 {partitions,[{rabbit@rabbit3,[rabbit@rabbit2]},
              {rabbit@rabbit1,[rabbit@rabbit2]}]},
 {alarms,[{rabbit@rabbit3,[]},{rabbit@rabbit1,[]}]
**rabbit2 cluster status:**
bash-4.4# rabbitmqctl cluster_status
Cluster status of node rabbit@rabbit2
[{nodes,[{disc,[rabbit@rabbit1,rabbit@rabbit2,rabbit@rabbit3]}]},
 {running_nodes,[rabbit@rabbit2]},
 {cluster_name,<<"rabbit@rabbit1">>},
 {partitions,[{rabbit@rabbit2,[rabbit@rabbit1,rabbit@rabbit3]}]},
 {alarms,[{rabbit@rabbit2,[]}]}]
**rabbit3 cluster status:**
bash-4.4# rabbitmqctl cluster_status
Cluster status of node rabbit@rabbit3
[{nodes,[{disc,[rabbit@rabbit1,rabbit@rabbit2,rabbit@rabbit3]}]},
 {running_nodes,[rabbit@rabbit1,rabbit@rabbit3]},
 {cluster_name,<<"rabbit@rabbit1">>},
 {partitions,[{rabbit@rabbit1,[rabbit@rabbit2]},
              {rabbit@rabbit3,[rabbit@rabbit2]}]},
 {alarms,[{rabbit@rabbit1,[]},{rabbit@rabbit3,[]}]}]

6. I also verify the situation that un-configure livenessprobe for every RabbitMQ node, and rabbit2 container will not restart automatically when occur network partition. **The cluster status will recovery after network recovery.**

From the above result, I don't know why the pause_minority was invalid after rabbit2 container restart automatically. So someone can help me to how to solve this problem. Thank you.

**Comment by wglambert** [comment]
Could you get a minimal reproducer of this issue so we can possibly probe around, also do you encounter this outside of a container environment?

**Comment by gujun4990** [comment]
The cluster status can recovery when RabbitMQ cluster run outside of a container environment. So I suppose the RabbitMQ status is destoryed when the container restart.
BTW: I also verify the 3.7.14 version of RabbitMQ image, the cluster status is not restored.

**Comment by michaelklishin** [comment]
This is rabbitmq-users (the mailing list) material and has nothing to do with the image. A rejoining node will [attempt to contact](https://www.rabbitmq.com/clustering.html#restarting) its peers for N times before giving up. See (and share) server logs on all nodes and in particular node 2.

**Comment by gujun4990** [comment]
> This is rabbitmq-users (the mailing list) material and has nothing to do with the image. A rejoining node will [attempt to contact](https://www.rabbitmq.com/clustering.html#restarting) its peers for N times before giving up. See (and share) server logs on all nodes and in particular node 2.

I add log to attachment and I will continue to analysis source for RabbitMQ. Thank you for help me.

[network partition log.zip](https://github.com/docker-library/rabbitmq/files/3219070/network.partition.log.zip)

**Comment by gujun4990** [comment]
> This is rabbitmq-users (the mailing list) material and has nothing to do with the image. A rejoining node will [attempt to contact](https://www.rabbitmq.com/clustering.html#restarting) its peers for N times before giving up. See (and share) server logs on all nodes and in particular node 2.

    I had analyzed the source code of RabbitMQ that how to prevent network partition for pause_minority configuration. I found that rabbit2 think self is in a minority and stop applications and dependencies. At the same time, rabbit2 will be paused and spawn another thread to ping rabbit1 and rabbit2 every 1 seconds.
    But if rabbit2 restart automatically due to health check for kubernetes, the rabbit2 will not be paused. So the network partition will form even after network recovery. So I think I should not add livenessprobe to rabbitmq container.

**Comment by michaelklishin** [comment]
A liveness probe is a good idea but there is [no one true check](https://www.rabbitmq.com/monitoring.html#health-checks), so you have to come up with a combination that makes sense for your environment. Restarting a node because it is paused in minority mode or has a memory alarm are not reasonable scenarios, for example. But if it has virtual hosts that failed and cannot recover, it is.

**Comment by gujun4990** [comment]
Thanks for your reply, I will consider my liveness probe again.

**Comment by gujun4990** [comment]
> A liveness probe is a good idea but there is [no one true check](https://www.rabbitmq.com/monitoring.html#health-checks), so you have to come up with a combination that makes sense for your environment. Restarting a node because it is paused in minority mode or has a memory alarm are not reasonable scenarios, for example. But if it has virtual hosts that failed and cannot recover, it is.

@michaelklishin, I have read monitoring for RabbitMQ website again and found no good ways to detect virtual host that failed. So if you have a good way to solve the problem, please tell me. Thank you very much.
