### ISSUE TITLE
documentation needed for `RABBITMQ_DEFAULT_VHOST`, `RABBITMQ_DEFAULT_USER`, and `RABBITMQ_DEFAULT_PASSWORD`

### ISSUE THREAD

**Issue by yosifkit** [docker-library/rabbitmq#34]
Need documentation similar to [cassandra](https://github.com/docker-library/docs/blob/master/cassandra/content.md#environment-variables) on the possible environment variables that can be passed in.  Specifically a PR to modify: [docker-library/docs/rabbitmq/content.md](https://github.com/docker-library/docs/blob/master/rabbitmq/content.md).

**Comment by workmaster2n** [comment]
I just submitted a PR, but it might have been to the wrong repo: https://github.com/docker-library/docs/pull/290.

**Comment by yosifkit** [comment]
This was already fixed :neutral_face:
