### ISSUE TITLE
Remove private keys stored in image 

### ISSUE THREAD

**Issue by maximusfloydus** [docker-library/rabbitmq#346]
During a security scan we found the following private keys in the image that should not be needed.

Found: 
/usr/local/lib/erlang/lib/inets-7.0.8/examples/httpd_load_test/hdlt_ssl_client_cert.pem, 
/usr/local/lib/erlang/lib/inets-7.0.8/examples/httpd_load_test/hdlt_ssl_server_cert.pem, 
/usr/local/lib/erlang/lib/inets-7.0.8/examples/server_root/ssl/ssl_client.pem, 
/usr/local/lib/erlang/lib/inets-7.0.8/examples/server_root/ssl/ssl_server.pem, 
/usr/local/lib/erlang/lib/ssl-9.3.3/examples/certs/etc/client/key.pem, 
/usr/local/lib/erlang/lib/ssl-9.3.3/examples/certs/etc/server/key.pem

**Comment by tianon** [comment]
Good point -- the `erlang` image handles this by simply removing all `examples` directories entirely: https://github.com/erlang/docker-erlang-otp/blob/6a5aecea0a1ce5e62c47bae72f6a3199908fdc55/22/Dockerfile#L31

We should probably follow suit (and I'll have a PR up shortly).
