### ISSUE TITLE
Rabbit process does not respond to SIGTERM signal issued by "docker stop"

### ISSUE THREAD

**Issue by dunk** [docker-library/rabbitmq#35]
Running "docker stop" or "docker-compose down" takes a full 10 seconds (the timeout) to stop a rabbit container made from this image. In the end the system just sends it a SIGKILL, which is a pretty brutal way to stop it. Ideally the server would be passed, and would respond appropriately and in a timely fashion, to the original SIGKILL signal.

**Comment by tianon** [comment]
@dumbbell this is another case of something we could either work around here (with https://github.com/krallin/tini being the solution I'd put in), or we could see whether this makes sense to fix upstream instead :+1:

To give you a little background on the issue, in Docker the RabbitMQ process runs as PID 1 inside the container, which means it has special signal characteristics.  For normal processes, any signal they don't capture and deal with leads to process death, but for PID 1, uncaptured signals are ignored.  In this specific case, what this means is that RabbitMQ isn't explicitly listening for `SIGTERM` as a "graceful shutdown" signal, and is instead relying on the normal default behavior of the process just dying outright but that means that in Docker, `SIGTERM` is completely ignored and we have to wait for `docker stop` to timeout and send `SIGKILL` (which can't be captured or ignored).

If this sounds like something you'd be interested in having implemented upstream (either for graceful shutdown or for forceful shutdown, not sure whether "graceful" even makes sense in the context of RabbitMQ), we're happy to help however we can to make that happen.  If not, we'll just add `tini` (which is really lightweight and solves this problem pretty well). :+1:

**Comment by dumbbell** [comment]
Hi @tianon!

Just to let you know I saw this issue. I'm a bit overloaded with other issues right now, but I will eventually work on this one. I created an "proxy" issue on our side: rabbitmq/rabbitmq-server#234.

**Comment by tianon** [comment]
Thanks! :smile:

In the mean time, do you think it'd be ok if we add the simple workaround
and remove it when the fix is released?

**Comment by michaelklishin** [comment]
@tianon we can't object to other projects working around Rabbit's limitations :) If this is something you're willing to maintain for a while, go for it.

**Comment by tianon** [comment]
@michaelklishin awesome -- you guys really are a great upstream :heart:

The workaround is really simple, so I'm implementing it right now and will keep on eye on that other issue for when we can remove it. :+1:

**Comment by stefanscheid** [comment]
Hi,
I have a similar issue on Ubuntu 18.04, no docker.
rabbit doesnt shut down within 90secs while Ubuntu is shutting down, so Unbuntu SIGKILLs it.
Is this related or did I get sth wrong in the docs?
Best
Stefan

**Comment by tianon** [comment]
> I have a similar issue on Ubuntu 18.04, no docker.

If you're not using Docker, this definitely isn't the right place to comment. :sweat_smile:

(This repository is specifically for the `rabbitmq` Docker image.)
