### ISSUE TITLE
Consider using the new "latest toolchain" generic UNIX package (LTP)

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#351]
Starting with 3.7.16, there is a new RabbitMQ package, `generic-unix-latest-toolchain` (called the LTP for "latest toolchain package" below), which is produced on the latest Erlang (`22.x`) and Elixir (`1.9.x`) releases. As such, it has the potential to incorporate all the recent optimizations in both compilers.

Given that this image provisions latest supported patch release of Erlang, it is feasible for it to use this new package type. Whether it should, I don't know. Our pipelines performs the same integration and package testing as for the classic generic UNIX package, so it should be reasonably safe to do so.

@tianon @yosifkit @gerhard any thoughts?

**Comment by tianon** [comment]
Is there a document somewhere that describes what the difference between `rabbitmq-server-generic-unix-3.7.16.tar.xz` and `rabbitmq-server-generic-unix-latest-toolchain-3.7.16.tar.xz` is?  I'm honestly having a hard time understanding what would be functionally different by using the latter of those vs the former that we're currently using. :sweat_smile: :innocent:

Does it include precompiled assets which are optimized for newer Erlang to be more efficient or something similar?

**Comment by gerhard** [comment]
> Does it include precompiled assets which are optimized for newer Erlang to be more efficient or something similar?

Yes. The Erlang bytecode that is produced by the latest version of Erlang will leverage the latest optimisations in the virtual machine. The resulting `latest-toolchain` RabbitMQ artefacts can make use of the latest and greatest, as well as pick up bytecode improvements as they get released.

This is a great idea Michael 🤘🏻

**Comment by michaelklishin** [comment]
The only difference is compiler versions used to build the package. Compiling on the oldest version we support (20.3 at the moment, 21.3 starting in Aug 2019) makes all compiler pass optimizations introduced in OTP 22 are irrelevant to RabbitMQ binary builds.

**Comment by gerhard** [comment]
> Compiling on the oldest version we support (20.3 at the moment, 21.3 starting in Aug 2019) makes all compiler pass optimizations introduced in OTP 22 irrelevant to RabbitMQ binary build users.

I am either misunderstanding this statement, or I misunderstood your initial proposal.

I was under the impression that the biggest advantage to running bytecode compiled on OTP 22 is the [SSA optimisations](http://blog.erlang.org/introducing-ssa/), which are not present in earlier OTP versions:

* [OTP 20.3 vs OTP 22.0.6](https://github.com/erlang/otp/compare/OTP-20.3...OTP-22.0.6) (current latest)
* [OTP 21.3 vs OTP 22.0.6](https://github.com/erlang/otp/compare/OTP-21.3...OTP-22.0.6) (current latest)

So which part am I misunderstanding 🤔

**Comment by michaelklishin** [comment]
That's right. We compile regular binary builds on OTP 20.3 and the "latest toolchain" package (LTP) on OTP 22. Since this image ships with OTP 22, it can afford to use the LTP.

**Comment by gerhard** [comment]
OK, so **we want RabbitMQ LTP in this image to benefit from OTP 22 compiler optimisations**  👍🏻

**Comment by tianon** [comment]
Is there a one-liner we can use to verify everything's good in the `Dockerfile` after we download/extract?  Are the existing checks enough to do at least that much, or is it too difficult to verify that completely?

https://github.com/docker-library/rabbitmq/blob/e1afff47a82c24c639f2e3cc5ed318c45f46e7e9/Dockerfile-ubuntu.template#L239-L243

**Comment by michaelklishin** [comment]
@tiagomtotti basic [health checks](https://www.rabbitmq.com/monitoring.html#health-checks), perhaps? The guide describes our approach to health checks. No objections to running the commands you run already in addition, in particular `rabbitmq-plugins list` makes sense for a Docker image.

**Comment by michaelklishin** [comment]
Apologies for an accidental mention of someone not participating here 🤦‍♂.

**Comment by gerhard** [comment]
@tianon if I was to pick a single one-liner that checks if everything is good after RabbitMQ is downloaded & extracted, then `rabbitmqctl list_ciphers` would be it. This ensures that OpenSSL & Erlang work with RabbitMQ, and that the built-in Elixir is compatible with Erlang.

`rabbitmq-plugins list` is another command worth running, since it shows which plugins are available. If this command succeeds, permissions are likely to be OK, which is a decent sanity check.

**Comment by michaelklishin** [comment]
For the "after extraction" stage what @gerhard suggested sounds good to me. I forgot that the official image policy on health checks is "it's up to the user" :)

**Comment by tianon** [comment]
Nice, sounds good!  To be clear, I was just looking for something to help make sure we catch it if we ever end up out of sync with what's being used to generate those, so it sounds like with the few commands we run in the `Dockerfile` itself (where `rabbitmq-server` isn't running yet) and the couple tests we've got over in https://github.com/docker-library/official-images/tree/master/test that we run on every update we should be covered plenty well. :+1:
