### ISSUE TITLE
TLS breaks rabbitmqctl. 

### ISSUE THREAD

**Issue by BenCoughlan15** [docker-library/rabbitmq#357]
**Hi all, 
For any of the new images I get the following issue:** 

    `[Unit]
    Description=Rabbitmq Service
    
    [Service]
    TimeoutSec=120m
    Restart=always
    
    LimitNOFILE=100000
    LimitNPROC=1048576
    ExecStartPre=-/usr/bin/docker rm -f rabbitmq
    ExecStartPre=-/usr/bin/docker pull rabbitmq:3.7.17-management-alpine
    ExecStartPre=-/bin/bash -c '/bin/echo HOSTNAME=$HOSTNAME > /opt/instance.env'
    ExecStartPre=-/bin/bash -c '/bin/echo RABBITMQ_NODENAME=rabbit@$HOSTNAME >> /opt/instance.env'
    ExecStartPre=-/bin/bash /opt/certs.sh
    
    EnvironmentFile=/opt/instance.env
    
    ExecStart=/usr/bin/docker run --name rabbitmq \
              --env-file=/opt/instance.env \
              -p 9419:9419 -p 4369:4369 -p 5672:5672 -p 15672:15672 -p 25672:25672 -p 5671:5671 -p 15671:15671 \
              -e RABBITMQ_USERNAME='user' -e RABBITMQ_PASSWORD='password' \
              -e RABBITMQ_DEFAULT_PASS='password' -e RABBITMQ_DEFAULT_USER='admin' \
              -e NAMI_LOG_LEVEL=trace -e RABBITMQ_ERLANG_COOKIE='GyPC7YWDGxZWVC8F78xp8Yf9ZcN8sHqo9HmVa5w8x4xMeQx8HFckA48yEs3bWuhq' \
              -e RABBITMQ_SSL_CACERTFILE=/opt/ca_certificate.pem -e RABBITMQ_SSL_CERTFILE=/opt/certificate.pem \
              -e RABBITMQ_SSL_DEPTH=1 -e RABBITMQ_SSL_KEYFILE=/opt/key.pem \
              -e SSL_LISTENERS="5671" --net="host" \
              -v /opt/instance.env:/opt/instance.env -v /opt/find_hosts.sh:/opt/find_hosts.sh \
              -v /opt/join_cluster.sh:/opt/join_cluster.sh -v /opt/certificate.pem:/opt/certificate.pem \
              -v /opt/ca_certificate.pem:/opt/ca_certificate.pem -v /opt/key.pem:/opt/key.pem \
              rabbitmq:3.8-rc
    
    ExecStartPost=/bin/bash -c '/root/configure.sh'
    
    [Install]
    WantedBy=multi-user.target`

**However, in /root/configure.sh I now want to run the following:** 

    `#!/usr/bin/env bash
    docker exec rabbitmq rabbitmqctl add_user admin password
    
    docker exec rabbitmq rabbitmqctl set_user_tags admin administrator
    
    docker exec rabbitmq rabbitmqctl add_user user password
    
    docker exec rabbitmq rabbitmqctl set_user_tags user administrator
    
    docker exec rabbitmq rabbitmqctl set_policy -p / ha-three "^" '{"ha-mode":"exactly", "ha-params":3, "ha-sync-mode":"automatic", "message-ttl":259200000, "expires":259200000}'
    
    docker exec rabbitmq rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
    
    docker exec rabbitmq rabbitmqctl set_permissions -p / user ".*" ".*" ".*"
    
    /bin/bash -c '/bin/echo HOSTNAME=$HOSTNAME > /opt/instance.env'
    
    /bin/bash -c '/opt/find_hosts.sh >> /opt/instance.env'
    
    docker exec rabbitmq bash /opt/join_cluster.sh
    exit 0
    `

**in the console I then get:** 

> Error: unable to perform an operation on node 'rabbit@ip-10-4-33-244'.
> Please see diagnostics information and suggestions below.
> 
> Most common reasons for this are:
> 
>  * Target node is unreachable (e.g. due to hostname resolution, TCP
> connection or firewall issues)  * CLI tool fails to authenticate with
> the server (e.g. due to CLI tool's Erlang cookie not matching that of
> the server)  * Target node is not running
> 
> In addition to the diagnostics info below:
> 
>  * See the CLI, clustering and networking guides on
> https://rabbitmq.com/documentation.html to learn more  * Consult
> server logs on node rabbit@ip-10-4-33-244  * If target node is
> configured to use long node names, don't forget to use --longnames
> with CLI tools
> 
> DIAGNOSTICS
> ===========
> 
> attempted to contact: ['rabbit@ip-10-4-33-244']
> 
> rabbit@ip-10-4-33-244:   * connected to epmd (port 4369) on
> ip-10-4-33-244   * epmd reports node 'rabbit' uses port 25672 for
> inter-node and CLI tool traffic   * TCP connection succeeded but
> Erlang distribution failed
> 
>   * Remote host closed TCP connection before completing
> authentication. Is the Erlang distribution using TLS?
> 
> 
> Current node details:  * node name:
> 'rabbitmqcli-2503-rabbit@ip-10-4-33-244'  * effective user's home
> directory: /var/lib/rabbitmq  * Erlang cookie hash:
> abhTtMFEi/Kkb9xvPt2erQ==

any ideas? I've tried setting args, but they're useless, and it's causing a catch 22, where I can't cluster up rabbitmq with TLS. 

I've also tried to run the docker-entrypoint.sh script before rabbitmqctl commands, which doesn't work. 

Why enable SSL if it breaks everything else? 

Ben

**Comment by tianon** [comment]
Instead of running `docker exec rabbitmq rabbitmqctl ...` directly, can you try passing that through `docker-entrypoint.sh`? (ala, `docker exec rabbitmq docker-entrypoint.sh rabbitmqctl ...`)

**Comment by tianon** [comment]
Doh read too quickly -- that should work. Any more details about how that fails? I'll get to a keyboard ASAP to try reproducing myself but it's going to be a bit.

**Comment by BenCoughlan15** [comment]
sure 

> docker exec rabbitmq docker-entrypoint.sh rabbitmqctl list_users

gives me the same error :)

**Comment by BenCoughlan15** [comment]
I'll get the env vars out for you while I'm in there. 


```
RABBITMQ_DEFAULT_PASS=g0kU3R5CWUGg3xnoWriV07rX7m2psldR
LC_ALL=C.UTF-8
RABBITMQ_SSL_KEYFILE=/opt/key.pem
LANG=C.UTF-8
HOSTNAME=ip-10-4-33-244
OPENSSL_VERSION=1.1.1c
OTP_VERSION=22.0.7
RABBITMQ_SASL_LOGS=-
RABBITMQ_HOME=/opt/rabbitmq
NAMI_LOG_LEVEL=trace
PWD=/
RABBITMQ_LOGS=-
HOME=/var/lib/rabbitmq
OPENSSL_PGP_KEY_IDS=0x8657ABB260F056B1E5190839D9C4D26D0E604491 0x5B2545DAB21995F4088CEFAA36CEE4DEB00CFE33 0xED230BEC4D4F2518B9D7DF41F0DB4D21C1D35231 0xC1F33DD8CE1D4CC613AF14DA9195C48241FBF7DD 0x7953AC1FBC3DC8B3B292393ED5E9E43F7DF9EE8C 0xE5E52560DD91C556DDBDA5D02064C53641C25E5D
RABBITMQ_VERSION=3.8.0-beta.5
RABBITMQ_SSL_DEPTH=1
RABBITMQ_DATA_DIR=/var/lib/rabbitmq
RABBITMQ_NODENAME=rabbit@ip-10-4-33-244
RABBITMQ_SSL_CERTFILE=/opt/certificate.pem
TERM=xterm
RABBITMQ_PGP_KEY_ID=0x0A9AF2115F4687BD29803A206B73A36E6026DFCA
RABBITMQ_ERLANG_COOKIE=GyPC7YWDGxZWVC8F78xp8Yf9ZcN8sHqo9HmVa5w8x4xMeQx8HFckA48yEs3bWuhq
RABBITMQ_PASSWORD=g0kU3R5CWUGg3xnoWriV07rX7m2psldR
SHLVL=1
LANGUAGE=C.UTF-8
SSL_LISTENERS=5671
OPENSSL_SOURCE_SHA256=f6fb3079ad15076154eda9413fed42877d668e7069d9b87396d0804fdb3f4c90
RABBITMQ_DEFAULT_USER=babylon
RABBITMQ_USERNAME=babylon
PATH=/opt/rabbitmq/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OTP_SOURCE_SHA256=04c090b55ec4a01778e7e1a5b7fdf54012548ca72737965b7aa8c4d7878c92bc
RABBITMQ_SSL_CACERTFILE=/opt/ca_certificate.pem
_=/usr/bin/env
```

**Comment by BenCoughlan15** [comment]
**so it seems this works:**

` docker exec rabbitmq bash /usr/local/bin/docker-entrypoint.sh /opt/rabbitmq/sbin/rabbitmqctl list_users`


FML a day working on this.  🥇

**Comment by BenCoughlan15** [comment]
Right, The other cause of this was down to the cert not having a trailing space at the end of it, thus when it ends up in /tmp/rabbitmq-ssl/combined.pem it doesn't render properly, fixing that file and running the command with /usr/local/bin/docker-entrypoint.sh /opt/rabbitmq/sbin/rabbitmqctl list_users.

**Comment by tianon** [comment]
Ah, that was probably the root cause all along (and the full paths "working" was probably just a red herring).  I'm guessing using `PATH` would work fine now.

Perhaps we should inject a line of whitespace between these when we create `combined.pem`. :thinking:
