### ISSUE TITLE
No default vhost or user created if definition.json exists

### ISSUE THREAD

**Issue by vincenzodnp** [docker-library/rabbitmq#365]
Hello there.
I'm trying to apply a _definitions.json_ file to a rabbitmq 3.7 management container.
Here my Dockerfile
```
FROM rabbitmq:3-management
ADD definitions.json /etc/rabbitmq/definitions.json
```
and here my _definitions.json_ file
```
{
  "vhosts":[
        {"name": "/"}
  ],
  "policies":[
        {"vhost":"/","name":"ha","pattern":"^test-", "definition":{"ha-mode":"all","ha-sync-mode":"automatic","ha-sync-batch-size":5}}
  ]
}
```
When I run the container, it starts correctly but no default user and password are set.
```
rabbitmqctl list_users
Listing users ...
```
even if 
_rabbitmqctl environments_ shows: 
```
{default_permissions,[<<".*">>,<<".*">>,<<".*">>]},
{default_user,<<"guest">>},
{default_user_tags,[administrator]},
{default_vhost,<<"/">>},
```
I have tried also to run the container with RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS variables, but no luck.

If I remove the _vhosts_ section in _definitions.json_ . container doesn' start and shows error
`{error,<<"Please create virtual host \"\" prior to importing definitions.">>}`

So has _definitions.json_ precedence instead of rabbitmq.conf? Why empty database is not initialized **BEFORE** import definitions.json?
Thanks
Vincenzo

**Comment by vincenzodnp** [comment]
PS: If I use a complete _definitions.json_ file, with users, permissions, vhost and policies sections, all is working as expected

**Comment by wglambert** [comment]
https://www.rabbitmq.com/management.html#load-definitions
>if you start from a completely reset broker, use of this option will prevent the usual default user / virtual host / permissions from being created.

Using environment variables modifies the `rabbitmq.conf` correctly, but they're not interpreted with the definitions.json being used
```console
$ docker run -d --rm -p 8080:15672 -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password --name rabbit rabbitmq:test
8599aa036285a73822da5837c6e132825ba94a3429f9e143bc29057598945670

$ docker exec rabbit cat /etc/rabbitmq/rabbitmq.conf
loopback_users.guest = false
listeners.tcp.default = 5672
default_pass = password
default_user = user
management.listener.port = 15672
management.listener.ssl = false
management.load_definitions = /etc/rabbitmq/definitions.json

$ docker exec rabbit rabbitmqctl list_users
Listing users ...


```

**Comment by tianon** [comment]
Closing as this is the intentional behavior of RabbitMQ upstream. :+1:

**Comment by vincenzodnp** [comment]
Thanks for the answers.

**Comment by andilabs** [comment]
@vincenzodnp could you show how your fully pleged defintions.json looks like to create default user with pass?

**Comment by vincenzodnp** [comment]
I used this: 
```{
  "vhosts":[
        {"name": "${RABBITMQ_DEFAULT_VHOST}"}
  ],
  "users": [
        { "name": "${RABBITMQ_DEFAULT_USER}", "password": "${RABBITMQ_DEFAULT_PASS}", "tags": "administrator" }
  ],
  "permissions":[
        { "user": "${RABBITMQ_DEFAULT_USER}", "vhost": "${RABBITMQ_DEFAULT_VHOST}", "configure": ".*", "write": ".*", "read": ".*" }
  ],
  "policies":[
        {"vhost":"${RABBITMQ_DEFAULT_VHOST}","name":"lagoon-ha","pattern":"${RABBITMQ_DEFAULT_HA_PATTERN}", "definition":{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic","ha-sync-batch-size":5}}
  ]
}

**Comment by jason-leeee** [comment]
> I used this:
> 
> ```
>   "vhosts":[
>         {"name": "${RABBITMQ_DEFAULT_VHOST}"}
>   ],
>   "users": [
>         { "name": "${RABBITMQ_DEFAULT_USER}", "password": "${RABBITMQ_DEFAULT_PASS}", "tags": "administrator" }
>   ],
>   "permissions":[
>         { "user": "${RABBITMQ_DEFAULT_USER}", "vhost": "${RABBITMQ_DEFAULT_VHOST}", "configure": ".*", "write": ".*", "read": ".*" }
>   ],
>   "policies":[
>         {"vhost":"${RABBITMQ_DEFAULT_VHOST}","name":"lagoon-ha","pattern":"${RABBITMQ_DEFAULT_HA_PATTERN}", "definition":{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic","ha-sync-batch-size":5}}
>   ]
> }
> ```

Had the same issue and this solved it!

**Comment by v-bulynkin** [comment]
I've tried using `${RABBITMQ_DEFAULT_USER}` and `${RABBITMQ_DEFAULT_PASS}` in definitions.json as shown above and now I have login ${RABBITMQ_DEFAULT_USER} and password ${RABBITMQ_DEFAULT_PASS} (literally).
What's wrong?

**Comment by lukebakken** [comment]
@v-bulynkin I have no idea how the method in [this comment](https://github.com/docker-library/rabbitmq/issues/365#issuecomment-1176356694) ever worked. Templating the `definitons.json` file is not supported.

Please start a [new discussion](https://github.com/docker-library/rabbitmq/discussions) and we can assist you. *Attach* your complete `Dockerfile` and all other files necessary to demonstrate what you are trying to accomplish. Thanks.
