### ISSUE TITLE
Clustering and HA Policy

### ISSUE THREAD

**Issue by workmaster2n** [docker-library/rabbitmq#38]
I've been trying to think of a clever way to set up clustering and HA policies with this image.

The problem is that the server must be running to setup clustering and HA policies.  We could configure clustering via the configuration file, but that would mean it would have to be built into the docker image.

HA policy doesn't have a configuration option, so we would need to do that on a running instance. As noted in #33 that is 'just a hack waiting to break.'

One option that could work would be to kick off a container that runs rabbitmq-server, then have another container connect to that server and remotely modify it by running the `rabbitmqctl` commands from this second container.

Though this approach should work, just feels heavy handed as an approach to set up our cluster.

**Comment by tianon** [comment]
Unfortunately, I think "modify/setup after startup" is the best we've got right now. :disappointed:

**Comment by tianon** [comment]
With 3.7, there are newer methods of setting up clustering that might be easier for this use case.  See https://www.rabbitmq.com/clustering.html for details. :+1:
