### ISSUE TITLE
Add RABBITMQ_MANAGEMENT_RATES_MODE variable

### ISSUE THREAD

**Issue by decaz** [docker-library/rabbitmq#383]
It would be nice to have `RABBITMQ_MANAGEMENT_RATES_MODE` environment variable for config setting `management.rates_mode` to turn detailed message rates on or turn message rates off.

**Comment by wglambert** [comment]
We're looking to deprecate the current RabbitMQ environment variables https://github.com/docker-library/rabbitmq/issues/376#issuecomment-542511400 in favor of setting them via the [config file](https://github.com/docker-library/docs/tree/master/rabbitmq#additional-configuration)

```console
$ docker run -d --rm --name rabbit -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_management_agent rates_mode none" rabbitmq:management
db31b7502c7cdf91bbf6a45b67a490ab462a1f9bdab2aef8270c263b3389cd42

$ docker exec rabbit rabbitmqctl environment | grep -iC1 rates_mode
 {rabbitmq_management_agent,
     [{rates_mode,none},
      {sample_retention_policies,
```

**Comment by wglambert** [comment]
I'm going to close since this is easily doable with `-e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS`
