### ISSUE TITLE
Some weird bug or my misunderstanding help pls

### ISSUE THREAD

**Issue by dokazhi** [docker-library/rabbitmq#386]
Hi, i have some issue, i am using rabbitmq:3.8-alpine. This is part of docker-compose:

> rabbit:
>     image: rabbitmq:3.8-alpine
>     hostname: 'habbit'
>     volumes:
>       - ./rabbitmq-data:/var/lib/rabbitmq
>       - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
>     ports:
>       - "4369:4369"
>       - "5671:5671"
>       - "5672:5672"
>     environment:
>       - RABBITMQ_ERLANG_COOKIE=******************************

I am using it with django(celery), and in a while time in crushing, container just get critical timeout and shutting down. I tried to find solution at stackoverflow, but nothing similar, so this my crash.log

> 2020-01-11 06:33:45 =ERROR REPORT====
> ** Generic server aten_detector terminating 
> ** Last message in was poll
> ** When Server state == {state,#Ref<0.3953062075.3096182785.152330>,1000,0.99,#{},#{}}
> ** Reason for termination ==
> ** {{timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},{aten_detector,handle_info,2,[{file,"src/aten_detector.erl"},{line,97}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
> 2020-01-11 06:33:45 =CRASH REPORT====
>   crasher:
>     initial call: aten_detector:init/1
>     pid: <0.282.0>
>     registered_name: aten_detector
>     exception exit: {{timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},{aten_detector,handle_info,2,[{file,"src/aten_detector.erl"},{line,97}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
>     ancestors: [aten_sup,<0.278.0>]
>     message_queue_len: 2
>     messages: [poll,{#Ref<0.3953062075.3096182785.152355>,#{}}]
>     links: [<0.279.0>]
>     dictionary: []
>     trap_exit: false
>     status: running
>     heap_size: 1598
>     stack_size: 27
>     reductions: 4156731
>   neighbours:
> 2020-01-11 06:33:45 =SUPERVISOR REPORT====
>      Supervisor: {local,aten_sup}
>      Context:    child_terminated
>      Reason:     {timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}}
>      Offender:   [{pid,<0.282.0>},{id,aten_detector},{mfargs,{aten_detector,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
> 
> 2020-01-11 06:34:38 =ERROR REPORT====
> ** Generic server aten_detector terminating 
> ** Last message in was poll
> ** When Server state == {state,#Ref<0.3953062075.3096182785.209581>,1000,0.99,#{},#{}}
> ** Reason for termination ==
> ** {{timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},{aten_detector,handle_info,2,[{file,"src/aten_detector.erl"},{line,97}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
> 2020-01-11 06:34:38 =CRASH REPORT====
>   crasher:
>     initial call: aten_detector:init/1
>     pid: <0.9595.3>
>     registered_name: aten_detector
>     exception exit: {{timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},{aten_detector,handle_info,2,[{file,"src/aten_detector.erl"},{line,97}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
>     ancestors: [aten_sup,<0.278.0>]
>     message_queue_len: 2
>     messages: [poll,{#Ref<0.3953062075.3096182785.209590>,#{}}]
>     links: [<0.279.0>]
>     dictionary: []
>     trap_exit: false
>     status: running
>     heap_size: 610
>     stack_size: 27
>     reductions: 1895
>   neighbours:
> 2020-01-11 06:34:38 =SUPERVISOR REPORT====
>      Supervisor: {local,aten_sup}
>      Context:    child_terminated
>      Reason:     {timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}}
>      Offender:   [{pid,<0.9595.3>},{id,aten_detector},{mfargs,{aten_detector,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
> 
> 2020-01-11 06:35:01 =ERROR REPORT====
> ** Generic server aten_detector terminating 
> ** Last message in was poll
> ** When Server state == {state,#Ref<0.3953062075.3096182785.234543>,1000,0.99,#{},#{}}
> ** Reason for termination ==
> ** {{timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},{aten_detector,handle_info,2,[{file,"src/aten_detector.erl"},{line,97}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
> 2020-01-11 06:35:01 =CRASH REPORT====
>   crasher:
>     initial call: aten_detector:init/1
>     pid: <0.9623.3>
>     registered_name: aten_detector
>     exception exit: {{timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},{aten_detector,handle_info,2,[{file,"src/aten_detector.erl"},{line,97}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
>     ancestors: [aten_sup,<0.278.0>]
>     message_queue_len: 2
>     messages: [poll,{#Ref<0.3953062075.3096182785.234554>,#{}}]
>     links: [<0.279.0>]
>     dictionary: []
>     trap_exit: false
>     status: running
>     heap_size: 610
>     stack_size: 27
>     reductions: 726
>   neighbours:
> 2020-01-11 06:35:01 =SUPERVISOR REPORT====
>      Supervisor: {local,aten_sup}
>      Context:    child_terminated
>      Reason:     {timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}}
>      Offender:   [{pid,<0.9623.3>},{id,aten_detector},{mfargs,{aten_detector,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
> 
> 2020-01-11 08:32:33 =ERROR REPORT====
> ** Generic server aten_detector terminating 
> ** Last message in was poll
> ** When Server state == {state,#Ref<0.3953062075.3099066369.47061>,1000,0.99,#{},#{}}
> ** Reason for termination ==
> ** {{timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},{aten_detector,handle_info,2,[{file,"src/aten_detector.erl"},{line,97}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
> 2020-01-11 08:32:33 =CRASH REPORT====
>   crasher:
>     initial call: aten_detector:init/1
>     pid: <0.9630.3>
>     registered_name: aten_detector
>     exception exit: {{timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},{aten_detector,handle_info,2,[{file,"src/aten_detector.erl"},{line,97}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
>     ancestors: [aten_sup,<0.278.0>]
>     message_queue_len: 1
>     messages: [poll]
>     links: [<0.279.0>]
>     dictionary: []
>     trap_exit: false
>     status: running
>     heap_size: 2586
>     stack_size: 27
>     reductions: 406545
>   neighbours:
> 2020-01-11 08:32:33 =SUPERVISOR REPORT====
>      Supervisor: {local,aten_sup}
>      Context:    child_terminated
>      Reason:     {timeout,{gen_server,call,[aten_sink,get_failure_probabilities]}}
>      Offender:   [{pid,<0.9630.3>},{id,aten_detector},{mfargs,{aten_detector,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
Also erlang/erts-10.6.1/bin/beam.smp "eats" to much ram
Sorry for my bad english, and i bad in Erlang, so help pls or explain what am i doing wrong

Thank you

**Comment by wglambert** [comment]
You'd want to ask https://www.rabbitmq.com/#community, or https://www.rabbitmq.com/#support who would be more knowledgeable with rabbitmq since these repos are for issues with the Dockerfile

This issue looks to be an exact match of yours https://groups.google.com/forum/#!topic/rabbitmq-users/CNXPvwHpbgQ/discussion

They're also using celery and mentioned memory issues as well

But I'm going to close this since this is an issue with using rabbitmq and not an issue in the way we package it
