### ISSUE TITLE
Permission Denied error if setting config variable RABBITMQ_MNESIA_DIR 

### ISSUE THREAD

**Issue by rewop** [docker-library/rabbitmq#39]
I created a docker file from the image tagged `3.5.4-management`. 

The Dockerfile sets the environment variable `RABBITMQ_MNESIA_DIR` as specified in the [configuration documentation of rabbitmq](https://www.rabbitmq.com/relocate.html). 

```
FROM rabbitmq:3.5.4-management
ENV RABBITMQ_MNESIA_DIR=/data/db
```

When starting a container with the image built, I get a permission error:

```
/usr/lib/rabbitmq/bin/rabbitmq-server: 42: /usr/lib/rabbitmq/bin/rabbitmq-server: cannot create /data/db.pid: Permission denied
```

The reason for me to change mnesia directory is to store the file in a volume folder.

**Comment by rewop** [comment]
It looks like the problem is that the default value for the folder is hard coded in `docker-entrypoint.sh` when setting permission on the folder. https://github.com/docker-library/rabbitmq/blob/master/docker-entrypoint.sh#L59

**Comment by yosifkit** [comment]
That is because is it already declared as a volume: https://github.com/docker-library/rabbitmq/blob/master/Dockerfile#L47.  If you want to use a different directory you'll need to ensure the permissions are correct.  A PR to change the entrypoint could work as well.  Maybe we should set that env in the Dockerfile and use it wherever we currently have `/var/lib/rabbitmq/`.

**Comment by rewop** [comment]
I see. In my case, the directory `/data/db` is a volume added with `--volumes-from` option from a data container. This is quite common with docker to enable easy backup and restore of the volume itself.

Also rabbitmq mechanism to decide where to store the db files is rather complicated. The path can be decided from a set of env variables that can override each other. 

I will work on a PR to fix this, and I would remove the VOLUME directive in the dockerfile to enable more generic cases.

**Comment by yosifkit** [comment]
Closing old issue.  Now, you can use a `docker volume` rather than a "data container" to allow you to map the volume to the correct spot in any container (and it can live beyond the life-cycle of any container).
