### ISSUE TITLE
queues are deleted when docker container is deleted

### ISSUE THREAD

**Issue by kirsazlid** [docker-library/rabbitmq#391]
Hi, there is my docker-compose.yml:
######################
version: '2'
services:
    rabbitmq:
        image: 'rabbitmq:3.7.7-management'
        restart: always
        container_name: 'rabbitmq'
        mem_limit: 1g
        ports:
            - '15673:15672'
        env_file: ./rabbitmq.env
        volumes:
            - '/data/docker/public/rabbitmq/:/var/lib/rabbitmq/'
        network_mode: 'bridge'
#######################
I created some durable queues, then deleted this container: 'docker rm -f rabbitmq', recreated a new container: 'docker-compose up -d rabbitmq', but the previous queues disappeared. Is there something wrong? I've set persistent volume, and the volume data are updated too, but why the queues can not be seen?

**Comment by wglambert** [comment]
If you look in `/data/docker/public/rabbitmq` you'll find multiple `rabbit@[host]` folders as Rabbitmq uses the hostname as part of the folder name

https://github.com/docker-library/rabbitmq/issues/106#issuecomment-241882358
So specifying a hostname with `--hostname` or `hostname: ` in the docker-compose file would resolve that

**Comment by kirsazlid** [comment]
@wglambert Thanks a lot, it works.

**Comment by sureshchoudhay** [comment]
> If you look in `/data/docker/public/rabbitmq` you'll find multiple `rabbit@[host]` folders as Rabbitmq uses the hostname as part of the folder name
> 
> [#106 (comment)](https://github.com/docker-library/rabbitmq/issues/106#issuecomment-241882358)
> So specifying a hostname with `--hostname` or `hostname: ` in the docker-compose file would resolve that

How we can resolve this issue with docker-compose. I have already tried with hostname but still no luck.

**Comment by ronsigter** [comment]
> So specifying a hostname with --hostname or hostname:  in the docker-compose file would resolve that

As mentioned, a `hostname` configuration  is needed to persist the stored data created by `rabbitmq` container. 

Then make sure your queue and messages are set to have a durable and persistent configuration respectively.

example, I'm using [amqp.node](http://www.squaremobius.net/amqp.node/) client for Node,

for queue:

```js
channel.assertQueue('hello', {durable: true});
```

for sending a message

```js
channel.sendToQueue(queue, Buffer.from(msg), {persistent: true});
```


More on [here](https://www.rabbitmq.com/tutorials/tutorial-two-javascript.html#:~:text=Message%20durability) under **Message Durability**
