### ISSUE TITLE
ansible container compatible 

### ISSUE THREAD

**Issue by ronansalmon** [docker-library/rabbitmq#393]
Ansible's rabbitmq modules do not work within a rabbitmq container. This is the error I get: 
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named requests
failed: [xxxx -> rabbitmq] (item=aaaaa) => {"ansible_loop_var": "queue", "changed": false, "msg": "Failed to import the required Python library (requests) on xxxx's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter", "queue": "aaaaa"}
```
But once I installed the missing lib, everything looks good.
So, is it possible to include the python-requests lib in the rabbitmq container ?

Thanks,

**Comment by ronansalmon** [comment]
Forgot to mention that I was using the 3.8 tags

**Comment by tianon** [comment]
If I understand correctly, you're trying to run Ansible *inside* the `rabbitmq` container?  What's the end goal of doing so?

**Comment by yosifkit** [comment]
Since `python-requests` is a python 2 library, https://github.com/docker-library/rabbitmq/pull/394 may be of note, since we are discussing removing `python` and only installing `python3` in upcoming releases.

**Comment by ronansalmon** [comment]
> If I understand correctly, you're trying to run Ansible _inside_ the `rabbitmq` container? What's the end goal of doing so?

The Idea is to be able to use rabbitmq plugins included in ansible. And it works juste fine once the missing lib is installed.

**Comment by tianon** [comment]
Sorry, I would suggest making your own image that installs the necessary libs (short `Dockerfile` that's `FROM rabbitmq:xxx` and then installs what you need).

Using Ansible inside this image is not a common enough use case (AFAIK) for us to support it out-of-the-box.
