### ISSUE TITLE
run as nonRoot

### ISSUE THREAD

**Issue by arminfelder** [docker-library/rabbitmq#396]
for security reasons, the server should run with its user 999 instead of root

**Comment by wglambert** [comment]
https://github.com/docker-library/rabbitmq/issues/380#issuecomment-557321746
What about using `--user` to run as an arbitrary user?

**Comment by arminfelder** [comment]
of course you can run the container in a different security context, but it should be the other way round. 
Default should be an unprivileged user, and only if needed --user root should be used

**Comment by wglambert** [comment]
The processes in the container run as user `rabbitmq`
```console
$ docker run -d --rm --name rabbitmq rabbitmq
bea2eed112a09c4cdcc62e4a21895ea4a2565164d56b16698b14b97aa93b395f

$ docker exec -it rabbitmq bash
root@bea2eed112a0:/# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
rabbitmq      1  0.5  0.0   4624  1796 ?        Ss   17:50   0:00 /bin/sh /opt/rabbitmq/sbin/rabbitmq-ser
rabbitmq    165  0.0  0.0   8272    88 ?        S    17:50   0:00 /usr/local/lib/erlang/erts-10.7/bin/epm
rabbitmq    374 66.7  0.3 5394568 100736 ?      Sl   17:50   0:06 /usr/local/lib/erlang/erts-10.7/bin/bea
rabbitmq    550  4.3  0.0   4516   816 ?        Ss   17:50   0:00 erl_child_setup 1048576
root        605  2.0  0.0  20252  3720 pts/0    Ss   17:50   0:00 bash
rabbitmq    618  0.0  0.0   8260  1212 ?        Ss   17:50   0:00 inet_gethost 4
rabbitmq    619  0.0  0.0  10380  1616 ?        S    17:50   0:00 inet_gethost 4
root        620  0.0  0.0  36148  3324 pts/0    R+   17:50   0:00 ps aux
```

https://github.com/docker-library/rabbitmq/issues/200#issuecomment-336254512
>We strive with all the official images to run as non-root as much as possible, usually only using root just long enough to fix permissions on any directories that matter (especially volumes like /var/lib/rabbitmq), and then step down -- see https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user for more details about that recommendation.

**Comment by arminfelder** [comment]
yes, rabbitmq is run a user rabbit, but docker-entrypoint.sh is not, and as there is no need for using the root user, its better to just don't.

**Comment by tianon** [comment]
This is the only portion of the entrypoint which runs as root: (everything above this portion is variable and function definitions)

https://github.com/docker-library/rabbitmq/blob/0b47a9fb7531f2ffa91f94fb7e2fbbca2ab5cb61/docker-entrypoint.sh#L82-L111

It has to run as root or it cannot `chown` the data directory and the default usage suffers.  As with all security, it's a balance between secure-by-default and usability, and in this case we went as secure as we can get while being easy for folks to use with bring-your-own-storage, making sure it's possible for them to take that security up a notch as their threat model requires (via `--user`, user namespaces, etc) and thus putting the drop in usability associated on their shoulders as well (pre-adjusting the volume / data path ownership).
