### ISSUE TITLE
where is 3.6.x Dockerfile

### ISSUE THREAD

**Issue by huangjiasingle** [docker-library/rabbitmq#398]
l want to build arm image fo version 3.6.9, but l can't find the 3.6.x Dockerfile in this reposistry

**Comment by tianon** [comment]
It was removed in https://github.com/docker-library/rabbitmq/commit/f9791ecb4464ce1e2b39b7ba5ff05bc57c5001d9 / https://github.com/docker-library/rabbitmq/pull/299 (it's been EOL since May 2018).
