### ISSUE TITLE
VOLUME declaration can result in difficult to diagnose misbehavior

### ISSUE THREAD

**Issue by pjk25** [docker-library/rabbitmq#410]
By declaring the VOLUME $RABBITMQ_DATA_DIR in the base Dockerfile, (i.e. https://github.com/docker-library/rabbitmq/blob/91be7cf597c069c9a038ae2619adac1a85e68d4d/3.8/ubuntu/Dockerfile#L257), it ensures that changes to that directory in subsequent Dockerfiles are ignored. This can cause very confusing behavior if, for instance, a user wants to add a specific erlang cookie in a new Dockerfile that inherits from this one. Additionally, if the behavior of `rabbitmq-plugins` were to change such that relies on modifying the data dir, the management Dockerfile would at least partially break.

**Comment by pjk25** [comment]
https://docs.docker.com/engine/reference/builder/#volume
>  If any build steps change the data within the volume after it has been declared, those changes will be discarded.

I also tried redeclaring the VOLUME after making the desired changes, however the behavior remains unchanged:

```Dockerfile
FROM rabbitmq:3.8

RUN echo "test" > ${RABBITMQ_DATA_DIR}/test.txt && cat ${RABBITMQ_DATA_DIR}/test.txt

VOLUME $RABBITMQ_DATA_DIR
```

```bash
docker build . -t dvdt
docker run --rm -it dvdt /bin/cat /var/lib/rabbitmq/test.txt
```

which prints
```bash
/bin/cat: /var/lib/rabbitmq/test.txt: No such file or directory
```
So, I believe the only available solution is to drop the VOLUME declaration from the Dockerfile.

**Comment by wglambert** [comment]
Other discussions on removing inherent volumes in images https://github.com/docker-library/mongo/issues/306, https://github.com/docker-library/redis/issues/140, https://github.com/docker-library/postgres/issues/404, https://github.com/docker-library/mysql/issues/255

https://github.com/docker-library/cassandra/issues/180#issuecomment-497862906
>While I agree it's unfortunate Docker doesn't have a feature to disable inherited volumes, I really hesitate to add extra explicit variants that then need to be maintained to support this.

**Comment by pjk25** [comment]
I'd like to propose https://github.com/docker-library/rabbitmq/pull/416 as a solution with minimal maintenance overhead.

**Comment by edvinkuric** [comment]
Yeah, that is a known issue: https://github.com/moby/moby/issues/3639

i always had to replace the volume-command manually in a fork of that image
