### ISSUE TITLE
No URL for the helm chart source in the README

### ISSUE THREAD

**Issue by subos2008** [docker-library/rabbitmq#414]
I realise this is in slightly the wrong place but I'm trying to find the source code for the `rabbitmq-ha` chart and I seem to be unable to find it.

Where is it? I'm happy to make a PR to link back from the package README to the source location.

https://hub.helm.sh/charts/stable/rabbitmq-ha

**Comment by wglambert** [comment]
I see we're listed as "related" at https://hub.helm.sh/charts/stable/rabbitmq-ha but we're not affiliated, You'd have to ask the maintainer of that chart https://github.com/steven-sheehy

**Comment by tianon** [comment]
I think it lives in https://github.com/helm/charts/tree/master/stable/rabbitmq-ha (but as mentioned, we're unaffiliated).
