### ISSUE TITLE
Unable to start RabbitMQ 3-management image on docker

### ISSUE THREAD

**Issue by BLaZeKiLL** [docker-library/rabbitmq#417]
I recently changed my docker backend to wsl2 and when i am trying to start rabbitmq 3 management using the command

> docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management --restart=always

the container exits immediately and in the logs i see this

>  /usr/local/bin/docker-entrypoint.sh: line 405: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]

**Comment by wglambert** [comment]
Docker run's usage is `docker run [OPTIONS] IMAGE [COMMAND] [ARG...]` so the `--restart=always` option is invalid in the `COMMAND` section as that gets interpreted by the entrypoint (which errors `line 405: exec: --: invalid option`) 

We have a few examples in the docs https://github.com/docker-library/docs/tree/master/rabbitmq#running-the-daemon

**Comment by yosifkit** [comment]
```diff
- docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management --restart=always
+ docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 --restart=always rabbitmq:3-management
