### ISSUE TITLE
*-management flavors were not automatically rebuilt for 3.8.5

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#418]
I can't know what happened but the `*-management` versions of this image [were not rebuilt for 3.8.5](https://github.com/docker-library/rabbitmq/tree/master/3.8/ubuntu) the same way the core image was.

Are my expectations incorrect or should all versions/tags be rebuilt when a new RabbitMQ, Erlang or OpenSSL version is released?

**Comment by yosifkit** [comment]
While the contents of the file haven't changed, the management image is `FROM rabbitmq:3.8`, so it'll get rebuild anytime `rabbitmq:3.8` changes.

**Comment by michaelklishin** [comment]
Makes sense, thank you for explaining something so obvious to me :)
