### ISSUE TITLE
Rabitmq management container starts earlier then plugin is on

### ISSUE THREAD

**Issue by ddosia** [docker-library/rabbitmq#43]
I use HTTP api provided by management plugin to create exchange upon container start.
If *curl* is used immediately after `docker run...` then *curl* always fails to define this exchange, but if I repeat the same command after few seconds it will succeed.
Currently I wrote some logic to repeat requests but it would be great if container will be considered as started only when this plugin has been started.

**Comment by ddosia** [comment]
I repeat cur command each 3 seconds, 3 first time it fails then it succeeds.
```shell
curl: (56) Failure when receiving data from the peer
curl: (52) Empty reply from server
curl: (52) Empty reply from server
HTTP/1.1 204 No Content
```

**Comment by tianon** [comment]
Docker doesn't have a way for us to delay the container "started" event until the service is available, so unfortunately the "retry" logic you've mentioned is your best and only option currently (and is the same problem we have in all the "database" images).

**Comment by chippawah** [comment]
@ddosia could you share the script you're using to check the sever response? I'm trying to get around the same problem now.
