### ISSUE TITLE
When I use the docker image to start rabbitmq, it starts normally. But when I log in, this error occurs. What is the problem?header,<<"authorization">>

### ISSUE THREAD

**Issue by axj52520** [docker-library/rabbitmq#433]
![image](https://user-images.githubusercontent.com/23573022/90879473-8ced6d00-e3d9-11ea-9c24-b0042a1bfe43.png)
[](url)

 [{initial_call,{cowboy_stream_h,request_process,['Argument__1','Argument__2','Argument__3']}},{pid,<0.942.0>},{registered_name,[]},{error_info,{exit,{{request_error,{header,<<"authorization">>},'Malformed header. Please consult the relevant specification.'},[]},[]}},{ancestors,[<0.941.0>,<0.737.0>,<0.736.0>,rabbit_web_dispatch_sup,<0.725.0>]},{message_queue_len,0},{messages,[]},{links,[<0.941.0>]},{dictionary,[]},{trap_exit,false},{status,running},{heap_size,4185},{stack_size,28},{reductions,4590}], []
2020-08-21T10:06:29.306748173Z 2020-08-21 10:06:29.306 [error] <0.942.0> CRASH REPORT Process <0.942.0> with 0 neighbours exited with reason: {{{request_error,{header,<<"authorization">>},'Malformed header. Please consult the relevant specification.'},[]},[]}

**Comment by michaelklishin** [comment]
@axj52520 I'd start by taking a traffic capture to see what the header value really is. The header is sent by an HTTP API client (could be a Web browser, a tool such as `curl` or any other client). Then track down the client that sends it.

**Comment by axj52520** [comment]
> @axj52520 I'd start by taking a traffic capture to see what the header value really is. The header is sent by an HTTP API client (could be a Web browser, a tool such as `curl` or any other client). Then track down the client that sends it.

Thank you for your answers and ideas. I know the problem. It may be due to the specified host name when I use docker to build the image. I must use this host to access the server MQ to be recognized. If I directly use the IP access of the virtual host, the authorization value is null. When I modify the host of the local machine and add a virtual domain name to map to the server IP, access 1 5672 log in, and the value of authorization will be passed. But this error, without any error prompt, is not friendly enough, I think.
![image](https://user-images.githubusercontent.com/23573022/91111287-bb599980-e6b2-11ea-9537-cb7ea1a54710.png)

**Comment by axj52520** [comment]
The final reason for this problem is that the host name attribute is set. When accessing, the host name is not used to access, resulting in the problem of login permissions.

**Comment by axj52520** [comment]
> I'm not able to reproduce
> 
>  docker run
> ![image](https://user-images.githubusercontent.com/26428991/90899707-29cded00-e37d-11ea-80d5-8030818bfd84.png)
> 
> Maybe your image is corrupted, you could try removing it and re-pulling
> Anything special about your Docker host?

You are right. It is really the permission problem caused by the setting of the hostname property.

**Comment by axj52520** [comment]
> @axj52520 I'd start by taking a traffic capture to see what the header value really is. The header is sent by an HTTP API client (could be a Web browser, a tool such as `curl` or any other client). Then track down the client that sends it.

But why can't the management webpage use the server's IP to log in after the docker has set the host name? Permission header acquisition is null..
