### ISSUE TITLE
Issue with self signed certificates

### ISSUE THREAD

**Issue by kushal-nt** [docker-library/rabbitmq#437]
I am facing an SSL connection issue with latest 3.8.8-management image. This is only when I use self-signed certificates (generated as per https://www.rabbitmq.com/ssl.html#automated-certificate-generation). With third party valid certificates, it is working perfectly fine. 

Here are the steps followed to reproduce this on debian 10.

1. Install docker and generate self signed certs.
2. Run official rabbit management image with command: 
`docker run --rm --network host -e RABBITMQ_MANAGEMENT_SSL_CACERTFILE=/var/lib/rabbitmq/ca_certificate.pem -e RABBITMQ_MANAGEMENT_SSL_CERTFILE=/var/lib/rabbitmq/server_certificate.pem -e RABBITMQ_MANAGEMENT_SSL_KEYFILE=/var/lib/rabbitmq/server_key.pem -e RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT=false -e RABBITMQ_MANAGEMENT_SSL_VERIFY=verify_none -v /opt/tls-gen/basic/result/:/var/lib/rabbitmq/ --name rabbitmq rabbitmq:3.8.8-management`
3. After this, failed to connect to management portal  at 15671 port.
4. Getting exception while executing:  `openssl s_client -connect localhost:15671`

```
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 283 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

```
I have verified that certs are ok using steps mentioned at https://www.rabbitmq.com/troubleshooting-ssl.html#openssl-tools.

This used to work for me in 3.7 version and it still works with third party valid certs. Is there anything I am missing here or is it a some issue?

**Comment by michaelklishin** [comment]
There is a dedicated guide on [Troubleshooting TLS](https://www.rabbitmq.com/troubleshooting-ssl.html). Self-signed certificates used by the server [must be trusted](https://www.rabbitmq.com/ssl.html#peer-verification) on all client hosts (this includes any hosts that access the management UI). This is not specific to this image.

**Comment by michaelklishin** [comment]
Perhaps this [section on trusted certificates](https://www.rabbitmq.com/ssl.html#peer-verification-trusted-certificates) would make more sense since in this example, peer verification for HTTP API clients has been disabled.

**Comment by michaelklishin** [comment]
Actually [write error 104](https://security.stackexchange.com/questions/158104/testing-tls-with-openssl#:~:text=In%20fact%2C%20errno%20104%20is,client%20and%20server%20blocking%20access.) for `s_client` seems to be an indication of `ECONNRESET`, which is fancy speak for "TCP connection was refused". It doesn't get to performing any TLS handshake, you have problems with TCP connectivity it seems.

**Comment by michaelklishin** [comment]
…and there's a separate guide for [narrowing down connectivity issues](https://www.rabbitmq.com/troubleshooting-networking.html).

**Comment by kushal-nt** [comment]
Thansk @michaelklishin for your response.

I have gone through these documents multiple times and tried many of things mentioned. I can confirm that connections are working on 5672 and 15672 ports when enabled.

I have followed steps mentioned at this [link](https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list) to add self signed ca cert to client host's /etc/ssl/certs  as well.  

Also tried by setting peer verification to verify_peer and then with command like to get same output below:  `openssl s_client -connect localhost:15671 -cert server_certificate.pem -key server_key.pem -CAfile ca_certificate.pem -state`

```
CONNECTED(00000003)
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hello
SSL_connect:error in SSLv3/TLS write client hello
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 283 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```
Also inside the docker, when I go to bash and execute  `rabbitmq-diagnostics listeners`, it returns me an entry with `Interface: [::], port: 15671, protocol: https, purpose: HTTP API over TLS (HTTPS)`

Can you please tell if there is anything specific I need to check here.

**Comment by michaelklishin** [comment]
@kushal-nt `write:errno=104` means `s_client` failed to connect to the target host on port 15671. It did not get to perform a TLS upgrade. You need to figure out why inbound TCP connections on that port are rejected by the container.

**Comment by kushal-nt** [comment]
I managed to solve it by simply changing the permissions of all three cert files to 666. 

Hope this information would come useful for someone else.
