### ISSUE TITLE
Can't view management web interface

### ISSUE THREAD

**Issue by amracel** [docker-library/rabbitmq#45]
I'm following the directions as given and cannot view the management interface. I did try to start the management interface within docker-compose, but have switched back to the command line until I can get this to work.

Steps to reproduce:

from the command line:
docker run -d --hostname vrabbit --name rabbit-mgt rabbitmq:3-management

confirm instance running:
docker ps

determine ip of instance:
docker inspect --format='{{.NetworkSettings.IPAddress}}' rabbit-mgt

open website:
http://[discovered url]:15672

Getting no response.

Using the following when trying to do it from docker-compose:

Dockerfile:
FROM rabbitmq:3-management
ENV RABBITMQ_DEFAULT_USER=vuser
ENV RABBITMQ_DEFAULT_PASS=[vuser passowrd]
LABEL hostname=vrabbit

docker-compose.yml:
rabbitadmin:
  build: rabbit-mgt
  links: 
    - rabbitmq
  container_name: rabbit-mgt

**Comment by yosifkit** [comment]
I can't seem to reproduce.  Are you on a Mac?  You cannot access the container ip directly on a Mac, since it is internal to the virtual machine.  You'll need to add a `-p 15672:15672` to the docker run (and to the compose yaml) and then access it by going to the address of the VM:15672.

**Comment by amracel** [comment]
Yes, I see. I tried it on the ubuntu server and had no problem.

But I added the port mapping and still couldn't get to the web interface on Mac (docker machine).

**Comment by yosifkit** [comment]
You used `docker-machine ip insert-vm-name` for the address?

**Comment by grantila** [comment]
@amracel you need to either export all ports to random ports on the host using `-P` or forward all ports to the host manually with `-p 4369:4369 -p 5672:5672 -p 15672:15672 -p 25672:25672`.

**Comment by yunghoy** [comment]
docker exec [CONTAINER_NAME] rabbitmq-plugins enable rabbitmq_management

**Comment by beyerz** [comment]
I am having the same issue.
Could it possibly be that the port is not exposed on line 81? 
In the docker file the ports being exposed are:
````
EXPOSE 4369 5671 5672 25672
````

You will notice that 15672 is not exposed as is mentioned in the docs...

**Comment by michaellihs** [comment]
Here is a slightly more comfortable solution for @yunghoy 's proposal:

```sh
rmq_container_id=$(docker run -d -p 5672:5672 -p 15672:15672 rabbitmq) && sleep 5 && docker exec $rmq_container_id rabbitmq-plugins enable rabbitmq_management
```

Depending on the startup time of the container, you maybe have to increase the `sleep` value :-)

Thx @yunghoy - you helped me a lot!

**Comment by philipschwarz** [comment]
Thank you @yunghoy - you also helped me a lot!

**Comment by tianon** [comment]
I'm going to close since this appears to be working properly. :+1:

**Comment by hasmo** [comment]
Worked for me too. Cheers.

**Comment by mr-moon** [comment]
```
docker exec 5e199f66a1ef rabbitmq-plugins enable rabbitmq_management
Plugin configuration unchanged.

Applying plugin configuration to rabbit@rabbitmq... nothing to do.
```

Can't view on `rabbitmq:3.6-management`

**Comment by bhgames** [comment]
Isnt this supposed to run by default with -management?

**Comment by yosifkit** [comment]
@bhgames, yup it does.  I figure it was mostly a networking issue to access the container that was running on the `docker-machine` created VM.  If a user is still using `docker-toolbox` (which uses `docker-machine`, Oracle VirtualBox, and boot2docker), in order to access rabbit from the Mac/Windows host one must do the following: run the container with the equivalent of `-p 15672:15672`; and access it through the IP address of the virtual machine on port `15672`.  The IP address can be found by running `docker-machine ip default`.

If users are now using Docker for Mac or Docker for Windows, they would only need to run the container with the equivalent of `-p 15672:15672` and then they can access the container via `http://localhost:15672`. While Docker for Mac/Windows still uses a Linux VM, it papers over the details of needing to hit the IP of the VM.

------------------------------

Logs definitely show that management plugin is being started:

```console
$ docker run -it --rm  --hostname vrabbit --name rabbit-mgt rabbitmq:3.6-management
/***** cutting logs to show relevant bits *****/

=INFO REPORT==== 27-Oct-2017::22:07:48 ===
started TCP Listener on [::]:5672

=INFO REPORT==== 27-Oct-2017::22:07:48 ===
Management plugin started. Port: 15672

=INFO REPORT==== 27-Oct-2017::22:07:48 ===
Statistics database started.
 completed with 6 plugins.

=INFO REPORT==== 27-Oct-2017::22:07:48 ===
Server startup complete; 6 plugins started.
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_web_dispatch
 * amqp_client
 * cowboy
 * cowlib
```

Compare to the startup of the non `-management` image:

```console
$ docker run -it --rm  --hostname vrabbit --name rabbit-mgt rabbitmq:3.6
/***** cutting logs to show relevant bits *****/

=INFO REPORT==== 27-Oct-2017::22:07:22 ===
started TCP Listener on [::]:5672
 completed with 0 plugins.

=INFO REPORT==== 27-Oct-2017::22:07:22 ===
Server startup complete; 0 plugins started.
```

**Comment by bhgames** [comment]
See the thing is I was using this on an ECS cluster, and I mounted an EFS volume so that when the image dies, it can startup again and still have the same data. It did not come with management running -  I had to shell in and enable it. After that it stuck. Makes it very annoying to deploy new ecs clusters - I have to go in and enable the management manually until I can find a better work around.

**Comment by yosifkit** [comment]
@bhgames, are you perhaps mounting in a custom `/etc/rabbitmq/enabled_plugins`? As far as I see, that is the only functional difference between the image `rabbitmq:3.6` and `rabbitmq:3.6-management` (aside from the metadata involving exposed ports).

Running management from the regular image:

```console
$ docker run -d  --hostname vrabbit --name rabbit -p 15672:15672 rabbitmq:3.6
$ docker diff rabbit
C /etc
C /etc/rabbitmq
A /etc/rabbitmq/rabbitmq.config
$ docker exec -it rabbit cat /etc/rabbitmq/rabbitmq.config
[ { rabbit, [
	{ loopback_users, [ ] },
	{ tcp_listeners, [ 5672 ] },
	{ ssl_listeners, [ ] },
	{ hipe_compile, false }
] } ].
$ docker exec -it rabbit rabbitmq-plugins enable rabbitmq_management
The following plugins have been enabled:
  amqp_client
  cowlib
  cowboy
  rabbitmq_web_dispatch
  rabbitmq_management_agent
  rabbitmq_management

Applying plugin configuration to rabbit@vrabbit... started 6 plugins.
$ docker diff rabbit
C /etc
C /etc/rabbitmq
A /etc/rabbitmq/rabbitmq.config
A /etc/rabbitmq/enabled_plugins
$ docker exec -it rabbit cat /etc/rabbitmq/rabbitmq.config 
[ { rabbit, [
	{ loopback_users, [ ] },
	{ tcp_listeners, [ 5672 ] },
	{ ssl_listeners, [ ] },
	{ hipe_compile, false }
] } ].
$ docker exec -it rabbit cat /etc/rabbitmq/enabled_plugins
[rabbitmq_management].
```

Running using the `-management` image:

```console
$ docker run -d  --hostname vrabbit --name rabbit-mgt -p 15672:15672 rabbitmq:3.6-management
$ docker diff rabbit-mgt
C /etc
C /etc/rabbitmq
A /etc/rabbitmq/rabbitmq.config
$ docker exec -it rabbit-mgt cat /etc/rabbitmq/rabbitmq.config
[
	{ rabbit, [
		{ loopback_users, [ ] },
		{ tcp_listeners, [ 5672 ] },
		{ ssl_listeners, [ ] },
		{ hipe_compile, false }
	] },
	{ rabbitmq_management, [ { listener, [
		{ port, 15672 },
		{ ssl, false }
	] } ] }
].
$ docker exec -it rabbit-mgt cat /etc/rabbitmq/enabled_plugins
[rabbitmq_management].
```

In either case, the site is available at `http://{ip-address}:15672`. It seems that the config for `rabbitmq_management` in `rabbitmq.config` is unnecessary for the default port and no ssl.

**Comment by bhgames** [comment]
So I think the issue is I am mounting an EFS volume for the /etc/rabbitmq dirs and other dirs related to data, so i can kill the container but keep the state. I need to make sure the EFS volume has that file setup before the container is launched.

**Comment by kalkrishnan** [comment]
This is not working for me. I ran the below command on docker for windows to run the container:

docker run -d -p 5672:5672 -p 15672:15672 --hostname rabbit-server1 --name rabbit1 rabbitmq:3-management

docker logs rabbit1 show me that the server has started with the management plugin.

I even exposed the port in virtualbox:

![image](https://user-images.githubusercontent.com/6913583/39774142-e2246b16-52ae-11e8-8812-9e72736ebb43.png)

But when I try to access localhost:15672 or 172.17.0.2:15672(The Ip of the container), the url just times out and nothing happens.

**Comment by cristobalito** [comment]
> @bhgames, yup it does. I figure it was mostly a networking issue to access the container that was running on the `docker-machine` created VM. If a user is still using `docker-toolbox` (which uses `docker-machine`, Oracle VirtualBox, and boot2docker), in order to access rabbit from the Mac/Windows host one must do the following: run the container with the equivalent of `-p 15672:15672`; and access it through the IP address of the virtual machine on port `15672`. The IP address can be found by running `docker-machine ip default`.
> 
> If users are now using Docker for Mac or Docker for Windows, they would only need to run the container with the equivalent of `-p 15672:15672` and then they can access the container via `http://localhost:15672`. While Docker for Mac/Windows still uses a Linux VM, it papers over the details of needing to hit the IP of the VM.

Just to follow up on this issue, as it's the most useful place I got to while googling. I get the behaviour described by others if I try to run one of the management images, but if I follow @yunghoy's suggestion it works fine. 

Therefore, there does appear to be an issue with the management related images.
