### ISSUE TITLE
rabbit_set_config can break rabbitmq.conf by omitting important new lines

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#456]
See this [RabbitMQ repository discussion](https://github.com/rabbitmq/rabbitmq-server/discussions/2700). It looks like the `rabbit_set_config` function should make sure it prepends a newline character to every line it generates. Extra newlines won't hurt but missing newlines can produce an incorrect config file and cause a fair amount of confusion.

Of course, it would be best if this image did not mess with the `rabbitmq.conf` and retired all environment variable-based configuration values possible but we've had this conversation in #440 and #424 :)

**Comment by tianon** [comment]
Doh, yep - I bet the reproducer is to have a `rabbitmq.conf` that's missing a trailing newline and the container try to set an option that doesn't exist, which will append to the file. :sweat_smile:

(Yes, I'd really love to resolve #424 :grimacing:)
