### ISSUE TITLE
error: clock_gettime(CLOCK_MONOTONIC, _) failed...

### ISSUE THREAD

**Issue by RabAusten** [docker-library/rabbitmq#462]
### Error message
clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
Aborted

### Images tested
- management-alpine - 10381e618175 (Fails)
- 3.8.11-management-alpine - 10381e618175 (Fails)
- 3.8.11-management-alpine - 9cd111ed5fd6 (No issue) 
- 3.8.10-management-alpine - 0ca1be2c737f (No issue)

>REPOSITORY | TAG | IMAGE ID | CREATED | SIZE
>rabbitmq | 3.8.11-management-alpine  | 10381e618175 | 5 days ago | 124MB
>rabbitmq | management-alpine | 10381e618175 | 5 days ago  | 124MB
>rabbitmq | 3.8.10-management-alpine | 0ca1be2c737f  | 2 weeks ago | 130MB

### System details
- Raspberry Pi 3 w/ latest Raspberry Pi OS Lite (Buster) 32 Bit
- Raspberry Pi 4 w/ latest Raspberry Pi OS Full Desktop (Buster) 32 Bit

### Docker version
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:57 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:57 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Comment
I have been running 3.8.11-management-alpine on a Raspberry Pi 4 using an image created 2 weeks ago
>REPOSITORY | TAG | IMAGE ID | CREATED  | SIZE
> rabbitmq  | management-alpine | 9cd111ed5fd6 | 2 weeks ago  | 130MB
Pulling the latest version of the image (10381e618175) on the same setup, reproduces the error.

I have reverted to 3.8.10-management-alpine for my current needs.

Thanks
James

**Comment by tianon** [comment]
This sounds like it's probably https://github.com/alpinelinux/docker-alpine/issues/135; see also https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements.

> You need to update libseccomp on your host to 2.4.2 or newer and Docker to 19.03.9 or newer (see moby/moby#40734).
