### ISSUE TITLE
RabbitMQ docker image takes more time to start when using home dir in an EFS mount

### ISSUE THREAD

**Issue by rahulsadanandan** [docker-library/rabbitmq#463]
**Describe the bug**
RabbitMQ Docker image takes a long time to start (5- 10 minutes) when using an efs mount as home directory location(/var/lib/rabbitmq).

**To Reproduce**

1. Create an efs file system
2. Create an ec2 instance mounting the efs file system to a path (/mnt/efs/fs1)
3. Run without using an efs mount
`docker run --hostname my-rabbit --name some-rabbit rabbitmq:3.8.11`
Starts normally. logs attached with `log.file.level = debug` 
[without_efs.log](https://github.com/docker-library/rabbitmq/files/5950275/without_efs.log)

4. Run using an efs mount for home dir
docker run -v /mnt/efs/fs1:/var/lib/rabbitmq --hostname my-rabbit --name some-rabbit rabbitmq:3.8.11
Takes longer time to start. logs attached with `log.file.level = debug` 
 #[efs.log](https://github.com/docker-library/rabbitmq/files/5950294/efs.log)

**Additional Information**
This is also reproducible in Kubernetes (using bitnami rabbitmq chart) .

#https://github.com/bitnami/charts/issues/4936

**Comment by wglambert** [comment]
The bitnami chart/image isn't derived from this image https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.8/debian-10/Dockerfile

The discussion in that thread is pretty informative for troubleshooting the issue, notably https://github.com/bitnami/charts/issues/4936#issuecomment-767466323 and michaelklishin's comment about using `strace`. So I'm not sure if there's anything more we can add to that in a separate thread here.

**Comment by rahulsadanandan** [comment]
@michaelklishin @wglambert 
This issue happens for the official image of rabbitmq (https://hub.docker.com/_/rabbitmq) 

I did use the debug and strace and here are my findings. please have a look when you have some time


while its stuck for 7 minutes at 
```bash
[root@ip-172-31-27-174 fs1]# docker run --cap-add SYS_PTRACE -v /mnt/efs/fs1:/var/lib/rabbitmq -v /mnt/efs/fs1/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf --hostname my-rabbit --name some-rabbit rabbitmq:3.8.11
Unable to find image 'rabbitmq:3.8.11' locally
3.8.11: Pulling from library/rabbitmq
d519e2592276: Pull complete
d22d2dfcfa9c: Pull complete
b3afe92c540b: Pull complete
cd4e41ce9500: Pull complete
e2741828ce46: Extracting [=======================================>           ]  25.56MB/32.73MB
e2741828ce46: Pull complete
6cf1935b659a: Pull complete
3df71d67553c: Pull complete
ac4f52d15541: Pull complete
0af823fd61c8: Pull complete
85579530757b: Pull complete
Digest: sha256:52e73c649b3ef628fb2b0dafd5b043c0b397bd188a0326a6514d37662d84b425
Status: Downloaded newer image for rabbitmq:3.8.11
Configuring logger redirection
```

Strace outputs

```bash
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
rabbitmq     1  0.2  0.0   4636   888 ?        Ss   03:55   0:00 /bin/sh /opt/rabbitmq/sbin/rabbitmq-server
rabbitmq    16  2.7  4.9 1686864 50052 ?       Sl   03:55   0:02 /usr/local/lib/erlang/erts-11.1.7/bin/beam.smp -W w -MBas ageffcbf -MHas ageffcbf -MBlmbcs 512 -MHlmbcs 512 -MMmcs 30 -P 1048576
rabbitmq    23  0.0  0.0   4528   880 ?        Ss   03:55   0:00 erl_child_setup 1024
rabbitmq    48  0.0  0.0   8280    88 ?        S    03:55   0:00 /usr/local/lib/erlang/erts-11.1.7/bin/epmd -daemon
rabbitmq    68  0.0  0.1   8272  1180 ?        Ss   03:55   0:00 inet_gethost 4
rabbitmq    69  0.0  0.1  10392  1716 ?        S    03:55   0:00 inet_gethost 4
root        70  0.5  0.3  20264  3840 pts/0    Ss   03:56   0:00 bash
root       330  0.0  0.3  36160  3284 pts/0    R+   03:57   0:00 ps -aux


root@my-rabbit:/# strace -p 1
strace: Process 1 attached
rt_sigsuspend([], 8


root@my-rabbit:/# strace -p 16
strace: Process 16 attached
select(0, NULL, NULL, NULL, NULL


root@my-rabbit:/# strace -p 23
strace: Process 23 attached
select(5, [3 4], NULL, NULL, NULL


root@my-rabbit:/# strace -p 48
strace: Process 48 attached
select(7, [3 4 5], NULL, NULL, {tv_sec=0, tv_usec=147862}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}) = 0 (Timeout)
select(7, [3 4 5], NULL, NULL, {tv_sec=5, tv_usec=0}
```

cc @chukka @eldada

**Comment by yosifkit** [comment]
Sounds similar to https://github.com/helm/charts/issues/1711 (so EFS is just NFS behind the scenes?).

Although about elasticsearch, [this post](https://www.elastic.co/guide/en/elasticsearch/plugins/master/cloud-aws-best-practices.html) seems relevant since RabbitMQ likely also cares about filesystem performance:

>EFS-based storage is not recommended or supported as it does not offer satisfactory performance. Historically, shared network filesystems such as EFS have not always offered precisely the behaviour that Elasticsearch requires of its filesystem

**Comment by debu99** [comment]
I have the same issue with rabbitmq:latest
