### ISSUE TITLE
management image variants does not support rabbitmq plugins packaged as directories

### ISSUE THREAD

**Issue by pjk25** [docker-library/rabbitmq#466]
https://github.com/rabbitmq/rabbitmq-server/commit/25f45fc59b0e63b376c7091321c82b38b5c29317 has changed the default for packaging rabbitmq's included plugins - they are no longer compressed files, and instead are expanded directories. This breaks the `-management` images who expect to perform the extraction.

See https://github.com/rabbitmq/rabbitmq-server/pull/2838 for one solution.

**Comment by yosifkit** [comment]
Thanks for the heads up! Working on a PR now.
