### ISSUE TITLE
Can't run rabbitmq:management-alpine  on  macbook  m1 cpu

### ISSUE THREAD

**Issue by Johnandfu** [docker-library/rabbitmq#478]
it can't start in macbook  with m1 cpu，When I get into shell  operation rabbitmq-server, it's normal！

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by Johnandfu** [comment]
> Can you give all the commands you ran and any relevant files or logs for reproducing the issue

this no logs, where i run in docker for windows ,it's start up ,but i run in macbook with m1 cpu ,i must run docker-compose exec rabbitmq sh ,then input rabbit-server,it can start up

**Comment by wglambert** [comment]
There's nothing in `docker logs` for the error?

I'd try asking or searching over at the [Docker for Mac](https://github.com/docker/for-mac/issues) repo

**Comment by Johnandfu** [comment]
> There's nothing in `docker logs` for the error?
> 
> I'd try asking or searching over at the [Docker for Mac](https://github.com/docker/for-mac/issues) repo
thinks，I use in laradock，when I delete  privileged: true from docker-compose.yal,it start up now.

**Comment by Johnandfu** [comment]
> There's nothing in `docker logs` for the error?
> 
> I'd try asking or searching over at the [Docker for Mac](https://github.com/docker/for-mac/issues) repo

thinks，I use in laradock，when I delete privileged: true from docker-compose.yal,it start up now.

**Comment by wglambert** [comment]
Cool, closing since this is resolved then
