### ISSUE TITLE
Heads up: Erlang 24 is released

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#483]
This is not an issue but a heads-up: Erlang 24 has [shipped earlier today](https://blog.erlang.org/My-OTP-24-Highlights/). RabbitMQ `3.8.16` [supports it already](https://blog.rabbitmq.com/posts/2021/03/erlang-24-support-roadmap/).

Our tests revealed no issues beyond fairly obscure Erlang tooling incompatibility with Erlang 24 (e.g. Looking Glass). Those
obviously will take some time to be addressed across the ecosystem.

Erlang 24 provides substantial (usually double digit %) throughput gains for many RabbitMQ workloads, so we expect
its adoption in this image will become a commonly requested thing.

I don't know if this image's build system automatically bumps major Erlang versions (@gerhard) but it likely does not.
Therefore we need to decide when to make the switch. Some members of the core team suggested late June when
24.0 becomes `24.0.2` or something similar.

**Comment by tianon** [comment]
It does auto-bump, but it's tied to a fixed major:

https://github.com/docker-library/rabbitmq/blob/e62f193dfcf9aee378e256cbbfae30363480c3a7/versions.sh#L4-L7

Happy to bump that whenever y'all deem it appropriate/sane to do so. :smile:

**Comment by michaelklishin** [comment]
@tianon we don't see a lot of things reported for Erlang 24.0.1, so I think we can bump
