### ISSUE TITLE
Builds and tags for 3.9 betas

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#491]
Hey folks 👋.

Team RabbitMQ is going to ship `3.9.0-beta.1` quite soon. It would be great to have a community image tag with this version.
Right now separate builds and tags are produced for RCs but not betas. Do you think we can extend this to betas?
Would this be too problematic in terms of maintenance?

Not every RabbitMQ release has betas, sometimes we go straight to RCs. But in this case it would be a huge service to the community if betas were available in this Docker image 🤓💪😍

**Comment by yosifkit** [comment]
No maintenance problem adding it. The version scraping code already looks for beta's :+1:  which is how we already have the `3.8.18-beta.1` image (https://github.com/docker-library/official-images/pull/10358). So I think we just need a tag to exist with the `generic-unix` tar file  and we can update #467.

https://github.com/docker-library/rabbitmq/blob/8942a4b61ef703ebb423ed969d6d5102a96d8eca/versions.sh#L35

**Comment by michaelklishin** [comment]
Ah, perfect. Nothing specific to betas to do then 👍
