### ISSUE TITLE
Base Erlang Docker Image - Request

### ISSUE THREAD

**Issue by vovimayhem** [docker-library/rabbitmq#50]
Hi guys (Long time, no see!)

It would be awesome for this project to use an official Erlang docker image as a starting point.

Do you guys know if there's a current effort on an "official" Erlang image at the docker hub? Where do I join? :)

**Comment by tianon** [comment]
You should probably check out https://github.com/docker-library/official-images/pull/1075. :smile:

**Comment by vovimayhem** [comment]
Got it :)
