### ISSUE TITLE
Please provide linux/arm64/v8 images

### ISSUE THREAD

**Issue by pse-sonic** [docker-library/rabbitmq#507]
Hi,

because there is no support for linux/arm64/v8 for all RabbitMQ releases since 3.8.17, I'm unable to run the latest RabbitMQ 3.9.0 on my Apple Macbook with M1 processor.

It would be nice if someone can fix the the build job 🥰 

Best regards

**Comment by wglambert** [comment]
The builds have been failing with:
```
checking for m4... m4
configure: error: JIT only works on x86 64-bit
ERROR: /usr/local/src/otp-24.0.4/erts/configure failed!`
```
https://github.com/erlang/otp/pull/4869
