### ISSUE TITLE
Whitelist a small number of env variables used to seed essential node data (new in RabbitMQ 3.9.4)

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#513]
In https://github.com/docker-library/rabbitmq/issues/508, RabbitMQ maintainers agreed to support a small number of environment variables that would make node seeding convenient in certain environments (such as ECS or service containers used by GitHub, GitLab and so on). This should ship in `3.9.4` https://github.com/rabbitmq/rabbitmq-server/pull/3299.

However, since the entrypoint of this image now (#467) black lists most previously supported env variables. We should whitelist
the [four agreed on in #508](https://github.com/docker-library/rabbitmq/issues/508#issuecomment-895109429) so that they are allowed and propagated to RabbitMQ nodes.

That should make it easier to use this image in more environments without introducing any entrypoint complexity (or undoing any important changes from #467).

@tianon @yosifkit does this sound reasonable to you?

**Comment by tianon** [comment]
We're happy with whatever y'all want to support -- unblacklisting those four should just be a matter of removing them from the entrypoint's array. :smile: :+1:
