### ISSUE TITLE
Please mention RABBITMQ_DEFAULT_USER / RABBITMQ_DEFAULT_PASS in the Readme

### ISSUE THREAD

**Issue by klamann** [docker-library/rabbitmq#526]
I just stumbled upon #508 after I tried to figure out how I can provide a username and password to RabbitMQ 3.9 in a GitLab CI pipeline.

So the Readme says that the use of environment variables to configure RabbitMQ is not possible anymore, but then in [rabbitmq-server#3299](https://github.com/rabbitmq/rabbitmq-server/pull/3299), support for the variables `RABBITMQ_DEFAULT_VHOST`, `RABBITMQ_DEFAULT_USER` and `RABBITMQ_DEFAULT_PASS` was added.

Can you mention this in the Readme on Dockerhub? There are quite a few situations (like GitHub Actions or GitLab CI) where mounting config files is not an option and it would be nice if the Readme helped with that.

**Comment by klamann** [comment]
yeah, it's not in the offcial documentation, would be nice if it was updated. 
But there's basically two pieces of information I'm looking for in the Readme of any docker image:

- which tag should I use?
- how can I specify credentials?

The current Readme does a really good job with the tags, but there is no information to be found regarding credentials, other than a link to a convoluted page which tells you (incorrectly) that the only way to change the password is to mount a config file.

I think it would be very helpful to mention these 3 variables in the Readme.

**Comment by michaelklishin** [comment]
FIY: https://github.com/rabbitmq/rabbitmq-website/commit/ec238a221e7fc7bf83d0f5f267e4f1fbff773b04. RabbitMQ docs are open source, so changes similar to the above one can be contributed by anyone ;)

**Comment by vgoklani** [comment]
Why were the environment variables removed?
