### ISSUE TITLE
Why not add vim to it

### ISSUE THREAD

**Issue by Amado-github** [docker-library/rabbitmq#537]
Why not add vim to it

**Comment by tianon** [comment]
The images are intentionally kept minimal -- most users do not need `vim`, especially inside an image designed for _running_ RabbitMQ (editing happens outside the container, usually via some kind of container orchestration system like `docker-compose`, Docker Swarm, or Kubernetes), so adding niceties like `vim` would just make the image unnecessarily bigger (both on disk and during transport).
