### ISSUE TITLE
Do not use RABBITMQ_LOGS to configure logging

### ISSUE THREAD

**Issue by lukebakken** [docker-library/rabbitmq#554]
TL;DR a configuration file should be used instead in `/etc/rabbitmq/conf.d` to set defaults.

Full discussion here:

https://github.com/rabbitmq/rabbitmq-server/issues/4303

cc @gerhard @mkuratczyk in case one of you remembers why `RABBITMQ_LOGS=-` was chosen. Thanks!

**Comment by tianon** [comment]
I believe it was chosen because it pre-dates the ini-style configuration
file format. 😅

**Comment by lukebakken** [comment]
Thanks. I'll open a PR with our suggested changes.
