### ISSUE TITLE
3.9.15-management-alpine is missing the amd64 arch

### ISSUE THREAD

**Issue by greut** [docker-library/rabbitmq#556]
![Screenshot 2022-04-14 at 09-05-16 rabbitmq Tags Docker Hub](https://user-images.githubusercontent.com/1388/163332318-f60b4454-d830-4485-a8b8-93c86bfb34d8.png)

3.9-management-alpine has it...

![Screenshot 2022-04-14 at 09-07-33 rabbitmq Tags Docker Hub](https://user-images.githubusercontent.com/1388/163332533-ae7dc326-b989-495e-9aa6-e142eba17685.png)

**Comment by wglambert** [comment]
It's there now 
![image](https://user-images.githubusercontent.com/26428991/163438516-fe2506b7-56a9-46d4-9a19-78aacf6ef357.png)

The architectures are built in sequence so it can take a few hours after an update for all architectures to be pushed
See also https://github.com/docker-library/rabbitmq#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

And the build status on that page
![image](https://user-images.githubusercontent.com/26428991/163439122-68a0ce89-8d21-4f80-9453-ac5ba29c4753.png)
