### ISSUE TITLE
bump to Erlang 25?

### ISSUE THREAD

**Issue by yosifkit** [docker-library/rabbitmq#568]
The releases notes of both RabbitMQ server [3.10.7](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.10.7) and [3.9.22](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.9.22) say they support Erlang 25:

> This release requires at least Erlang 24.x, and supports Erlang 25.

Though, it doesn't look like https://www.rabbitmq.com/which-erlang.html is updated quite yet. :heart:

I'm not certain when we should bump the erlang version. :confused: Perhaps we wait for the next minor bumps (like `3.10.8` and `3.9.23`), or maybe only on the next major, (like `3.11.x`). :thinking: We could also do it without waiting for a bump at all (assuming it is safe like previous previous erlang 24 bump: https://github.com/docker-library/rabbitmq/pull/486).

cc @michaelklishin should we move the images to erlang 25? Maybe just the `3.10` images?

**Comment by michaelklishin** [comment]
Just the `3.10` ones for now. `3.9.x` does run on Erlang 25 but we don't promote that fact since Erlang 25 support is a "feature", too.

**Comment by michaelklishin** [comment]
Towards the end of its lifecycle next spring, Erlang 24 will be close to its EOL, then moving 3.9 to 25, even if for a month or two, would make sense.
