### ISSUE TITLE
FYI: RabbitMQ 3.11 will require Erlang 25 and Elixir 1.13

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#575]
FYI, RabbitMQ 3.11 [will require Erlang 25 and Elixir 1.13](https://github.com/rabbitmq/rabbitmq-server/pull/5811). I don't think this image will be affected
but figured we should mention it to this community :)

**Comment by tianon** [comment]
Yep, we're already on Erlang 25 for the pre-releases :smile:

https://github.com/docker-library/rabbitmq/blob/62b837a84aee6b89ea2fe97ed33419f41fa6ff9c/3.11-rc/ubuntu/Dockerfile#L34

(even 3.10 is on 25 :eyes:)

We don't currently install Elixir, though -- should we be?  Does that come with the RabbitMQ bundle?  (Perhaps it's an optional thing?)

**Comment by michaelklishin** [comment]
It's great that 3.10 is on 25, by the way.

**Comment by michaelklishin** [comment]
You don't need to provision Elixir, it's a compile-time dependency.
