### ISSUE TITLE
Relatively serious issue in Erlang/OTP 25.1

### ISSUE THREAD

**Issue by lukebakken** [docker-library/rabbitmq#582]
https://github.com/erlang/otp/issues/6328

This doesn't seem like much but it will affect everyone using the docker image with Kubernetes -

https://groups.google.com/g/rabbitmq-users/c/etETZLpq-xI

Would it make sense to revert?

Going forward, should there be a policy to wait on an new Erlang major or minor for a period of time? Sort of like how you don't upgrade Windows until the first service pack 😉

**Comment by mkuratczyk** [comment]
Erlang 25.1.1 has been released. Can we bump to that version please?

**Comment by tianon** [comment]
> Erlang 25.1.1 has been released. Can we bump to that version please?

Yep, absolutely; see https://github.com/docker-library/official-images/pull/13276

> Going forward, should there be a policy to wait on an new Erlang major or minor for a period of time? Sort of like how you don't upgrade Windows until the first service pack :wink:

If we did have such a policy, 25.1 is the first "service pack" for Erlang OTP 25, so it would be the release we would've upgraded on (and thus we would've run into this issue anyhow).
