### ISSUE TITLE
qemu error

### ISSUE THREAD

**Issue by kwonglau** [docker-library/rabbitmq#583]
Getting a Segmentation fault error when building a mutli-arch image

```
 > [linux/arm64 5/5] RUN rabbitmq-plugins enable rabbitmq_consistent_hash_exchange:
#0 1.284 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#0 1.298 Segmentation fault
------
Dockerfile:11
--------------------
   9 |     #RUN apt-get -y install qemu-system
  10 |     
  11 | >>> RUN rabbitmq-plugins enable rabbitmq_consistent_hash_exchange
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c rabbitmq-plugins enable rabbitmq_consistent_hash_exchange" did not complete successfully: exit code: 139
```

I'm using a intel base mac to build the image

Dockerfile:
```
FROM rabbitmq:3.11.0

RUN apt-get update

RUN apt-get -y autoremove

RUN apt-get -y upgrade

RUN rabbitmq-plugins enable rabbitmq_consistent_hash_exchange
```
command:
```
docker buildx build --platform linux/amd64,linux/arm64/v8 \
  -t -rabbitmq:3.11.0 . \
  --push
```

**Comment by kwonglau** [comment]
there is no issue with rabbitmq:3.10.6

**Comment by tianon** [comment]
This sounds like it's probably a bug in QEMU's emulation -- if you're using Docker Desktop (and are on the latest up-to-date version), I would suggest filing an issue with details on https://github.com/moby/qemu.

**Comment by siwa-pparzer** [comment]
got the same issue when building rabbitmq on an arm64 drone-runner, building an amd64 image:

```
FROM --platform=linux/amd64 rabbitmq:latest
ARG VHOST

RUN rabbitmq-plugins enable --offline rabbitmq_management
RUN rabbitmq-plugins enable --offline rabbitmq_stomp
RUN rabbitmq-plugins enable --offline rabbitmq_web_stomp
RUN echo "stomp.default_vhost = $VHOST" >> /etc/rabbitmq/rabbitmq.conf
```

errors with

```
#5 [2/5] RUN rabbitmq-plugins enable --offline rabbitmq_management
#5 1.617 Segmentation fault (core dumped)
#5 ERROR: executor failed running [/bin/sh -c rabbitmq-plugins enable --offline rabbitmq_management]: exit code: 139

 > [2/5] RUN rabbitmq-plugins enable --offline rabbitmq_management:

#5 1.617 Segmentation fault (core dumped)

ERROR: failed to solve: executor failed running [/bin/sh -c rabbitmq-plugins enable --offline rabbitmq_management]: exit code: 139
```

already tried different tags:

latest, 3.10, 3.10.6, management - with the same result

**Comment by michaelklishin** [comment]
@siwa-pparzer you are looking at https://github.com/erlang/otp/pull/6340, which affects multi-arch builds. That PR will likely only ship in Erlang 25.1.

**Comment by sagimann** [comment]
I'm getting the exact same error, but when building arm6 only (not multi-arch). If this is resolved in Erlang 25.1 as @michaelklishin  mentioned, is it somehow possible to upgrade erlang inside the Rabbit 3.11 docker? I tried to upgrade it through apt-get inside the docker:
```
FROM rabbitmq-3.11:management
apt-get install -y erlang
```
It installed erlang 25.1 however the same error occured during build afterwards. Maybe rabbitmq didn't use the new version? Is there some post-install step I am missing?

**Comment by lukebakken** [comment]
@sagimann this branch will build the Ubuntu images using Erlang `master`:

https://github.com/lukebakken/rabbitmq-1/tree/lukebakken/erlang-master

**Comment by siwa-pparzer** [comment]
rabbitmq updated the OTP Version to 25.2
https://github.com/docker-library/rabbitmq/commit/eb98ea3aee0df586882c4118c74b870f11072bbf
but the error still occurs
