### ISSUE TITLE
RabbitMQ 3.11.8 in k8s

### ISSUE THREAD

**Issue by fontexD** [docker-library/rabbitmq#603]
im using the latest RabbitMQ 3.11.8 in k8s.

im getting this error in the limit tab, tried just about everything which google have of solutions

https://postimg.cc/K17dRxM4

had the same issue for the user tab to start with, but a refresh of the browser cache fixed that, but cant seem to get it to work on limit tab this is my cm

  enabled_plugins: |
    [rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s,rabbitmq_prometheus].
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672
    cluster_formation.peer_discovery_backend  = k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname

**Comment by Zerpet** [comment]
I can reproduce this in a container locally with the current `3.11.8-management` tag. It's not related to k8s or Docker. Can you open an issue in [rabbitmq/rabbitmq-server](https://github.com/rabbitmq/rabbitmq-server/issues) ?

**Comment by fontexD** [comment]
awesome, ill create a issue over there, thans for your time :=)!

**Comment by fontexD** [comment]
ref to issue in rabbitmq:server

https://github.com/rabbitmq/rabbitmq-server/issues/7142
