### ISSUE TITLE
Cannot set config from ENV vars

### ISSUE THREAD

**Issue by nhalm2** [docker-library/rabbitmq#63]
If I try to set a configuration option with  `-e` flag I get:
`/docker-entrypoint.sh: line 56: /etc/rabbitmq/rabbitmq.config: Permission denied
`

It looks like the `docker-entrypoint.sh` is not able to write to `/etc/rabbitmq/rabbitmq.config`.

If I changed the `Dockerfile` to add the chmod line this prolem is resolved.

    RUN echo '[{rabbit, [{loopback_users, []}]}].' > /etc/rabbitmq/rabbitmq.config
    RUN chmod 666 /etc/rabbitmq/rabbitmq.config

Is that a pull request that will work for you guys?

**Comment by nhalm2** [comment]
I guess we could probably chmod the group to rabbitmq for that file?

**Comment by tianon** [comment]
This was fixed in #62, just waiting on a PR to https://github.com/docker-library/official-images

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/1390. :+1:
