### ISSUE TITLE
Enable JIT in Erlang build stage for ARM64

### ISSUE THREAD

**Issue by Zerpet** [docker-library/rabbitmq#647]
https://github.com/docker-library/rabbitmq/blob/0192a912d656a74b27e8d3ebe0df1aa0d08dd92c/Dockerfile-ubuntu.template#L141-L147

From the comment in the script, JIT is supported as of Erlang 25.x. This PR https://github.com/erlang/otp/pull/4869 also suggests that it's available in Erlang 25+. Given that RabbitMQ 3.11 and 3.12 [require Erlang 25 as minimum version](https://rabbitmq.com/which-erlang.html), I propose to remove above's switch case, or at least consider the Erlang/RabbitMQ version in addition to the architecture.

**Comment by yosifkit** [comment]
https://github.com/docker-library/rabbitmq/blob/0192a912d656a74b27e8d3ebe0df1aa0d08dd92c/versions.sh#L19-L24

Now that we only use Erlang 25.x for all the versions of RabbitMQ, I think it is probably safe to add `|arm64` to the case statement (and update the comment wording and the link to https://github.com/erlang/otp/blob/OTP-25.3.2.2/erts/configure#L24306C5-L24347).
