### ISSUE TITLE
3.12.10 and 3.11.26 images are not available

### ISSUE THREAD

**Issue by mkuratczyk** [docker-library/rabbitmq#678]
Hi. The commits to bump to 3.11.26 and to 3.12.10 were merged a week ago but these images are still not available.
Could you please check what happened? 

https://github.com/docker-library/rabbitmq/commit/b6b4cd71df7d15918afbd4e7ab021266bb2310b7
https://github.com/docker-library/rabbitmq/commit/2740bd4780a9e5f6abc22f9ebddc399e021b7a28

Thank you,

**Comment by LaurentGoderre** [comment]
This is the one that gets it to the registry: https://github.com/docker-library/official-images/pull/15772

Thos versions are in registry now
