### ISSUE TITLE
Disable cleartext authentication mechanisms in the AMQP configuratio

### ISSUE THREAD

**Issue by pmashaba** [docker-library/rabbitmq#681]
We run a vulnerability scan and it reported this vulnerability, "AMQP Cleartext Authentication". When I check the rabbitmq file on the server and container, I don't see anything wrong. Is the auth_mechanisms set to "PLAIN" on the image?

**Comment by lukebakken** [comment]
Yes, by default this image ships with cleartext authentication. It is up to users to configure TLS if they wish authentication to be encrypted.
