### ISSUE TITLE
Provide a 4.0 (preview) flavor

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#712]
Hey folks 👋 

FYI, [RabbitMQ `4.0.0-beta.1`](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v4.0.0-beta.1) has just dropped, and it would be great to have a 4.0 variation of this image so that more people can test these preview releases.

**Comment by yosifkit** [comment]
Sure! Just a few comments/questions to make sure we use the best supported versions of OS and libraries:
- We should stick to erlang 26 (not move to [27](https://www.rabbitmq.com/docs/which-erlang#erlang-27-support))
- Should we stick to Alpine 3.19 and Ubuntu 22.04 or move to Alpine 3.20 and/or Ubuntu 24.04 LTS?
- Should we stick to OpenSSL `3.1` or is there a newer version that we should use?

**Comment by michaelklishin** [comment]
@yosifkit 

1. We don't support 27 yet. Using 26.2.5.2 would therefore the best option
2. I don't have an opinion but I'd say, let's go with the latest versions of those two distributions
3. We have moved to 3.3 for RabbitMQ's own builds recently, can we adopt the same series in the image?

Thank you for the prompt response!

**Comment by yosifkit** [comment]
That all sounds fine. Swapping in OpenSSL 3.3 should hopefully be painless; we'll see how the build tests go. PR incoming shortly.

**Comment by michaelklishin** [comment]
Not sure if the 4.x flavor should auto update but there's a `4.0.0-beta.2` already to match what's shipped in `3.13.5`.

**Comment by tianon** [comment]
It's supposed to auto-update, but it only checks for new releases four times a day -- it _should've_ picked it up by now, so we'll dig a little and see what's going on.

**Comment by tianon** [comment]
Ok, figured it out -- it looks like https://github.com/rabbitmq/rabbitmq-server/releases/tag/v4.0.0-beta.2 is missing the artifacts that normally come with releases (and that "Source Code Archives" on that page implies should be there) :eyes:

Did some automation fail somewhere?

**Comment by michaelklishin** [comment]
Yup, I have a guess what might have failed. I have triggered a `beta.3` build to match a freshly released `3.13.6`.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/releases/tag/v4.0.0-beta.3 has all the artifacts.

**Comment by yosifkit** [comment]
Thanks! https://github.com/docker-library/rabbitmq/commit/a1177f4c71c9c3214bd1ec3f653d1dbf91e0d3fb -> https://github.com/docker-library/official-images/pull/17245

**Comment by michaelklishin** [comment]
I think we can consider this resolved :) Thanks everyone!
