### ISSUE TITLE
Consider including logrotate

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#717]
Apparently some folks run containers and log to local file storage. For such cases, it would be great to include `logrotate` into the image, and I guess making mounting a config file easier.

Thoughts?

**Comment by michaelklishin** [comment]
The background of this was https://github.com/rabbitmq/rabbitmq-server/discussions/11873#discussioncomment-10207880.

Given that I have updated the docs to explain the behavior https://github.com/rabbitmq/rabbitmq-website/commit/2a8d9ea8aeb54ca7237be04eacdfd3100db1e71b, maybe this is not really relevant.

Although `logrotate` is more powerful and flexible than anything a tool such as RabbitMQ usually provides as a built-in option.

**Comment by Zerpet** [comment]
Logging to local storage is a bit of an anti-pattern in containers. If you want to have logs for long term storage and analysis, you would use a different [Docker log driver](https://docs.docker.com/config/containers/logging/configure/), or configure your app to emit logs via OpenTelemetry, and ship them to a logging system. The later, of course, it's not possible in RabbitMQ today (it may never be). It is possible, however, to configure a logging driver to write to an external system e.g. Splunk, or to write `stdout/stderr` to a local file in the Docker host, and ingest that file by a logging system.

**Comment by michaelklishin** [comment]
Yes, I agree. Let's close this.
