### ISSUE TITLE
Missing "-" for indicating set options in Dockerfile

### ISSUE THREAD

**Issue by grmhskidata** [docker-library/rabbitmq#728]
In the Dockerfile for rabbitmq:4-management-alpine https://github.com/docker-library/rabbitmq/blob/444c58b5b51433019a9422737ee98b05adcf7e06/4.0/alpine/management/Dockerfile#L9 the shell builtin command "set" is called with argument "eux" instead of the dash (or plus sign) indicating options to the "set" command. 
For example, the Dockerfile for rabbitmq:4-alpine calls "set -eux" instead.

**Comment by tianon** [comment]
Oh amazing, great catch!
