### ISSUE TITLE
When to switch to Erlang 27

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#734]
This is a heads-up issue.

RabbitMQ `4.0.4` will mark Erlang 27 as supported https://github.com/rabbitmq/rabbitmq-server/issues/12603. Technically it already is, starting with `27.1.2` which addressed an issue that seriously affects RabbitMQ users who use TLS for client connections.

I suggest that we switch this image to Erlang 27 after RabbitMQ `4.0.4` ships.

**Comment by tianon** [comment]
Oh neat, sounds sane to me!  To make sure we're clear, you mean 4.0.x should switch to 27, but 3.13 and 3.12 should stay as-is, right?

**Comment by michaelklishin** [comment]
3.13 does not support Erlang 27 and I'm not currently sure if it will or when. In any case, I'd not expect any future open source 3.13.x releases.

And 3.12.x has been out of support since late March 2024 or so when our new single series community support policy was adopted.

**Comment by tianon** [comment]
Fair, thanks for clarifying!  So I guess dropping 3.12 entirely is uncontroversial - I think we should probably drop 3.13 as well (so we're clearly communicating that it's not "open source supported" anymore); we can always bring it back if there ends up being more open source releases of it. :+1: (I'll make a PR for those two shortly so we can keep this focused on Erlang 27 in 4.0.4 :eyes:)

**Comment by michaelklishin** [comment]
Yup, dropping 3.12 should be a no-brainer https://github.com/docker-library/rabbitmq/issues/735.

I have shared what I'd do with 3.13.x in the same issue.
