### ISSUE TITLE
rabbitmq unusable, way too slow

### ISSUE THREAD

**Issue by Mwea** [docker-library/rabbitmq#74]
Hi ! 
I'm trying to use this image in my project but it appears that the rabbitmq-server is so slow that i litterally can't use it. It takes about 2 minutes to be launched, and if I try to go to 127.0.0.1:15672 it can take about one minute.. 
Is this an issue known  ?

**Comment by michaelklishin** [comment]
First steps should be looking at the log files and tools such as iostat and vmstat, not assuming it is a general issue.

**Comment by Mwea** [comment]
My bad, this was a wrong settings coming from my docker-compose.

**Comment by LoveXiaoLiu** [comment]
> My bad, this was a wrong settings coming from my docker-compose.

I have the same problem，What do I need to set up.

**Comment by michaelklishin** [comment]
@LoveXiaoLiu start with narrowing the problem down by looking at [monitoring data](), making sure the node is not pegged to [a single core/scheduler](https://www.rabbitmq.com/runtime.html) and seeing what `vmstat` and runtime thread stats look like. There can be any number of limiting factors and without knowing *anything* about your system and load profile there is *nothing* that can be suggested.
