### ISSUE TITLE
`3.13` build failing on `arm32v7`

### ISSUE THREAD

**Issue by yosifkit** [docker-library/rabbitmq#745]
The `gosu` from Ubuntu 22.04 was recently [rebuilt](https://launchpad.net/ubuntu/+source/gosu/1.14-1ubuntu0.1) with go `1.18.1`. And on `arm32v7` happens to hit a regression in go (https://github.com/golang/go/issues/51776, https://github.com/golang/go/commit/4f4542479d27161d70b22557c52f182c0332ac7b). So, the build fails when it tries to `gosu nobody true`. 

We have a few options that I can see:
- swap to downloading `gosu` directly from [upstream releases](https://github.com/tianon/gosu/releases)
- wait for a fix/rebuild in Ubuntu 22.04 (while the `3.13` image for arm32v7 stays where it was on its last build on 2014-11-04)
- upgrade to Ubuntu 24.04 (not sure if this is feasible for 3.13)
- drop `arm32v7` for the 3.13 images
- something else?

Failing log: 
```console
+ apt-get install --yes --no-install-recommends ca-certificates gosu tzdata
...
Setting up gosu (1.14-1ubuntu0.1) ...
...
+ gosu nobody true
panic: unaligned 64-bit atomic operation
preempt off reason: doAllThreadsSyscall
fatal error: panic during preemptoff

goroutine 1 [running, locked to thread]:
runtime.throw({0x141c82, 0x17})
	runtime/panic.go:992 +0x5c fp=0xc60da4 sp=0xc60d90 pc=0x47334
panic({0x12ba58, 0x16cfc0})
	runtime/panic.go:780 +0x710 fp=0xc60e04 sp=0xc60da4 pc=0x4717c
runtime/internal/atomic.panicUnaligned()
	runtime/internal/atomic/unaligned.go:8 +0x24 fp=0xc60e10 sp=0xc60e04 pc=0x124a0
runtime/internal/atomic.Load64(0xc366e4)
	runtime/internal/atomic/atomic_arm.s:280 +0x14 fp=0xc60e14 sp=0xc60e10 pc=0x127f4
syscall.runtime_doAllThreadsSyscall(0xce, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	runtime/os_linux.go:829 +0x360 fp=0xc60e84 sp=0xc60e14 pc=0x74088
syscall.AllThreadsSyscall(0xce, 0x0, 0x0, 0x0)
	syscall/syscall_linux.go:987 +0x6c fp=0xc60eb0 sp=0xc60e84 pc=0xb0554
syscall.Setgroups({0x2356cc, 0x0, 0x0})
	syscall/syscall_linux.go:291 +0x124 fp=0xc60ed8 sp=0xc60eb0 pc=0xaf620
main.SetupUser({0xffb7bd42, 0x6})
	github.com/tianon/gosu/setup-user.go:35 +0xf4 fp=0xc60f28 sp=0xc60ed8 pc=0x115bb4
main.main()
	github.com/tianon/gosu/main.go:77 +0x480 fp=0xc60fc0 sp=0xc60f28 pc=0x1157dc
runtime.main()
	runtime/proc.go:250 +0x26c fp=0xc60fec sp=0xc60fc0 pc=0x49e44
runtime.goexit()
	runtime/asm_arm.s:824 +0x4 fp=0xc60fec sp=0xc60fec pc=0x7707c
```

**Comment by michaelklishin** [comment]
@yosifkit as far as RabbitMQ and Erlang go, you absolutely can move to Ubuntu 24.04. That's what we use in many of our workflows.

**Comment by tianon** [comment]
I was wondering about that single outlier still on 22.04 when I was doing #744 :joy: :heart:
