### ISSUE TITLE
E: Version '3.6.0-1' for 'rabbitmq-server' was not found

### ISSUE THREAD

**Issue by Omnipresent** [docker-library/rabbitmq#75]
I'm on OSX and building like this:

`docker build -t rabbitmq rabbitmq`

I get the following error:

`E: Version '3.6.0-1' for 'rabbitmq-server' was not found`

I'm using docker-machine and virtualbox

**Comment by tianon** [comment]
Probably just needs a version bump; as a side note, any particular reason
you're building from source instead of just using the pre-built image?

**Comment by michaelklishin** [comment]
We released `3.6.1` earlier today but haven't announced it yet as not all mirrors are updated. So yes, please bump the version.

**Comment by tianon** [comment]
e9e416f :+1:
