### ISSUE TITLE
RabbitMQ 3.6.2 will have a dependency on socat

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#77]
This is a heads-up, not an issue: in RabbitMQ 3.6.2, packages will depend on `socat` but [apparently with some installation methods that dependency is ignored](https://groups.google.com/forum/#!topic/rabbitmq-users/HiKSUkaPZtM).

It would be very nice if this project installed the `socat` package before installing RabbitMQ.

**Comment by Gillingham** [comment]
```
There is a change coming in 3.6.2 that we'd like to give you a heads-up about.
RabbitMQ 3.6.2 will have an optional dependency on `socat` [1].
With it, we can work around a systemd bug and notify systemd of RabbitMQ
startup and (OS) process ID correctly.
```
I'm confused why the docker image needs socat, the rabbitmq inside a container doesn't communicate with systemd, so this work-around wouldn't apply, or am I mistaken?

**Comment by tianon** [comment]
Regardless of whether it's _necessary_ for the way we use RabbitMQ, the way we install appears to be pulling it in appropriately, so we're good! :+1:

```console
$ docker pull rabbitmq
Using default tag: latest
latest: Pulling from library/rabbitmq

5c90d4a2d1a8: Already exists 
6089c6f096b9: Already exists 
23b5bfce8ad4: Already exists 
13946ed57420: Already exists 
f87077e96db6: Already exists 
91b271af1b6f: Already exists 
ae50560319c7: Already exists 
031a1dcbb47d: Already exists 
6ca65936d19d: Already exists 
44da2c895b8f: Already exists 
b33963637358: Already exists 
03658b60e6d0: Already exists 
cb39c06c1a97: Already exists 
437c56d51ec5: Pull complete 
fe7ca962df56: Pull complete 
Digest: sha256:95c9ddccf4734427e70729a103e4ca45916c8ab58a9c93a8299c0a6e0eb4aedd
Status: Downloaded newer image for rabbitmq:latest
$ docker run -it --rm rabbitmq socat --help
2016/07/08 00:17:03 socat[1] E unknown option "--help"; use option "-h" for help
```

**Comment by Gillingham** [comment]
"Regardless of whether it's necessary for the way we use RabbitMQ, the way we install appears to be pulling it in appropriately, so we're good!"

There's no point in adding it to the image, so why increase the image size by any amount, surely there needs to be some justification behind it.

**Comment by yosifkit** [comment]
@Gillingham, it is an apt dependency, we can't easily skip just `socat`.

**Comment by Gillingham** [comment]
@yosifkit oops, I was thinking I was looking at https://github.com/docker-library/rabbitmq/pull/95/files#diff-3254677a7917c6c01f55212f86c57fbfR41
which manually added it into the Dockerfile, sorry for the extra noise. It's unfortunate more and more systemd work-arounds are getting pushed downstream.
