### ISSUE TITLE
Rabbit mq docker image is not exposing port 5672

### ISSUE THREAD

**Issue by kkorada** [docker-library/rabbitmq#82]
tried running docker image 
docker run -d --hostname MYHOST--name some-rabbit rabbitmq

BUT LOGS ARE SHOWING 
started TCP Listener on [::]:5672

PORTS LISTED IN DOCKER PS
 4369/tcp, 5671-5672/tcp, 25672/tcp

when i try to connect MQ with simple java client it is throwing connection execption.

and also netstat is not listing 5672 port

and i also checked that MYHOST is being resolved to IP address when i ping.

**Comment by Gillingham** [comment]
You need to expose the port from the docker instance, add -p 5672:5672 to your docker run line.

**Comment by podholadavid** [comment]
`docker run -d --hostname MYHOST  -p 5672:5672 --name some-rabbit rabbitmq`
